### ISSUE TITLE
Standup Signal Amplifier I does not apply Maximum Locked Targets bonus

### ISSUE THREAD

**Issue by BloodKhanid** [pyfa-org/Pyfa#1385] opened 2018-02-15 09:23 UTC
If you fit Standup Signal Amplifier I to the citadel it does not apply Maximum Locked Targets bonus.
pyfa v2.0.0b1 on Win10 Ent

**Comment by blitzmann** [comment] 2018-02-16 00:45
Possibly a duplicate of #1387 which is a general issue of all the brokenness with citadels

**Closed** 2018-02-16 06:06 UTC
