### ISSUE TITLE
Pyfa error

### ISSUE THREAD

**Issue by KaZaK007** [pyfa-org/Pyfa#1829] opened 2018-12-20 13:55 UTC

**Comment by KaZaK007** [comment] 2018-12-20 14:05
Occurs when trying to add a character. 
Used SSO mode: pyfa.io
Login Authentication Method: Manual
When you type the response from the server EVE online this error is occurring.
When using the: Local Server - Pyfa Method, no response is received

![2018-12-20_17-52-56](https://user-images.githubusercontent.com/34710764/50289285-d1489d00-0481-11e9-9616-2a96839ec708.png)

**Comment by KaZaK007** [comment] 2018-12-20 14:07
pyfa vv2.7.0
EVE Data Version: 1435052 (2018-12-12 13:48:30)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.1
Requests version: 2.21.0
Dateutil version: 2.7.5

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 344, in connect
  File "C:\Python36\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Python36\lib\ssl.py", line 689, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 367, in increment
  File "C:\Python36\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 344, in connect
  File "C:\Python36\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Python36\lib\ssl.py", line 689, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\mainFrame.py", line 245, in ShowSsoLogin
  File "C:\projects\pyfa\service\esi.py", line 150, in handleLogin
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 546, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 344, in connect
  File "C:\Python36\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Python36\lib\ssl.py", line 689, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 367, in increment
  File "C:\Python36\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 344, in connect
  File "C:\Python36\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 407, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 814, in __init__
  File "C:\Python36\lib\ssl.py", line 1068, in do_handshake
  File "C:\Python36\lib\ssl.py", line 689, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\mainFrame.py", line 245, in ShowSsoLogin
  File "C:\projects\pyfa\service\esi.py", line 150, in handleLogin
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 546, in get
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

**Comment by blitzmann** [comment] 2018-12-20 14:53
@KaZaK007 thanks for the additional information! So this is using the manual method, huh?

Originally thought this as a duplicate of #1823, but now thinking this may be somewhat different. That being said, I cannot reproduce myself.

It looks like it's a SSL handshake issue... are you by chance behind a firewall that may be sniffing at certs (company firewall for example)?

**Comment by blitzmann** [comment] 2019-01-02 02:18
@KaZaK007 Are you still getting this error?

This is a shot in the dark, but I've committed what might be a workaround "fix" wherein we disable SSL verification. Before I delve too much farther down into making this a preference for the user to select, I want to know if it fixes this specific problem.

Can you download and run the zip located here: https://ci.appveyor.com/project/blitzmann/pyfa/build/artifacts

This is a build with SSL verification disabled. If this works, I will develop a more permanent workaround where this option can be set in the preferences. 

I honestly don't know what would cause this error other than the host refusing to accept the connection.

**Comment by KaZaK007** [comment] 2019-01-09 05:51
Hi! I'm not sure I'll be able to test this build because it worked after a couple of days. 02.01.2019, 05:18, "Ryan Holmes" <notifications@github.com>:@KaZaK007 Are you still getting this error?This is a shot in the dark, but I've committed what might be a workaround "fix" wherein we disable SSL verification. Before I delve too much farther down into making this a preference for the user to select, I want to know if it fixes this specific problem.Can you download and run the zip located here: https://ci.appveyor.com/project/blitzmann/pyfa/build/artifactsThis is a build with SSL verification disabled. If this works, I will develop a more permanent workaround where this option can be set in the preferences.I honestly don't know what would cause this error other than the host refusing to accept the connection.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  -- С уважением,  Владимир Казаков  (927)52-77-987

**Comment by blitzmann** [comment] 2019-03-02 23:02
Going to close this as a fluke then - might have been network disruption or something, especially if it started working on it's own again. :)

**Closed** 2019-03-03 00:30 UTC
