### ISSUE TITLE
Linux GUI information formatting issue on fitting updates

### ISSUE THREAD

**Issue by tqueiros** [pyfa-org/Pyfa#520] opened 2016-02-14 13:27 UTC
Annoying wx bug/glitch, everytime a (any or none really) fit is updated the right side information gets all messed up. Eventually its unusable check pic below.

http://i.imgur.com/4E9lw08.png
https://lowsec.space/pyfa.ogv (issue is more apparent in video)

Platform: Linux (Fedora 23)
Python: 2.7
wxPython: 3.0.2
wxGTK: 3.0.2
SQLAlchemy: 1.0.11

**Comment by blitzmann** [comment] 2016-02-14 17:19
I can't reproduce with Debian unfortunately, following the exact same steps as you.

Can you tell me if this happens with an empty fit? (just open a fit and spam the EHP button)

Then add 1 rig, and do the same, let me know what happens.

**Comment by tqueiros** [comment] 2016-02-15 12:54
Happens on an empty fit as well as no fit at all.

Seems like anything that updates the right most panel add padding to some of the information

Weird you can't reproduce, can very well be some Fedora specific issue.

**Comment by Neugeniko** [comment] 2016-02-15 21:01
I have tried reproducing with no luck on Slackware 14.1. Using both source package 1.19.0 and 1.19.1 Linux zip.

EVE Data: 	1006189
Python: 		2.7.5
wxPython: 	3.0.0.0
SQLAlchemy: 	0.9.6

Cheers,
Neug

**Comment by blitzmann** [comment] 2016-11-24 02:50
@tqueiros can you still reproduce this problem?

**Comment by blitzmann** [comment] 2017-04-11 04:35
Closing as I can't reproduce :(((

If this is still a thing, please reopen and let me know of any updates you may have. Thanks!

**Closed by blitzmann** 2017-04-11 04:35 UTC
