### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by garland-tim** [pyfa-org/Pyfa#1266] opened 2017-08-09 06:43 UTC
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

### Expected behavior:
Trying to log in to export fit via CREST

### Actual behavior:
SSO to CREST is failling

### Detailed steps to reproduce:
When I go to CREST>Log in to EVE I get the error after logging in and authorizing for my character.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Legion, Sleeper Hacker]

Heat Sink II
Heat Sink II
Damage Control II
Imperial Navy Energized Adaptive Nano Membrane
Imperial Navy Energized Adaptive Nano Membrane
Medium Armor Repairer II
Imperial Navy 1600mm Steel Plates

10MN Afterburner II
Tracking Computer II, Tracking Speed Script

Covert Ops Cloaking Device II
Sisters Core Probe Launcher, Sisters Core Scanner Probe
Heavy Pulse Laser II, Imperial Navy Multifrequency M
Heavy Pulse Laser II, Imperial Navy Multifrequency M
Heavy Pulse Laser II, Imperial Navy Multifrequency M
Heavy Pulse Laser II, Imperial Navy Multifrequency M
Heavy Pulse Laser II, Imperial Navy Multifrequency M
Heavy Pulse Laser II, Imperial Navy Multifrequency M

Medium Trimark Armor Pump I
Medium Anti-Thermal Pump I
Medium Trimark Armor Pump I

Legion Core - Augmented Antimatter Reactor
Legion Defensive - Covert Reconfiguration
Legion Offensive - Liquid Crystal Magnifiers
Legion Propulsion - Intercalated Nanofibers

Conflagration M x4
Scorch M x4
Optimal Range Script x1
Sisters Core Scanner Probe x8
Mobile Depot x1
Mobile Tractor Unit x1
Ligature Integrated Analyzer x1

### Release or development git branch? Please note the release version or commit hash:
Release 1.30.0 stable - YC119.7 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.30.0 Stable - YC119.7 1.0
pyfa root: D:\pyfa-1.30.0-yc119.7-1.0-win\pyfa
save path: D:\pyfa-1.30.0-yc119.7-1.0-win\pyfa\saveddata
fs encoding: mbcs

EXCEPTION: The C++ part of the ExportToEve object has been deleted, attribute access no longer allowed.

  File "D:\pyfa-1.30.0-yc119.7-1.0-win\pyfa\library.zip\gui\crestFittings.py", line 245, in ssoLogin
    self.updateCharList()
  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__

**Comment by garland-tim** [comment] 2017-08-09 06:49
Closing and reopening Pyfa seems to have fixed it. Looks like it might happen when trying to authorize after an authorization times out.

**Comment by blitzmann** [comment] 2017-09-19 05:07
Duplicate of #1260

> Looks like it might happen when trying to authorize after an authorization times out.

Exactly. I have an idea of why this is happening, need to sit down and dig deeper and develop a solution :)

**Closed by blitzmann** 2017-09-19 05:07 UTC
