### ISSUE TITLE
Cant place items in "Additions" tab

### ISSUE THREAD

**Issue by GingkathFox** [pyfa-org/Pyfa#1888] opened 2019-03-19 17:45 UTC
### Expected behavior:
Item appears in Additions tab

### Actual behavior:
```css
pyfa vv2.7.0
EVE Data Version: 1435052 (2018-12-12 04:48:30)

OS version: Darwin-18.2.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/fitCommands/calc/fitAddCargo.py", line 22, in Do
  File "/Users/ryan/pyfa/eos/db/saveddata/queries.py", line 83, in checkAndReturn
  File "/Users/ryan/pyfa/eos/db/saveddata/queries.py", line 57, in setCache
  File "/Users/ryan/pyfa/eos/db/saveddata/queries.py", line 216, in getFit
TypeError: Need integer as argument
```

### Detailed steps to reproduce:
Drag a item onto the Additions tab and release.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
none

### Release or development git branch? Please note the release version or commit hash:
2.7.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
macOS 10.14.3

### Other relevant information:
I have no idea how to use this, maybe i did something wrong? ^w^;

**Comment by blitzmann** [comment] 2019-03-19 18:44
Additions tab being the cargo tab? Which item were you attempting to drag?

**Comment by GingkathFox** [comment] 2019-03-20 01:06
I was attempting to drag the Iron Charge S, and I dunno which tab, the window was too small for any text to show (I realized that after seeing screenshots)

**Comment by DarkFenX** [comment] 2019-03-20 05:10
Post screenshots then. It's unclear what's the issue is without further explanation.

**Comment by GingkathFox** [comment] 2019-03-20 23:29
![Screen Shot 2019-03-20 at 7 29 32 PM](https://user-images.githubusercontent.com/33764485/54725711-7f79e680-4b46-11e9-88f3-a2926fe07ce1.png)
So apparently i tried to put it into the cargo slot.

**Comment by blitzmann** [comment] 2019-03-21 00:32
You dont have a fit open. There must be a bug in that it doesnt check this before attempting it.

Should be a simple fix

**Comment by GingkathFox** [comment] 2019-03-21 01:07
ok, thanks!

**Comment by blitzmann** [comment] 2019-03-21 01:52
Fixed with the above commit. Thanks for reporting this! :)

**Comment by GingkathFox** [comment] 2019-03-21 02:07
no problem! closing now

**Comment by DarkFenX** [comment] 2019-03-21 06:50
Don't close - we're closing issues only when making a release.

**Comment by GingkathFox** [comment] 2019-03-21 13:43
oh, thats a new way to do stuff xD
all the other repos closed a issue when it was fixed

**Comment by DarkFenX** [comment] 2019-03-21 14:38
I believe it's easier for @blitzmann to write up release notes this way.

**Comment by GingkathFox** [comment] 2019-03-21 18:24
Thats fine with me :3 
Kinda wish i knew Python, i need to learn how to use ESI xd

**Closed** 2019-03-24 15:52 UTC
Labels: bug, fixed, logged
