### ISSUE TITLE
windows 10 dark mode UI bug (unredable UI)

### ISSUE THREAD

**Issue by theultimatums** [pyfa-org/Pyfa#2592] opened 2024-02-23 16:14 UTC
![image](https://github.com/pyfa-org/Pyfa/assets/18234860/23f28ba5-0a88-41b5-8c63-915942456c18)

## Bug Report
unredable UI see image

fix? can we get a toggle button to overwrite if we want light/dark mode or get darkmode fully picking up in windows 10?

### Release or development git branch? Please note the release version or commit hash:
[pyfa-v2.58.0-win.exe](https://github.com/pyfa-org/Pyfa/releases/download/v2.58.0/pyfa-v2.58.0-win.exe)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

### Other relevant information:
have dark themes/color set in Windows 10. so it only seems to be picking it up for the background colors... but the rest of the system is well white

can we get a toggle to say what mode we want it to be in / a setting to set the mode?

**Comment by DarkFenX** [comment] 2024-02-24 00:34
Duplicate of #2585

**Closed by DarkFenX** 2024-02-24 00:34 UTC
