### ISSUE TITLE
pyfa 2.0.0 stable doesn't start due to a logbook module not found (even if installed)

### ISSUE THREAD

**Issue by Tetractys** [pyfa-org/Pyfa#1574] opened 2018-05-14 09:24 UTC
## Bug Report

davide@thor ~/Desktop/Pyfa-2.0.0 $ python3.6 ./pyfa.py     --------- **python3.6 compiled from scratch**
Traceback (most recent call last):
  File "./pyfa.py", line 27, in <module>
    import config
  File "/home/davide/Desktop/Pyfa-2.0.0/config.py", line 4, in <module>
    from logbook import CRITICAL, DEBUG, ERROR, FingersCrossedHandler, INFO, Logger, NestedSetup, NullHandler, \
ModuleNotFoundError: No module named 'logbook'   --------- **logbook not found**
davide@thor ~/Desktop/Pyfa-2.0.0 $ pip list
Package            Version               
------------------ ----------------------
appdirs            1.4.3                 
attrs              15.2.0                
BeautifulSoup      3.2.1                 
beautifulsoup4     4.5.1                 
blinker            1.3                   
chardet            2.3.0                 
configglue         1.1.2                 
configobj          5.0.6                 
cryptography       1.2.3                 
cycler             0.9.0                 
debtags            2.0                   
defer              1.0.6                 
dirspec            13.10                 
dnspython          1.12.0                
duplicity          0.7.6                 
ecdsa              0.13                  
enum34             1.1.2                 
EsiPy              0.1.5                 
EVE-Gnosis         2016.11.28.post2      
feedparser         5.1.3                 
futures            3.1.1                 
httplib2           0.9.1                 
idna               2.0                   
ipaddress          1.0.16                
lockfile           0.12.2                
Logbook            0.12.3                --------- **logbook installed (note the capital letter)**
lxml               3.5.0                 
Mako               1.0.3                 
MarkupSafe         0.23                  
matplotlib         1.5.1                 
nbxmpp             0.5.3                 
nemo-emblems       3.6.0                 
netifaces          0.10.4                
numpy              1.11.0                
oauthlib           1.0.3                 
oneconf            0.3.9                 
packaging          16.8                  
PAM                0.4.2                 
paramiko           1.16.0                
pexpect            4.0.1                 
Pillow             3.1.2                 
pip                10.0.0                
piston-mini-client 0.7.5                 
protobuf           2.6.1                 
psutil             3.4.2                 
ptyprocess         0.5                   
pyaml              16.12.2               
pyasn1             0.1.9                 
pyasn1-modules     0.0.7                 
pycrypto           2.6.1                 
pycups             1.9.73                
pycurl             7.43.0                
pygame             1.9.1release          
pyglet             1.1.4                 
pygobject          3.20.0                
pygpgme            0.3                   
pyinotify          0.9.6                 
PyJWT              1.3.0                 
pyOpenSSL          0.15.1                
pyparsing          2.0.3                 
pyparted           3.10.7                
pyserial           3.0.1                 
pysmbc             1.0.15.5              
Pyste              0.9.10                
pyswagger          0.8.29                
python-apt         1.1.0b1+ubuntu0.16.4.1
python-dateutil    2.4.2                 
python-debian      0.1.27                
python-xlib        0.14                  
pyttsx             1.1                   
pytz               2017.2                
pyxdg              0.25                  
PyYAML             3.12                  
reportlab          3.3.0                 
requests           2.9.1                 
screenkey          0.9                   
service-identity   16.0.0                
setproctitle       1.1.8                 
setuptools         35.0.2                
six                1.10.0                
SQLAlchemy         1.0.11                
Twisted            16.0.0                
urllib3            1.13.1                
uTidylib           0.2                   
validate-email     1.3                   
vboxapi            1.0                   
wxPython           3.0.2.0               
wxPython-common    3.0.2.0               
youtube-dl         2018.4.3              
zope.interface     4.1.3                 
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
davide@thor ~/Desktop/Pyfa-2.0.0 $

### Release or development git branch? Please note the release version or commit hash:

Release stable 2.0.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

LinuxMint 18.3 completely updated.

**Comment by blitzmann** [comment] 2018-05-14 22:44
Hi there!

> Logbook 0.12.3 --------- logbook installed (note the capital letter)

I'm pretty sure pyfa requires Logbook >1.0. Not saying that's the issue here, but may as well start with that.

Hrm, I'm also seeing an outdated wxPython version. This looks like an issue with the way the environment is set up rather than a pyfa issue. Please note that 2.0 is a big change, and a lot of the requirements have changed / been updated. wxPython 4.0.0b2 is required, for example. I can assist as needed, but might not be all that useful. I would recommend creating a virtualenv and then piping `requirements.txt` through pip to install what it needs to install. For wxPython, it can be a bitch and a half to get up and running since a lot of distros don't have it available yet (and pyfa requires a beta version, rather than the stable version, due to the latest stable actually having a bug in it that affect pyfa). You will probably have to build wxPython from scratch.

Please see these resources for more information on that. 

https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html
https://wxpython.org/pages/downloads/index.html

If you run a common distro, you may be able to find snapshots for it here:
https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/

Let me know if I can help!

**Comment by Tetractys** [comment] 2018-05-16 07:18
Thank you very much for all these details!
I'll try today and I will notify you all the details.

**Comment by blitzmann** [comment] 2018-05-22 04:06
@Tetractys how goes it?

**Comment by Tetractys** [comment] 2018-05-23 07:02
I have been hospitalized for a few days, unfortunately. I'll try in the next days btw, sorry for the late.
Can you think about an "all included" package like the .exe one? Especially during big versions steps, I think that could be useful. What do you think about?

**Comment by blitzmann** [comment] 2018-05-23 13:46
I'm sorry to hear that, I hope you get better!

You're talking about a pre-compiled Linux build? I've thought about it, and from what I've read it's possible with PyInstaller, the packaging software that I use for Windows and Mac. It's just that it's also a a bit more complex considering it's Linux, and there's many different flavors. I plan to look into it, however time restrictions force me to look at other things at the moment. :/

**Comment by Tetractys** [comment] 2018-05-23 16:08
Tha 2.x.x version of pyfa is a big leap.This actually needs is python 3.6 (and relatives libs) minimum. This version is probably installed by default on some distros released in 2018 but i think the 80% of the Linux installations is still at the 2.7.12 or merely in early 3.x version. 
So, even if not strictly compiled, as you mentioned, but a folder with a normal source  would be perfect, with all the requested python version and relatives libs inside. A .sh script would be handy to launch pyfa 2.x.x finding all the necessary resources in the folder itself.
I know you are busy take you time of course! Hoping to have suggested something eventually possible. :)

**Comment by blitzmann** [comment] 2018-05-24 02:10
> So, even if not strictly compiled, as you mentioned, but a folder with a normal source would be perfect, with all the requested python version and relatives libs inside. 

That's basically what PyInstaller would do - take the python interpreter of the build system, along with it's packages, and pyfa's source code, and mashes it into a configuration that is able to be run independent of distro or user's environment. That's the idea anyway.

That being said, there are ways to handle older distros that don't have python 3 by default. You can simply download it via the package manager of choice, or build it from scratch, and have it live alongside python 2 - this usually isn't a problem, as even old, stable distros tend to have 3.6 (released 3 years ago). Afterwards, if you want to download python packages specifically for pyfa, without it modifying system-wide python packages, there's [`virtualenv`](http://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv). That allows you to create an isolated python environment for pyfa only,

Hope this information helps! I will experiment with linux builds as time permits, but let me know if I can be of further help with getting you up and running. You said you already have python 3.6 installed. the only other two big things would be to install the pip packages noted in `requirements.txt`, and wxPython 4.0.0b2. Since you use Mint, you may be able to use the Ubuntu builds here: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/. However, be prepared to have to actually build wxPython from scratch. Make sure it's 4.0.0b2 as well - there's breaking bugs with the latest stable versions.

**Comment by blitzmann** [comment] 2018-06-06 04:30
@Tetractys hope you're still doing well! I'm going to close this as it's not a pyfa issue, but rather related to your environment. I do hope you've been able to get it up and running. If you're still having difficulties / need additional information, we can still discuss here :)

👍

**Closed** 2018-06-06 04:30 UTC
Labels: invalid, linux

**Comment by Tetractys** [comment] 2018-07-01 10:00
@blitzmann 
Hi Ryan :)
I dist-upgraded my Lmint 18.3 to Lmint 19 (==ubuntu 18.04)
I solved the logbook problem and seems many others but the forced wxPython version that "have" to be v4.0.0b2+.
Take a look please:

`dave@penguin:~/Desktop/Pyfa-2.2.0b1$ pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython --user
Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04
Collecting wxPython
  Downloading https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.3-cp27-cp27mu-linux_x86_64.whl (119.1MB)
    100% |████████████████████████████████| 119.1MB 405kB/s 
Requirement not upgraded as not directly required: six in /usr/lib/python2.7/dist-packages (from wxPython) (1.11.0)
Requirement not upgraded as not directly required: PyPubSub in /home/dave/.local/lib/python2.7/site-packages (from wxPython) (4.0.0)
Requirement not upgraded as not directly required: typing in /home/dave/.local/lib/python2.7/site-packages (from PyPubSub->wxPython) (3.6.4)
Installing collected packages: wxPython
Successfully installed wxPython-4.0.3
dave@penguin:~/Desktop/Pyfa-2.2.0b1$ python3.6 ./pyfa.py 
pyfa requires wxPython v4.0.0b2+. You can download wxPython from https://wxpython.org/pages/downloads/
dave@penguin:~/Desktop/Pyfa-2.2.0b1$`

seems no other wxPython is allowed by your code.... is it possible?
Have you any ideas, please?

**Comment by minlexx** [comment] 2018-07-01 10:14
> /home/dave/.local/lib/python2.7/

seems you use python2 instead of python3. Do not start `pip`, instead start `pip3` or better directly `/usr/bin/python3.6 -m pip`

**Comment by blitzmann** [comment] 2018-07-15 04:45
Glad you got it up and running @Tetractys!


> how to set bigger fonts in the interface?? (true 4K on a 28" monitor here)

pyfa uses, for most of it's interface, the system settings. of course, when it comes to linux, this could mean anything and I'm not entirely sure which settings control which widgets. There are a few hard-coded font sizes IIRC.

Font's in wxpython are weird and I've been wanting to go through and refactor how pyfa utilize them so that we can set our own font sizes. Just haven't had time or motivation to do this. 

> can you think a script to install pyfa for those that don't have too much experience on Linux? This would be greatly appreciated! (yes, many new Linux lovers has little or no experience about python, differences between 2.7 and 3.x versions, pip and pip3.... etc)!

There isn't a script that I can maintain that will cover all use cases. When it comes to linux, it's very much a "do you own research" type of situation, since there are so many distros and configurations out there. There have been folks that maintain pyfa for their specific linux distro (for example, this Arch package: https://aur.archlinux.org/packages/pyfa/), the problem is that 2.x, with it dependency upgrades, means that a lot of the older packages have to be reworked. I've been wanting to get a wiki page up for linux as well for just general hints and tips, but also haven't gotten around to it >_<

**Comment by minlexx** [comment] 2018-07-15 21:31
> how to set bigger fonts in the interface?? 
@Tetractys wxPython is based on wxGTK, which uses gtk for low-level UI rendering. Try something from this article https://wiki.archlinux.org/index.php/HiDPI under **"GNOME"** or **GDK 3 (GTK+ 3)** section
