### ISSUE TITLE
2.20.1: searching on market for "damage" crashes pyfa

### ISSUE THREAD

**Issue by Bazzek** [pyfa-org/Pyfa#2167] opened 2020-04-15 18:31 UTC
## Bug Report
searching on market for "damage" crashes pyfa

### Expected behavior:
finding items with the text damage in the name

### Actual behavior:
Program stops responding

Browsing to the damage control II works fine

### Detailed steps to reproduce:
Make fit (i did a cynabal) and search for "damage" on the market.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Cynabal, Cynabal Bjorn]

Tracking Enhancer II
Gyrostabilizer II
Gyrostabilizer II
Gyrostabilizer II
Damage Control II

50MN Microwarpdrive II
Large F-S9 Regolith Compact Shield Extender
Large F-S9 Regolith Compact Shield Extender
Large F-S9 Regolith Compact Shield Extender
Warp Disruptor II

425mm AutoCannon II, Republic Fleet Phased Plasma M
425mm AutoCannon II, Republic Fleet Phased Plasma M
[Empty High slot]
425mm AutoCannon II, Republic Fleet Phased Plasma M
425mm AutoCannon II, Republic Fleet Phased Plasma M

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Release 2.20.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment] 2020-04-15 19:52
Is it just this keyword or others also do? Try entering `rr`, for example.

How does it crash? Just silently closes?

**Comment by Bazzek** [comment] 2020-04-16 05:26
I have not found other keywords that trigger it.

And the app just stops responding

**Comment by DarkFenX** [comment] 2020-04-16 08:51
I think I've seen similar issue but i thought I mitigated it. Will revert my mitigation change to reproduce it on my machine and look into root of the issue.

**Comment by DarkFenX** [comment] 2020-04-16 08:54
Please share specs of your PC. I think it might be something related to regex search performance.

**Comment by DarkFenX** [comment] 2020-04-16 09:06
FYI i reproduced it by setting market input search delay to 0 (by default it's 250 ms). As a temporary workaround, try increasing it to higher values.

**Comment by DarkFenX** [comment] 2020-04-16 11:31
So, this bug is revealed by regex-enabled searches, since they take time. Actually it seems to be a race condition which existed for a while. I will show an example with 0 search delay and "capital" as a search entry.

I have pretty powerful PC but nevertheless it seems to fail to get search results ready and updated for "capi" before "capit" is requested.

1. Main thread calls `Market.searchItems()` with `capi` request
2. Main thread calls `Market.scheduleSearch()` with `capi` request
3. Main thread successfully executes `Market.scheduleSearch()` and its child calls for `capi` request
4. Search thread gets the request and starts to unwrap it (`request, callback, filterName = self.searchRequest` part in `SearchWorkerThread.processSearches()`) for `capi` request
5. Main thread leaves `Market.searchItems()`, successfully completing it for `capi` request (note that it just scheduled search rather than actually performed it, that's why it is finished)
6. Search thread submits query to database to actually find some items for `capi` request
7. Meanwhile, user has added another letter to the request. So, main thread calls `Market.searchItems()` with `capit` request
8. Main thread calls `Market.scheduleSearch()` with `capit` request
9. Search thread completes the search and executes callback via `wx.CallAfter` for `capi` request. It is put into internal wx queue to be executed later by main callback.
10. Immediately after completing `capi` request (callback is last part of it), search thread takes on `capit` request and prepares search (parses request, jargonizes it etc)
11. Main thread starts executing callback with `capi` search results. Calls go through `ItemView.populateSearch()`, `ItemView.filterItemStore()`
12. At this point, search thread requests database to start actual search for `capit` request
13. Main thread gets to `Display.update()` as part of callback for `capi` requests and stops here

So far, it is obvious that there is some conflict for resources, and I have to find what exactly happens to properly fix or mitigate it.

**Comment by DarkFenX** [comment] 2020-04-16 11:46
No idea how those intersect, but pyfa crashes while sqlalchemy handles search in the search thread and wx is handling callback with results from previous search. My guess would be that during that callback, wx uses data on returned objects, which is handled by sqlalchemy. SQLAlchemy is not built to be accessed from different threads simultaneously, which might be the reason of the crash.

**Comment by DarkFenX** [comment] 2020-04-16 11:55
Passing objects from worker thread to main thread is no good. I will pass item IDs instead.

**Comment by DarkFenX** [comment] 2020-04-16 12:14
Fixed by using scoped SQLAlchemy sessions and passing search results as list of item IDs in 32db3e31791048112f0c502dd069d56bf6860326 and 1a897c04192c64bed0d82deb0a8126e62ddac1e9.

**Closed by DarkFenX** 2020-04-16 12:14 UTC
Labels: bug
