### ISSUE TITLE
Error window on fit delete

### ISSUE THREAD

**Issue by peldar** [pyfa-org/Pyfa#1147] opened 2017-05-10 08:29 UTC
Got pyfa error popup window with following text after deleting a fit.

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.0 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\olaf_\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'projectedFits'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\sfBrowserItem.py", line 318, in OnLeftUp
    self.Refresh()
  File "C:\Program Files (x86)\pyfa\library.zip\gui\shipBrowser.py", line 2006, in Refresh
    fit = sFit.getFit(activeFit)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 253, in getFit
    for fitP in fit.projectedFits:

**Comment by ECHRE-Zetakya** [comment] 2017-05-10 11:16
Likewise. Specifically, I got this on deleting a fit while having the fit open in a tab:

OS version: 	Windows-7-6.1.7601-SP1
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.0 Stable - YC119.5 1.0
pyfa root: D:\CCP\Pyfa
save path: C:\Users\Alisdair\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'projectedFits'

  File "D:\CCP\Pyfa\library.zip\gui\sfBrowserItem.py", line 318, in OnLeftUp
    self.Refresh()
  File "D:\CCP\Pyfa\library.zip\gui\shipBrowser.py", line 2006, in Refresh
    fit = sFit.getFit(activeFit)
  File "D:\CCP\Pyfa\library.zip\service\fit.py", line 253, in getFit
    for fitP in fit.projectedFits:

**Comment by ECHRE-Zetakya** [comment] 2017-05-10 11:49
A bit of further testing: The issue only occurs if you delete the fit that's in the currently active tab (the one displayed in the main part of the window). Once triggered, the error window reappears whenever any change is made to what fitting would be displayed in a tab. This includes changing fit, closing a tab, opening a tab. The issue goes away if you close and reopen pyfa. Appears to happen with all fits (at least, all of those I've tested reproduced the issue in the same way).

Workaround: Don't delete fits that are displayed in an active tab.

Steps to reproduce: Open a fit. Delete that fit while the fit is open in the active tab

**Comment by Seismix** [comment] 2017-05-10 17:03
Got the exact same message when deleting an active fit:

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.0 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\Oliver\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'projectedFits'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\sfBrowserItem.py", line 318, in OnLeftUp
    self.Refresh()
  File "C:\Program Files (x86)\pyfa\library.zip\gui\shipBrowser.py", line 2006, in Refresh
    fit = sFit.getFit(activeFit)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 253, in getFit
    for fitP in fit.projectedFits:

**Comment by blitzmann** [comment] 2017-05-10 22:40
Hey guyes, thanks for the bug reports. The issue has been identified and a fix is pending inclusion :)

**Comment by blitzmann** [comment] 2017-05-10 22:53
An automated build with this fix can be found here:

https://ci.appveyor.com/project/blitzmann/pyfa/build/artifacts :)

**Comment by blitzmann** [comment] 2017-05-12 03:24
v1.29.1 is out which should have a fix in place for this issue. Let me know of any other issues or problems.

**Closed by blitzmann** 2017-05-12 03:24 UTC
Labels: bug, fixed

**Comment by Rarilmar** [comment] 2017-05-12 13:41
Well, I have the error on 1.29.1
![319ca5e2-372f-11e7-84f2-8a40bd2c347a](https://cloud.githubusercontent.com/assets/6603349/26000480/ca0749c0-3731-11e7-9138-40bd7ddfbdba.jpg)

**Comment by blitzmann** [comment] 2017-05-12 19:39
@rarilmar seems to be a separate issue, at least the error isn't 100% the same. Did you get this when deleting the fit as well? I'll take a look tonight =)

**Comment by blitzmann** [comment] 2017-05-13 00:36
@Rarilmar can you send me a zip archive of your `%userprofile%/.pyfa` directory to sable.blitzmann@gmail.com? It contains user data that will hopefully help to figure out why that error happened.

**Comment by Ebag333** [comment] 2017-05-13 08:37
These are also stacktraces that I fixed ages ago.....

**Comment by blitzmann** [comment] 2017-05-14 01:02
@Ebag333 Would you mind linking to them then? Do you have reproduction steps? I looked through your PRs when you said you had a few fixes, but didn't come across these things, or maybe I missed them.

As for @Rarilmar's error, the fix itself is simple - just check if it's `None` first (and indeed, this is what I have done), but I'm unsure of why it would ever happen in the first place. If there is something in the projected view, then it stands to reason that `stuff.getProjectedInfo(activeFit)` wouldn't be `None`. I can't imagine what causes it to return None. @_@

**Comment by Ebag333** [comment] 2017-05-14 01:59
There are dozens of these scattered all over.  There's a couple PRs where I fixed good numbers of them, but a lot of them got fixed in situ as I was working on the module in question.

The good news is that there's only 305 commits to search through. :)

Essentially, though, each instance of being lazy and using `variable = self.something` needs to be trapped and handled. Either a try/catch or a `if` check

I'm not going to go through every PR (you can do that, there's only 79 of them :) ), but here's a few that about 30 seconds of clicking through them turned up.

https://github.com/Pyfa-fit/Pyfa-fit/pull/11
https://github.com/Pyfa-fit/Pyfa-fit/pull/44
https://github.com/Pyfa-fit/Pyfa-fit/pull/46
https://github.com/Pyfa-fit/Pyfa-fit/pull/54

There's more, I only searched through a few pages of PRs......

**Comment by blitzmann** [comment] 2017-05-14 02:55
@Ebag333 Thanks for the links, I'll take a look through them. But I was specifically asking about the errors noted in this issue since you state that you've known about them and fixed them. :/

**Comment by Ebag333** [comment] 2017-05-14 03:41
Well, I'm sure if you'd asked a month ago I'd probably remember.  But that was a month, hundreds of commits, multiple projects ago. :)

> I can't imagine what causes it to return None. @_@

Mostly just the fit object literally being None, because it doesn't exist (projected/command) or it it an empty tab, or it's being created/destroyed (mostly destroyed).

**Comment by blitzmann** [comment] 2017-05-14 06:16
> Mostly just the fit object literally being None, because it doesn't exist (projected/command) or it it an empty tab, or it's being created/destroyed (mostly destroyed).

Neither the active fit or the projected fit isn't None though. The fact that this started in projected view means that there is at least an active fit (and not just an empty view). The projected view shows everything in `fit.projectedFits` (along with mods and stuff), and the fact that there is something there means there is a Fit object in this collection. The projected fit that is displayed has a dictionary of all the things that it's projected onto. If it's being displayed, then that projected fit will have a pointer back to the other fit (active in this case), which is what `getProjectionInfo()` does. This isn't a case of a fitting object being `None` (otherwise, projectedView wouldn't get that far, and if `stuff` was None and there would be an error on `getProjectedFits()`, not accessing the `active` attribute). Instead it seems to be a case of the victim fit not being in the projected fits projectedOnto dictionary. Now why that is, I have no idea. Very hard to pinpoint since I can't personally reproduce the issue, and probably due to some hokey deletion.

Anyway, I've made a commit that should avoid the issue even if it doesn't solve it.
