### ISSUE TITLE
[ascension preview] propulsion mode's some bonuses on T3D ignored

### ISSUE THREAD

**Issue by msoltyspl** [pyfa-org/Pyfa#850] opened 2016-11-26 16:45 UTC
Been testing some oversized MWD fits recently - both svipul and confessor under preview version ignores speed boost given by re"balanced" role bonuses.

See: https://aww.moe/xbc9c5.jpg

**Comment by blitzmann** [comment] 2016-11-27 05:27
Duplicate of #835.

**Closed by blitzmann** 2016-11-27 05:27 UTC
Labels: duplicate
