### ISSUE TITLE
Backup All Fittings works but gives error message

### ISSUE THREAD

**Issue by Kawless** [pyfa-org/Pyfa#2576] opened 2024-01-19 07:09 UTC
## Bug Report
error message when backing up all fittings

### Expected behavior:
Backup All Fittings

### Actual behavior:
Backs up All Fittings, but gives error message

### Detailed steps to reproduce:
1. create a fit
2. backup all fittings

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Caracal, Baconer's Caracal]

Ballistic Control System I
Ballistic Control System I
Ballistic Control System I
Mark I Compact Reactor Control Unit

Large F-S9 Regolith Compact Shield Extender
Large F-S9 Regolith Compact Shield Extender
10MN Monopropellant Enduring Afterburner
Enduring Multispectrum Shield Hardener
Coadjunct Scoped Remote Sensor Booster

Heavy Missile Launcher I
Heavy Missile Launcher I
Heavy Missile Launcher I
Heavy Missile Launcher I
Heavy Missile Launcher I

Medium EM Shield Reinforcer I
Medium Core Defense Field Extender I
Medium Core Defense Field Extender I

Hornet I x2

Scourge Heavy Missile x918
ECCM Script x1

### Release or development git branch? Please note the release version or commit hash:
Version v2.57.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Error Message:

pyfa v2.57.3
EVE Data Version: 2443636 (2023-12-05 03:37:07)

OS version: Windows-10-10.0.19044-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 884, in backupToXml
wx._core.wxAssertionError: C++ assertion ""IsRunning()"" failed at ..\..\src\common\evtloopcmn.cpp(92) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop

**Comment by Madman045** [comment] 2024-02-05 20:20
pyfa v2.57.3
EVE Data Version: 2443636 (2023-12-05 11:37:07)

OS version: Windows-10-10.0.22000-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 884, in backupToXml
wx._core.wxAssertionError: C++ assertion ""IsRunning()"" failed at ..\..\src\common\evtloopcmn.cpp(92) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop

Same error reported as above, I am running Windows 11

it created a file so i take it that worked? i'll soon find out after an OS reinstall

**Comment by DarkFenX** [comment] 2024-02-20 16:11
Duplicate of #2566

**Closed by DarkFenX** 2024-02-20 16:11 UTC
