### ISSUE TITLE
Character Editor will not open (MAC)

### ISSUE THREAD

**Issue by worstcaseffm** [pyfa-org/Pyfa#965] opened 2017-02-01 17:17 UTC
Attempting to open the Character Editor in the Mac-version is unsuccessful when using using Ctrl-E, clicking on the menu item manually or choosing that option from drop-down list.
No error shows up in the log.txt. Other dialogs can be opened (f.e. damage profile editor).

**Comment by Ebag333** [comment] 2017-02-01 17:18
@worstcaseffm please grab the pre-release listed here:
https://github.com/pyfa-org/Pyfa/releases

There's a number of fixes in there to deal with database corruption.  If you have the same issue using the pre-release, let me know here.

**Comment by blitzmann** [comment] 2017-02-01 18:08
What os x version? Is it the prerelease or stable version?  And is it the normal or deprecated Mac build

**Comment by worstcaseffm** [comment] 2017-02-01 18:33
I used pyfa-20170130-6049c9-mac.zip and my MAC is running OSX Sierra 10.12.2
No reaction when I try to open the editor. No error, no window.
Will now try the deprecated version as soon the download finished.

**Comment by Ebag333** [comment] 2017-02-01 18:35
Can you send me your savedata.db file?  ebagola@gmail.com
Also any log files in the same location.

https://github.com/pyfa-org/Pyfa/wiki/Database

**Comment by worstcaseffm** [comment] 2017-02-01 18:41
I just sent the savedata.db. The log.txt file is completly empty (size 0). I also tried the deprecated Mac version and had the same issue. The character editor will not be opened while all other dialogs opens without any trouble.
Thank you for your help.

**Comment by worstcaseffm** [comment] 2017-02-01 18:50
I now tried the pyfa-1.26.0-yc118.10-1.2-mac.zip version. With that it is possible to open the character editor. Seems, only the pre-release version is affected.

**Comment by Ebag333** [comment] 2017-02-01 18:54
So as far as I can tell this is essentially an empty database, except for a Coercer fit with no modules attached to it.

Does this happen if you delete or rename the current saveddata.db and open it with a completely empty database?

**Comment by worstcaseffm** [comment] 2017-02-01 18:56
always happened so. I tried to open the character editor first after deleting all in that folder and also after fully fitted a destroyer.

**Comment by blitzmann** [comment] 2017-02-01 20:07
@Ebag333 this does not sound like a database issue. We've never run into corruption issues with just opening the character editor. This sounds like a bad import or something similar.

@worstcaseffm can you directly run pyfa through the terminal? just go `pyfa.app/Contents/MacOS/pyfa` and tell me if that outputs anything useful

**Comment by mavericklan** [comment] 2017-02-02 11:11
same on windows, should i post another issue?

**Comment by Rarilmar** [comment] 2017-02-04 15:32
I also have same issue on windows with the latest public release.

**Comment by Ebag333** [comment] 2017-02-04 15:59
@mavericklan @rarilmar

Are you starting with an empty database? If you aren't, can you please send me your database and log.txt file? Also try starting from a empty database and see if that works (rename your current saveddata.db).

**Comment by Rarilmar** [comment] 2017-02-05 01:12
@Ebag333 nothing works, tried with new install and deleted settings folder, still chr edit won't open with this version. 
[.pyfa.zip](https://github.com/pyfa-org/Pyfa/files/752680/default.pyfa.zip)

**Comment by Rarilmar** [comment] 2017-02-05 01:28
I just reverted to the previous stable release and it works so it must be some bug in the new version code

**Comment by Ebag333** [comment] 2017-02-05 01:32
Give this build a shot, see if it works and anything is generated in a `Pyfa.log`.

If it doesn't work, try running the Pyfa executable with a `--debug` flag, and there should be a `Pyfa_debug.log` file.

https://drive.google.com/file/d/0B59pJ0pO7UMeMmd2ZXZHNjNrczQ/view?usp=sharing

This is a very alpha build, and the link will be removed, so let me know when you grab it.

**Comment by blitzmann** [comment] 2017-02-05 01:38
Ebag what does that build contain? I would like to not troubleshoot with a build that is vastly different than the target. Just more logging?

**Comment by blitzmann** [comment] 2017-02-05 01:39
@rarilmar would you be able go to hop onto slack tonight? Its easier to troubleshoot and provide next steps in a chat interface :)

**Comment by Rarilmar** [comment] 2017-02-05 01:44
@Ebag333 Just grabbed it and it works!

**Comment by Ebag333** [comment] 2017-02-05 01:54
>Ebag what does that build contain? I would like to not troubleshoot with a build that is vastly different than the target. Just more logging?

it's the build branch, which is basically just the logging branch with the build stuff enabled.

Without logs it's impossible to say the cause, since we don't usually write stack traces when frozen anything there is gone.

Basically, it's branched right before this commit:
https://github.com/Ebag333/Pyfa/commit/5d46fe7e4d06355886f50623a3a5480dade70742

Honestly I was hoping it'd break and we'd get a stacktrace since we can redirect `stderr` using pyinstaller. :(

@Rarilmar I would suggest rolling back to the previous version for now.  Feature wise there's nothing really special in the new build, it's just a ton of low level base code improvements.

**Comment by Rarilmar** [comment] 2017-02-05 02:12
Forced debug mode on the problem version but it just creates info messages nothing related to trying to open character sheet. Tried opeing it from different menus and CTRL + E. Updating skill points on chr from api or various shortcuts from ship works and nothing generates an error. 
Btw Pyfa_debug.log doesn't appear but the normal log gets populated under debug mode.
[log.txt](https://github.com/pyfa-org/Pyfa/files/752703/log.txt)

**Comment by Ebag333** [comment] 2017-02-05 03:57
>Btw Pyfa_debug.log doesn't appear but the normal log gets populated under debug mode.

You'll only get a `Pyfa.log` or `Pyfa_debug.log` if you're running the build I gave you.  It uses a different logging engine that lets us output more data (like redirecting stacktraces to the log).

Any other build uses `log.txt`.


>Forced debug mode on the problem version but it just creates info messages nothing related to trying to open character sheet.

If this is happening on both Mac and Windows it's not an environment issue.  The question becomes if it's a code issue (certainly possible with as many low level changes as we made) or something in the build itself (bug in a particular module version in the skeleton, or the skeleton itself just needing to be rebuilt).

**Comment by blitzmann** [comment] 2017-02-05 06:39
Just as a note, I can reproduce the character editor issue.

The cause is that I'm a dumbass. I did not include an updated EVE database with that build, which would have included the alpha clone data. So it tries to load data which it can't find.

This should be fixed with the next stable release. I'm almost positive this is what is happening on OS X as well (haven't confirmed though)

**Comment by Ebag333** [comment] 2017-02-05 07:02
That would make sense. The test build I have is straight from dev, which does have the updated EVE.db.

We'll have to start adding a check for that.

**Comment by Rarilmar** [comment] 2017-02-05 15:02
Yep that was it, copied the eve.db from @Ebag333 test version to the problem version and chr editor opened.

**Comment by Ebag333** [comment] 2017-02-05 16:33
Thanks for confirming! 👍

**Closed** 2017-02-17 04:44 UTC
Labels: bug, fixed
