### ISSUE TITLE
Structure skills are not trained for "All 5" character

### ISSUE THREAD

**Issue by jacobmatthewjansen** [pyfa-org/Pyfa#947] opened 2017-01-15 08:56 UTC
Structure skills (example: Structure Electronic Systems) are not trained to 5 on the 'All 5' character

**Comment by Ebag333** [comment] 2017-01-17 19:29
Looking at a fresh DB it is.  Most likely your DB is corrupt.

Can you give a screenshot of the character editor, or shoot me a copy of your DB?  (Share it somewhere and post the link here, or email the DB/link to me: ebagola@gmail.com )

**Comment by blitzmann** [comment] 2017-01-18 00:46
Same, I am not seeing this issue. 

Your database file is located at `%userprofile%/.pyfa/saveddata.db`, please send me a copy at sable.blitzmann@gmail.com

**Comment by jacobmatthewjansen** [comment] 2017-01-20 22:47
I emailed you my savedata.db as requested

**Comment by blitzmann** [comment] 2017-01-25 15:13
@jacobmatthewjansen I'm also showing level 5 for structure skills. Not sure what's going on??

![image](https://cloud.githubusercontent.com/assets/3904767/22295894/7b133ad0-e2e6-11e6-918e-5fa606dedd7b.png)

Can you double check and send me a screenshot (same thing I did)?

**Comment by blitzmann** [comment] 2017-02-12 02:47
@jacobmatthewjansen any news?

**Comment by blitzmann** [comment] 2017-02-14 04:03
@jacobmatthewjansen gonna close this issue as I can't reproduce. please feel free to reopen it if you are still experiencing this problem. :)

**Closed by blitzmann** 2017-02-14 04:03 UTC
