### ISSUE TITLE
Shield Regeneration Graph out of view

### ISSUE THREAD

**Issue by ArtUrban** [pyfa-org/Pyfa#2467] opened 2022-09-16 06:34 UTC
## Bug Report
The Graph for Shield Regeneration is always 0.0 to 1.0 on X and Y axis when simulating. the data points are outside the view.

### Expected behavior:
the x and y axis should get adjusted to fit the data points

### Actual behavior:
x and y axis are locked from 0.0 to 1.0

### Detailed steps to reproduce:
try generating a shield graph

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any fit

### Release or development git branch? Please note the release version or commit hash:
v2.45.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
Tried reinstalling, no change. i remember traying to generate the graph in the past and it behaved in the same way. Did not thing about generating a ticket.

**Comment by DarkFenX** [comment] 2022-09-30 13:37
Caused by adding drone EHP/shield regen columns (had to change various interfaces to support that). Fixed in 78af68cac2a5daed22a57eec57d66b6abeac66cc.

**Closed** 2022-09-30 13:37 UTC
