### ISSUE TITLE
Unable to export fits when first adding a esi character.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1541] opened 2018-05-07 08:13 UTC
## Bug Report
Unable to export fits when first adding a esi character.

### Expected behavior:
fit gets exported to eve.

### Actual behavior:
No fit is exported to eve.

### Detailed steps to reproduce:
1. Go into character editor>EVE SSO tab
2. click log in with eve sso and login a character
3. exit character editor
4. select and export a fit via eve sso
5. check client and note fit is not exported, also no status msg about communicating with the server.

*this error only happened on my first attempt with esi, unable to reproduce.
### Release or development git branch? Please note the release version or commit hash:
v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by blitzmann** [comment] 2018-05-07 16:44
Thanks, I wonder if there's an issue with assigning the esi client object to the character when first creating. Not able to test right now, but will test when I get home!

**Comment by blitzmann** [comment] 2018-05-08 02:08
Hrm, I also cannot reproduce. I recently added an exception whenever an ESI call fails, so hopefully if this pops up again it would give us a bit more information as to what happened?

**Comment by PatMcCarthy** [comment] 2018-05-09 20:08
Happened to me... Got the following
OS version: Windows-10-10.0.14393-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 248, in exportFitting
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 170, in postFitting
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 184, in check_response
service.esi.EsiException: 500

**Comment by PatMcCarthy** [comment] 2018-05-09 20:08
Since I do not have a user Holme, I think I can guess what happened.....

**Comment by blitzmann** [comment] 2018-05-10 00:58
> Since I do not have a user Holme, I think I can guess what happened.....

Nah, that's not why. This is a funky side effect of using a program to freeze the python code. That's actually my environment, where I keep the pyfa source code. Doesn't have anything to do with the error :)

`service.esi.EsiException: 500`

This is an error from the server (so on CCP's side), so your error might be due to a hiccup from EVE. Could ou post that fit that you were trying to export?

**Comment by blitzmann** [comment] 2018-05-15 02:31
I've reworked the esi functionality. not sure if it solves this issue particularly, but going to close this issue in the hopes of it does. If it pops up again, we can address it. :) 

Thanks all

**Closed by blitzmann** 2018-05-15 02:31 UTC
Labels: 2.x, esi
