### ISSUE TITLE
Alpha Clone from new character results in no-skill alpha

### ISSUE THREAD

**Issue by MrOnak** [pyfa-org/Pyfa#1219] opened 2017-06-07 04:42 UTC
When I create a new character through the "New Character" button on the right and then apply an alpha clone preset, the new character will remain with zero skills. There is no warning either so this might be confusing to some. 
Using the all-V clone as base for a copy and then applying an alpha preset of course does work as expected.

**Comment by blitzmann** [comment] 2017-06-07 05:29
The alpha clones are not meant to overwrite a character. They are meant to cap the characters skill levels to the respective alpha's max. This allows folks to be able to keep their character consistent (and still allow things like API updating) but have it in the Alpha state. It also allows them to return a character to Omega easily.

If you want a character with the alpha skill set, copy the All 5 character and set it as an alpha (as you've discovered). The current functionality will remain as-is, considering that the core functionality of alpha clones being a level cap rather than a skill replacement (in EVE and in pyfa). I'll look into the possibility of adding a way to overwrite the character to alpha state for those that may want that (maybe a simple "Reset Skills to Alpha" button or something). :)

**Comment by MrOnak** [comment] 2017-06-07 18:57
Agreed, it probably works as intented but the possibility to use as described above is confusing and there is no clue or feedback that the result is not what some might expect. Maybe a simple context help is all that's needed.

**Comment by blitzmann** [comment] 2017-06-09 02:02
> Maybe a simple context help is all that's needed.

This is an excellent idea for the interim. Thanks!

![image](https://user-images.githubusercontent.com/3904767/26957958-1aa4465c-4c96-11e7-920b-e18b6ea59c9f.png)

**Comment by blitzmann** [comment] 2018-05-28 23:13
Closing issue as it's working as intended, and a new context tooltip is provided that hopefully provides a clearer indication on what is happening. 😄

**Closed by blitzmann** 2018-05-28 23:13 UTC
