### ISSUE TITLE
SSO add character problem

### ISSUE THREAD

**Issue by Extrimalua** [pyfa-org/Pyfa#1990] opened 2019-05-27 12:20 UTC
## Bug Report
When i try add character and login i take this - {"error":"invalid_request","error_description":"Some parameters are either missing or invalid"}

### Release or development git branch? Please note the release version or commit hash:
Version v2.9.4dev3
Eve data Version: 1503340 (2019-05-09 16:14:26)
### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment] 2019-05-27 12:46
Open `<user folder>\.pyfa`, clean up all *.log files, launch pyfa, reproduce issue again and attach here logs. Thanks.

**Comment by Extrimalua** [comment] 2019-05-27 13:15
if i try add character no log forming, but if refresh api exist character 
[pyfa-2019-05-27.log](https://github.com/pyfa-org/Pyfa/files/3223874/pyfa-2019-05-27.log)

**Comment by DarkFenX** [comment] 2019-05-28 12:13
Unfortunately logs turned out to be not so useful (not enough logging in app when it comes to ESI interaction). Could you post full error message, or screenshot of it?

**Comment by DarkFenX** [comment] 2019-05-28 12:20
Nvm, found this part:
```
[2019-05-27 13:12:17.795407] WARNING: gui.characterSelection: Error fetching skill information for character
[2019-05-27 13:12:17.795909] WARNING: gui.characterSelection: Expecting value: line 1 column 1 (char 0)
```
There're parts of code which could generate this error, i will add extra logging for next release.

**Comment by DarkFenX** [comment] 2019-05-28 14:11
Launch 2.9.4 with extra --debug argument (add it to the shortcut, e.g. `"C:\Path\To\Pyfa\pyfa.exe" --debug`), reproduce issue again, get debug log from `.pyfa` folder and attach here. Should provide some extra info which is necessary to look into this issue.

**Comment by Extrimalua** [comment] 2019-05-28 15:45
[pyfa_debug-2019-05-28.log](https://github.com/pyfa-org/Pyfa/files/3228543/pyfa_debug-2019-05-28.log)

**Comment by Extrimalua** [comment] 2019-05-28 15:49
[pyfa_debug-2019-05-28.log](https://github.com/pyfa-org/Pyfa/files/3228558/pyfa_debug-2019-05-28.log)

**Comment by Extrimalua** [comment] 2019-05-28 15:56
[pyfa_debug-2019-05-28.log](https://github.com/pyfa-org/Pyfa/files/3228590/pyfa_debug-2019-05-28.log)
![777](https://user-images.githubusercontent.com/51083698/58492775-48ddcf00-817a-11e9-91fa-20a02e3ba344.PNG)

**Comment by DarkFenX** [comment] 2019-05-28 18:21
Please send me that link you have in your browser to phoenix@mail.ru (to not expose it to anyone besides me). I will check what ESI doesn't like.

**Comment by Extrimalua** [comment] 2019-05-28 18:39
done

**Comment by DarkFenX** [comment] 2019-05-28 18:47
Thanks, i will take a look tomorrow.

**Comment by DarkFenX** [comment] 2019-05-29 09:54
@Extrimalua what are your settings in `Preferences -> EVE SSO`? It works for me with `pyfa.io` SSO mode and `Local Server` authentication method.

**Comment by Extrimalua** [comment] 2019-05-29 11:08
Yes it was castom , and i added character thx, half year ago i tryed found problem and forget about swiching to custom mode.  But the main problem wasn`t solve. And i just now found  solution =) I relogin all characters, and now it works. 
![не успешно](https://user-images.githubusercontent.com/51083698/58552393-f6a0ba80-821a-11e9-9c15-180cf93a98df.PNG)
![заново](https://user-images.githubusercontent.com/51083698/58552442-159f4c80-821b-11e9-9ba0-51e37f71e9f6.PNG)
![удачно2](https://user-images.githubusercontent.com/51083698/58552470-26e85900-821b-11e9-849a-2cb8671373a2.PNG)

**Comment by DarkFenX** [comment] 2019-05-29 11:18
Cool, closing issue

**Closed by DarkFenX** 2019-05-29 11:18 UTC
Labels: bug
