### ISSUE TITLE
Saving skill overrides on Character Editor

### ISSUE THREAD

**Issue by petsagouris** [pyfa-org/Pyfa#1281] opened 2017-09-14 16:21 UTC
## Bug Report
Change the Rigging skill on an Alpha Amarr character. Click Save on the Character Editor. Error splat.

### Expected behavior:
To save the skill override.

### Actual behavior:
Got message:

`OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\George\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'dirtySkills'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\characterEditor.py", line 224, in saveChar
    sChr.saveCharacter(char.ID)
  File "C:\Program Files (x86)\pyfa\library.zip\service\character.py", line 244, in saveCharacter
    char.saveLevels()
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 226, in saveLevels
    skill.saveLevel()
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 320, in saveLevel
    if self in self.character.dirtySkills:
`

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Coercer, meta]

Extruded Compact Heat Sink
Extruded Compact Heat Sink
Extruded Compact Heat Sink

1MN Y-S8 Compact Afterburner
Alumel-Wired Enduring Sensor Booster, Scan Resolution Script

Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Focused Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
[Empty High slot]

Small Energy Collision Accelerator I
Small Energy Burst Aerator I
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
1.31.0 Stable    - YC119.8 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment] 2017-09-19 05:18
Did you happen to refresh the skills via API before mucking with skills and before this error happened? I can't reproduce the issue for myself, but we've had a bunch of `'NoneType' object` errors relating to `self.character = None` somehow, and the common theme is API skill update.

**Comment by blitzmann** [comment] 2017-09-22 06:11
Marking this as most likely a duplicate / extension of #1234, please continue discussion there is needed :)

**Closed by blitzmann** 2017-09-22 06:11 UTC
