### ISSUE TITLE
Pyfa crash after API key error importing skills

### ISSUE THREAD

**Issue by Jarten** [pyfa-org/Pyfa#1235] opened 2017-06-20 14:17 UTC
## Bug Report
Pyfa Error popup occurred several seconds after an error indication showed up on a skill import complaining about my API key.

The skills were updated anyway, so the error message seems misleading.
Several seconds later 8 PYFA Error windows popped up.
I may have right clicked in the ship background, and every time I tried to click the close icon of the error popup, another popup showed up, after 8 popups it somehow stopped.

Last error window contents are at the bottom of this report.

### Expected behavior:
Skill import successful, no Error window popup.

### Actual behavior:
API Key error followed by Error window popped up several seconds later.

### Detailed steps to reproduce:
Intermittent, unable to reproduce

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Bifrost, TI Bifrost (Skirmish)]

Damage Control II
Micro Auxiliary Power Core I
Nanofiber Internal Structure II

Republic Fleet Medium Shield Extender
Republic Fleet Medium Shield Extender
5MN Y-T8 Compact Microwarpdrive
Micro Jump Field Generator
Warp Disruptor II

'Malkuth' Rocket Launcher I
'Malkuth' Rocket Launcher I
'Malkuth' Rocket Launcher I
'Malkuth' Rocket Launcher I
[Empty High slot]
Skirmish Command Burst I, Rapid Deployment Charge

Small Core Defense Field Extender II
Small Core Defense Field Extender II

Caldari Navy Inferno Rocket x1000
Caldari Navy Mjolnir Rocket x1000
Caldari Navy Nova Rocket x1000
Caldari Navy Scourge Rocket x1000
Nanite Repair Paste x150
Evasive Maneuvers Charge x300
Interdiction Maneuvers Charge x300
Rapid Deployment Charge x300

### Release or development git branch? Please note the release version or commit hash:
pyfa version: 1.29.4 Stable - YC119.5 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.4 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\Jeff\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'name'

  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 577, in spawnMenu
    menu = ContextMenu.getMenu(selection, *contexts)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\contextMenu.py", line 85, in getMenu
    sub = m.getSubMenu(srcContext, selection, rootMenu, it, rootItem)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinContextMenus\changeAffectingSkills.py", line 88, in getSubMenu
    bitmap = BitmapLoader.getBitmap("lvl%s" % skill.level, "gui")
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 337, in level
    if self.character.name == "All 5":

**Comment by blitzmann** [comment] 2017-07-10 05:20
Sorry about my delayed response. Went on vacation recently and have been super busy since. 

> Intermittent, unable to reproduce

This is the story of my life. This is a phantom bug that keeps popping up. I know why it's happening (a Skill doesn't have a character assigned to it), but I don't know how it happens (a skill should always have a character assigned to it...). There's a dirty fix to it that I will implement if necessary, but I'd like to find the cause. And it always seems to happen after updating via API.

Do you remember what the import error said? Can you post your pyfa log (found in `%userprofile%/.pyfa/`)? I'm tracking a few other issues with the same error, and trying to get a better feel for errors of this nature

see #1234 for duplicate issue (and there's probably more in the issues list about it)

**Comment by blitzmann** [comment] 2017-07-16 02:12
closing as this is a duplicate of #1234

**Comment by blitzmann** [comment] 2018-03-01 05:34
hrm, never closed this. but I thin we found the problem, and a fix has been added to the next release. if you notice a problem moving forward, please let me know :)

**Closed by blitzmann** 2018-03-01 05:34 UTC
Labels: bug
