### ISSUE TITLE
Command Bursts which increase Remote Repair Speed are not applied when projecting the boosted fit onto another one.

### ISSUE THREAD

**Issue by NamelessNewbie** [pyfa-org/Pyfa#1125] opened 2017-04-14 10:16 UTC
## Bug Report

When projecting a boosted Logi fit onto another ship, the Remote Rep boosts don't get applied. They show up on the effect column on the logi fit, but the projected reps don't change. 

### Expected behavior:

Applying the Rapid Repair Boost to a Logi should increase the EHP/s on a ship that has the boosted Logi projected to it.

### Actual behavior:

The projected EHP/s stays the same, no matter if the Logi ship is boosted or not. 

### Detailed steps to reproduce:

1. Create a boosting fit, for example a Brutix, with a Armor Command Burst. Use the Rapid Repair Charge.
2. Create a Logi fit, e.g. an Oneiros with 4 t2 Large reps. Withh All Skills V each repper reps 85.3/s. Applying the Link, one repper reps now 100/s. This works fine. 
3. Create a third fit where you want to test the EHP/s gained. 
4. Project the Logi fit onto the new ship. The EHP/s stays exactly the same, no matter if you turn the link on the logi on or off. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any fit using Command Bursts with the Rapid Repair Charge and fits that use Remote Repair Modules. 

### Release or development git branch? Please note the release version or commit hash:

Both with the 2017.03.13 (release) fork and the current official release build (1.28.1)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment] 2017-04-14 13:22
Hi there!

I can't test or try to reproduce right now, but this sounds like a duplicate of #1081 which was fixed. I'll confirm this tonight and report back. Thanks for the report!

**Comment by blitzmann** [comment] 2017-04-15 03:32
Can confirm, seems to be a duplicate of #1081. A release will be out in the next couple of weeks with the fix.

**Closed by blitzmann** 2017-04-15 03:32 UTC
Labels: duplicate
