### ISSUE TITLE
exception when deleting a Drake fit

### ISSUE THREAD

**Issue by BoraVyvorant** [pyfa-org/Pyfa#1585] opened 2018-05-16 10:05 UTC
## Bug Report

Deleting a Drake fit causes a segment violation.

### Expected behavior:

Fit would just be deleted.

### Actual behavior:

Fit is deleted in the database, then application falls over.

### Detailed steps to reproduce:

remove ~/.pyfa directory
start pyfa
create an empty Drake fit
delete that fit

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Drake, Drake fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

### Release or development git branch? Please note the release version or commit hash:

2.0.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

macOS 10.13.4

### Other relevant information:

It's not just Drakes, although that makes for a funnier headline. It isn't all ship types, though, for example there's no problem if I create and then delete an empty Retribution fit.

Dump attached.

[dump.txt](https://github.com/pyfa-org/Pyfa/files/2008584/dump.txt)

**Comment by blitzmann** [comment] 2018-05-16 13:41
There's been a bug forever regarding fit deletion, usually happens when you delete a fit that is currently open. It's also not 100% reproducible, so it doesn't happen all the time. I think this is the first time I've seen it on a mac though, so this could be useful data.

I expect this is going to be one of the first things I look into after the next expansion release. The fix is probably going to be quite a bit of refactoring. :/

Duplicate #164, but going to keep this open specifically because it has useful dump information. 👍

**Comment by BoraVyvorant** [comment] 2018-05-16 14:37
Cheers. I have previously hit the deletion issue on the Mac, but never to such a great extent. It's also rock solid reproducible against an empty database.

My workround will be to simply never delete anything ever again, of course.

**Comment by blitzmann** [comment] 2018-05-16 15:14
> Cheers. I have previously hit the deletion issue on the Mac, but never to such a great extent. It's also rock solid reproducible against an empty database.

> My workround will be to simply never delete anything ever again, of course.

lol. So, this happens even when you delete a fit that isn't open? If that's the case, this is new information. 

If it's easily reproducible for you, then expect me to ping you... a lot... when I get around to refactoring the code behind fit deletion. :P

**Comment by BoraVyvorant** [comment] 2018-05-16 19:37
>So, this happens even when you delete a fit that isn't open? If that's the case, this is new information.

Hmmm. No, it seems that if I close the tab first, deleting the fit doesn't cause the crash any more. So maybe this is a variant you've seen before.

Here's the reproduceable sequence exactly:

* Click on Combat Battlecruiser
* Click on green + on Drake
* Hit enter
* Click on a module slot in the fitting
* Click on the red - on Drake

It's _very_ sensitive to details, though. For example, if you tab out to another application and back at some points, maybe it won't fall over. If you don't click on a module slot, maybe it won't fall over. But when I do _exactly_ the above, I get a failure every time.

Of course, no guarantee it will be this easy to repro with a new version.

**Comment by blitzmann** [comment] 2018-05-17 03:45
> It's very sensitive to details, though.

Yeah, this is what's made the issue so annoying to track. :P

Regardless, thanks for the bug report, and especially for the dump for mac. Could be very useful :)

**Comment by BoraVyvorant** [comment] 2018-05-19 20:01
2.0.2 no longer shows this behaviour using the recipe described. I will add another comment if I hit another case with this or a later release. Or we can close it if you want.

**Comment by DarkFenX** [comment] 2019-10-02 18:50
I believe this set of crashes has been fixed with set of updates to Dialog window management somewhere in 2019. Reopen if it still happens on the latest versions.

**Closed by DarkFenX** 2019-10-02 18:50 UTC
Labels: bug, duplicate
