### ISSUE TITLE
Agency drugs error

### ISSUE THREAD

**Issue by FourLe4f** [pyfa-org/Pyfa#2062] opened 2019-10-09 16:16 UTC
## Bug Report
pyfa v2.12.0
EVE Data Version: 1581357 (2019-10-08 13:11:13)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.9
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\contextMenu.py", line 163, in handler
  File "C:\projects\pyfa\gui\contextMenu.py", line 296, in _baseActivate
  File "C:\projects\pyfa\gui\builtinContextMenus\itemMarketJump.py", line 55, in activate
  File "C:\projects\pyfa\gui\marketBrowser.py", line 107, in jump
KeyError: 19

Agency drugs do not appear in items list

**Comment by DarkFenX** [comment] 2019-10-09 16:20
duplicate of #2061

**Closed by DarkFenX** 2019-10-09 16:20 UTC
