### ISSUE TITLE
Feature Request --Night Mode

### ISSUE THREAD

**Issue by cptashen** [pyfa-org/Pyfa#1782] opened 2018-10-26 14:38 UTC
Hi, first time using this site.

I'm wondering if it would be possible to create a night mode for Pyfa 

Thanks

~Ash

**Comment by blitzmann** [comment] 2018-10-26 18:58
Hi @cptashen!

A few attempts have been made to create simple theming support. I actually have an older branch that kinda sort of does it, but there's some serious issues with it. One of the major issues is that that are some widgets that just don't seem to play nice with it. For example, the fitting window column headers - it's impossible to change these from white on Windows.

We do support system default colors out of the box for linux operating systems. I know that means nothing to windows users though. >_>

This is something that I revisit every few months to try to devise a solution that looks good, but it isn't high on the priority list, at least it hasn't been in the past. There are a few tricks we might be able to utilize now that pyfa 2.0 ships with wxPython 4, maybe I should take another look at this soon :)

**Comment by DarkFenX** [comment] 2020-04-30 20:23
Duplicate of #1206

**Closed by DarkFenX** 2020-04-30 20:23 UTC
