### ISSUE TITLE
Drones skill level in Skills Required tooltip does not account for number of drones fitted

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#748] opened 2016-09-22 00:04 UTC
To fly a five-drone setup, Drones V is required. The Skills Required tooltip will show only the Drones level needed for the class of drones fitted, not the level needed for the number of drones currently active, The Drones Active display correctly says the right number and highlights red if it is exceeded.

Repeat by: 

1. Start to fit an Algos.
2. Select the "all zeros" character.
3. Install 5x Hobgoblin I in the drone bay.
4. Mark the drone stack active.
4. Note that the Skills Required tooltip only asks for Drones III.

**Comment by blitzmann** [comment] 2016-09-23 16:33
This is a question of semantics. The Skill Requirement tooltip only check if you have the skill required to use a particular item. It would not address the specific state of the current fit, and honestly that's not the proper place for that. What you're looking for is already noted with the drones active label. If Drones is level 0, it will show `5/0`, if it's level 5, it will show `5/5`.

https://gyazo.com/159054a1aa37c75c1495a639ad945e82

I'm going to close this issue as it's technically working as intended. If you feel like this can be improved in any way, please feel free to continue the conversation here. :)

**Closed by blitzmann** 2016-09-23 16:33 UTC
Labels: invalid
