### ISSUE TITLE
Graphs menu option disabled in 2.9.5

### ISSUE THREAD

**Issue by jasconius** [pyfa-org/Pyfa#2014] opened 2019-07-27 16:21 UTC
## Bug Report
Graphs menu option is grayed out and un-clickable in 2.9.5

### Expected behavior:
Graphs menu button is green and clickable

### Detailed steps to reproduce:
Updated to 2.9.5, ran normally. Reproduced easily after restarts.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any, apparenetly

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
![bug](https://user-images.githubusercontent.com/276055/61997011-2a585f00-b069-11e9-97e6-c1b90c68dd11.png)

**Comment by DarkFenX** [comment] 2019-07-27 16:24
Duplicate of #1998 (same bug, affects exe build as well). I am debugging it atm.

**Closed by DarkFenX** 2019-07-27 16:24 UTC
