### ISSUE TITLE
Crash when deleting opened fit on MacOS

### ISSUE THREAD

**Issue by yukixz** [pyfa-org/Pyfa#1302] opened 2017-09-25 04:20 UTC
### Expected behavior:
Opened fit window is closed when deleting the opened fit in ship browser.

### Actual behavior:
Pyfa crash when deleting the opened fit in ship browser.

### Detailed steps to reproduce:
1. Create an empty with any ship
2. Open the fit (automatically)
3. Delete the fit in ship browser
4. Pyfa crash

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Needless.

### Release or development git branch? Please note the release version or commit hash:
Release v1.32.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
MacOS 10.12.6

### Other relevant information:
It seems be a wxPython bug.

**Comment by blitzmann** [comment] 2017-09-25 04:25
Is there any crash info? Or just it just fail? I'm pretty sure it would be a duplicate of #164 and other assorted bugs, and I agree it's probably a wxPython issue (or more likely pyfa isn't handling certain events correctly).

**Comment by yukixz** [comment] 2017-09-25 04:28
It should be a dup. Thanks. 

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e55b47 wxEvtHandler::SearchDynamicEventTable(wxEvent&) + 49
1   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e55ac7 wxEvtHandler::TryHereOnly(wxEvent&) + 37
2   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e55a10 wxEvtHandler::ProcessEventLocally(wxEvent&) + 40
3   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e559a3 wxEvtHandler::ProcessEvent(wxEvent&) + 175
4   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e55751 wxEvtHandler::ProcessPendingEvents() + 783
5   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105d4339c wxAppConsoleBase::ProcessPendingEvents() + 208
6   libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e288b7 wxCFEventLoop::CommonModeObserverCallBack(__CFRunLoopObserver*, int) + 49
7   com.apple.CoreFoundation      	0x00007fff81fd3d37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
8   com.apple.CoreFoundation      	0x00007fff81fd3ca7 __CFRunLoopDoObservers + 391
9   com.apple.CoreFoundation      	0x00007fff81fb46d9 __CFRunLoopRun + 873
10  com.apple.CoreFoundation      	0x00007fff81fb4114 CFRunLoopRunSpecific + 420
11  com.apple.HIToolbox           	0x00007fff81514ebc RunCurrentEventLoopInMode + 240
12  com.apple.HIToolbox           	0x00007fff81514bf9 ReceiveNextEventCommon + 184
13  com.apple.HIToolbox           	0x00007fff81514b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
14  com.apple.AppKit              	0x00007fff7faada54 _DPSNextEvent + 1120
15  com.apple.AppKit              	0x00007fff802297ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
16  com.apple.AppKit              	0x00007fff7faa23db -[NSApplication run] + 926
17  libwx_osx_cocoau_core-3.0.0.2.0.dylib	0x000000010584097a wxGUIEventLoop::OSXDoRun() + 106
18  libwx_baseu-3.0.0.2.0.dylib   	0x0000000105e28de5 wxCFEventLoop::DoRun() + 39
19  libwx_baseu-3.0.0.2.0.dylib   	0x0000000105d74b57 wxEventLoopBase::Run() + 167
20  libwx_baseu-3.0.0.2.0.dylib   	0x0000000105d42b86 wxAppConsoleBase::MainLoop() + 102
21  _core_.so                     	0x0000000105211e24 wxPyApp::MainLoop() + 84
22  _core_.so                     	0x0000000105276377 0x10520c000 + 435063
23  org.python.python             	0x00000001005a3712 PyEval_EvalFrameEx + 17234
24  org.python.python             	0x000000010059f242 PyEval_EvalCodeEx + 1730
25  org.python.python             	0x0000000100531f76 0x100500000 + 204662
26  org.python.python             	0x000000010050e3b5 PyObject_Call + 101
27  org.python.python             	0x000000010051a4b6 0x100500000 + 107702
28  org.python.python             	0x000000010050e3b5 PyObject_Call + 101
29  org.python.python             	0x00000001005a328c PyEval_EvalFrameEx + 16076
30  org.python.python             	0x00000001005a6202 0x100500000 + 680450
31  org.python.python             	0x00000001005a24d1 PyEval_EvalFrameEx + 12561
32  org.python.python             	0x000000010059f242 PyEval_EvalCodeEx + 1730
33  org.python.python             	0x00000001005a3878 PyEval_EvalFrameEx + 17592
34  org.python.python             	0x000000010059f242 PyEval_EvalCodeEx + 1730
35  org.python.python             	0x00000001005a6266 0x100500000 + 680550
36  org.python.python             	0x00000001005a24d1 PyEval_EvalFrameEx + 12561
37  org.python.python             	0x000000010059f242 PyEval_EvalCodeEx + 1730
38  org.python.python             	0x000000010059eb76 PyEval_EvalCode + 54
39  org.python.python             	0x00000001005c6731 PyRun_FileExFlags + 161
40  org.python.python             	0x00000001005c627e PyRun_SimpleFileExFlags + 718
41  org.evefit.pyfa               	0x000000010000275b 0x100000000 + 10075
42  org.evefit.pyfa               	0x000000010000117a main + 650
43  org.evefit.pyfa               	0x0000000100000be4 start + 52
```

**Closed** 2017-09-25 04:28 UTC

**Comment by blitzmann** [comment] 2017-09-25 04:57
Yeah. Unfortunately I'm just not knowledgeable enough to debug it into the underlying C++ code. It almost certainly has to do with how we handle the delete event, and I've been meaning to look into it for a while now and generally make it more efficient, however I will be focused on some other initiatives that may help this and some other GUI bugs.
