### ISSUE TITLE
[Feature Request] Prices on implants and boosters.

### ISSUE THREAD

**Issue by Ligraph** [pyfa-org/Pyfa#678] opened 2016-07-09 04:10 UTC
It would be amazing to be able to see prices like on modules/drones.

**Comment by blitzmann** [comment] 2016-07-11 17:45
Should be as easy as adding that column to the display. Will take a look, thanks!

**Comment by blitzmann** [comment] 2016-07-25 04:07
Took a look at this, and it's not as simple as I thought, which is probably why they were not included to begin with. I would still like to fix this eventually though.

Techy version:

The price column checks to see if the item has a valid price (isn't outdated). If it checks out, it simply displays it. If not, it stores the item's ID with the price fetching thread with a callback that updates the GUI text for the price.

Now, the actual code that gets the price is found in the price stats pane. It compiles a list of modules and send it to the price fetcher thread. It then fetches the price, and tries to find the item in the previously stored items and calls the callback.

The problem is that the implants and boosters are not compiled with the rest of the fits price, and thus the prices never get updated.

This is pretty bad design. I might be able to fiddle with it so that the wait list is what is process when the fetcher is triggered, rather than supplying a list of items to fetch. We shall see...

**Comment by Ebag333** [comment] 2017-03-14 22:57
See #1038 for a partial solution.

It doesn't add a price column.  _Yet._

**Comment by blitzmann** [comment] 2017-04-11 01:18
Fixed with #1115

**Closed** 2017-05-10 03:35 UTC
Labels: done, enhancement
