### ISSUE TITLE
FAX Can only use 1 Command Burst

### ISSUE THREAD

**Issue by SomeoneStrange** [pyfa-org/Pyfa#2039] opened 2019-09-06 19:07 UTC
After recent update, all capitals and supers can use correct # of command bursts except for FAX - these are still capped at one online burst each.

Could be related to Issue 2031.

**Comment by DarkFenX** [comment] 2019-09-06 19:17
Duplicate of #2036. Was fixed after 2.10.1, so will have to wait until next release.

**Closed by DarkFenX** 2019-09-06 19:17 UTC
