### ISSUE TITLE
DPS Graph

### ISSUE THREAD

**Issue by Tuxer55** [pyfa-org/Pyfa#924] opened 2016-12-30 20:52 UTC
My DPS Graph doesn't open under Arch Linux.
Version pyfa 1.26.0

**Comment by resinneublem** [comment] 2016-12-30 21:00
Looks like matplotlib isn't included in the release zip. I can reproduce on Ubuntu 16.04 if I first uninstall the python-matplotlib package.

**Comment by resinneublem** [comment] 2016-12-30 21:03
I guess matplotlib is considered optional? No idea why that is: https://aur.archlinux.org/packages/pyfa/

**Comment by Tuxer55** [comment] 2016-12-30 21:20
Nice thanks, after installing the python2-matplotlib package is works! :)
Maybe it works also with the python-matplotlib package, but i don't look at the differents of the 2 packages ;)

**Comment by MechaLynx** [comment] 2016-12-30 21:36
`python-matplotlib` is for python 3, pyfa is in python 2. The naming scheme on Arch is different: `python` is for version 3, the default for Arch, which is opposite of most distros.

**Comment by Ebag333** [comment] 2016-12-30 21:47
>The naming scheme on Arch Linux is different: python is for version 3, the default for Arch, which is opposite of most distros. So on this distro you need python2 packages for pyfa to work.

So in order to make Arch work out of the box, it sounds like it'd need it's own skeleton.

**Comment by MechaLynx** [comment] 2016-12-30 21:59
It seems it's been taken care of, the `pyfa-start.sh` script uses `python2` as needed, but yeah if you want it to work without that on Arch, you'd need the package install script to change every shebang line to point to `python2` instead. Not really needed unless someone wants to work on pyfa's code while using Arch and needing to execute single scripts alone _and_ can't use sed for some reason.

**Comment by blitzmann** [comment] 2016-12-30 23:01
Linux skeletons aren't a thing, and won't be a thing, simply because it's unneeded. The only reason why we do it with OS X and Windows is because they don't have package managers (and Windows / OS X users expect things to "just work").

Arch has it's own build system called AUR. It's up to the maintainer of that particular package to bring in the correct packages needed to make pyfa work, and it's also up to them how to classify each package (optional vs mandatory). This is a third party package, BTW, and I have no control over it - you have to get in touch with whoever is maintaining it. 

I should also just point out quickly that we support Linux in the sense that it works once you have all the dependencies sorted out and know how to run it from terminal - how to get it set up is wholly up to the user to figure out due to the plethora of different distros out there (and since it's Linux, it's generally assumed you know what you're doing).

Gonna close this issue as the OP has solved it. :)

**Closed by blitzmann** 2016-12-30 23:01 UTC

**Comment by resinneublem** [comment] 2016-12-31 01:03
Should we stop releasing a linux.zip then? We already release a source zip.

If I downloaded a linux.zip (32 or 64bit) I would assume it's an installer or self-contained executable with the dependencies sorted out for me. Like the Eve Linux client.

**Comment by blitzmann** [comment] 2016-12-31 01:26
> Should we stop releasing a linux.zip then? We already release a source zip.

I have always questioned why we release a linux.zip. It was that way when I joined the project, and when I took over I just kept it that way. I believe it's because, initially, we used GitHub for only code and not releases - so we had a way to package a source zip. When we switched over to GitHub releases, GitHub automatically does that for us. The linux.zip archive does have this file in it: https://github.com/pyfa-org/Pyfa-skel/blob/master/src/info.py But that's the only difference really between that one and source. There is the possibility of folks using that file for whatever reason (in their package management or whatever).

Also, GitHub API exposes the downloads for the packages uploaded. It doesn't keep track, AFAIK, of the source code archives that are downloaded. I have a local page that shows the download stats of the releases, so it's somewhat useful in knowing how popular the linux package is (obviously, doesn't take into consideration git clones and what not).

As it stands now, I don't think I want to change anything. It's been this way for years and is assumed.
