### ISSUE TITLE
CREST: issues in browsers other than Chrome

### ISSUE THREAD

**Issue by wvdvegt** [pyfa-org/Pyfa#950] opened 2017-01-19 14:45 UTC
Hi

Trying to get pyfa working under windows 10 but have problems logging in with CREST.

The callback url uses localhost where (using sysinternals's txpview utility) pyfa opened a listening port on my machine name (so not localhost or 127.0.0.1).

I think there is something wrong with the code that opens this 'webserver' port.

**Comment by blitzmann** [comment] 2017-01-19 18:47
The way that it should work is that you try to log into CREST -> pyfa starts a server listening on port 6461 > once logged into EVE, it'll redirect back to `localhost:6461` which should automatically be handled by the webserver and display a confirmation page.

There is a 60 second time out between the server starting and the server receiving the response. It won't work if you sit on the eve login page for any amount of time.

You should also check that pyfa has access to start a webserver and open ports on your machine, and make sure there isn't any software firewall (such as Windows Firewall) that is preventing it from receiving traffic.

Can you describe in greater detail what's happening after you log into EVE? Does it not display any confirmation page?

**Comment by blitzmann** [comment] 2017-01-25 15:04
@wvdvegt any more info? Unfortunately I cannot reproduce, and without further info I'm gonna have to close this issue. Again, check windows firewall, let me know at which step it's failing on, etc. Thanks!

**Comment by blitzmann** [comment] 2017-02-08 17:48
@wvdvegt gonna close this issue as I cannot reproduce. If you're able to reproduce, please reopen. :) Thanks!

**Comment by NickLinnear** [comment] 2017-02-25 10:47
I can confirm the issue. When I click on CREST-Login (implicit mode), the EVE-Login page appears to confirm the necessary rights. After clicking on authorize the tab redirects to localhost:6461:/... and the caption changes to "pyfa local server" for a short time. Then I get the error that the web-page is not reachable. I use Windows10 and EDGE.
After trying the procedure with Chrome, I saw an Error Message like "Can't parse Query Parameters" for about a second and then "Connection refused".

**Comment by NickLinnear** [comment] 2017-02-25 10:49
The URL looks like:
http://localhost:6461/?access_token=<access_token>&token_type=Bearer&expires_in=1200&state=<guid>

**Comment by NickLinnear** [comment] 2017-02-25 13:26
After downloading the Git-Repository and installing all prerequisites for running the code on my Developer-VM (Windows 10, Browser EDGE), everything worked fine. So I can confirm both: Developer cannot reproduce, End-User cannot login via CREST.

**Comment by blitzmann** [comment] 2017-02-25 18:04
So there is an issue with v1.26 with implicit auth (see #998). I'm making a new build today that has a fix for it. So I'd like for you to let me know after the new build if you're still running into this issue or not ;)

**Comment by NickLinnear** [comment] 2017-02-26 08:47
Works perfect. Thank you.

**Comment by wvdvegt** [comment] 2017-02-26 11:19
NickLinnear, did you change anything to the edge/windows settings? I have the issue that the browser won't redirect to localhost so the title does not change to pyfa local server but goes strait into a timeout.
I'm using a fully patched the anniversary build.

**Comment by wvdvegt** [comment] 2017-02-26 11:30
Maybe an idea (workaround) is to add an option to the configuration to choose a browser to use for authentication. I don't mind it being Chrome, but I do mind if I have to change my default browser to Chrome.

**Comment by wvdvegt** [comment] 2017-02-26 12:41
At https://docs.python.org/2/library/webbrowser.html#webbrowser.get it states that 

If the environment variable BROWSER exists, it is interpreted to override the platform default list of browsers, as an os.pathsep-separated list of browsers to try in order. When the value of a list part contains the string %s, then it is interpreted as a literal browser command line to be used with the argument URL substituted for %s; if the part does not contain %s, it is simply interpreted as the name of the browser to launch. [1]

However it fails on my machine as well (edge is still opened).

**Comment by wvdvegt** [comment] 2017-02-26 13:09
Found a solution for above, change the line 
`            	webbrowser.open(uri) 
`in
`            	def ssoHandler(self, event):`
to

```
            	webbrowser.register('chrome', None, webbrowser.GenericBrowser('C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'))
                b = webbrowser.get('chrome')
                b.open(uri)
```
after which Chrome is used (in this example) to login into crest instead of Windows default browser.

**Comment by NickLinnear** [comment] 2017-02-26 14:49
I didn't change the configuration of my Edge browser (about:flags = Default). 
Setting the Environment Variable BROWSER didn't work on my System either.

**Comment by blitzmann** [comment] 2017-02-26 16:53
Ah, so this only works in Chrome then?

tbh, I didn't bother to test in other browsers. This is such simple javascript I didn't think it was necessary. I'll take a look and see what the behavior is like in edge / firefox, but if that doesn't help I'll try out your solution about explicitly using chrome to open. That would be unfortunate though if the user doesn't have chrome installed. :/

**Comment by wvdvegt** [comment] 2017-02-26 17:51
Hi

Edge and Internet Explorer on Windows 10 both reject a redirect to localhost and present a timeout. has nothing to do with simple javascript but security.

The code allows just you to set a browser to use other then the default browser (Edge in my case). Other browsers may work too like FireFox.

**Comment by blitzmann** [comment] 2017-02-26 17:55
> Edge and Internet Explorer on Windows 10 both reject a redirect to localhost and present a timeout. has nothing to do with simple javascript but security.

This seems dumb. If you are on localhost already, you should be able to redirect to localhost . I can understand a webpage on the public internet not allowing that, or not allowing redirection to a different port...

Thanks for the info though. I've been meaning to add the ability to just display the information that you need and be able to input it into pyfa manually. But that's a lot of work unfortunately. Maybe in the interim I can have a link that displays for IE/Edge that you can click on to actually register the information to the server.

**Comment by NickLinnear** [comment] 2017-02-26 19:15
As I said before, on my System EDGE works after installing the new Version.
I tried the Internet-Explorer and that one also works without any problem. Are you sure _wvdwegt_, that there is not some other program (firewall, anti-virus, ...) that prevents the Microsoft browsers from working? I did not change any settings in the Explorer or EDGE, I am not member of a domain or have any entries in my hosts-File and IP4/IP6 is configured properly.

**Comment by blitzmann** [comment] 2017-02-26 19:21
@NickLinnear @wvdvegt 

I can confirm that Edge works just fine for me as well with implicit authentication. v0v

**Comment by blitzmann** [comment] 2018-05-28 21:51
I'm going to close this issue on two accounts:

* I wasn't able to reproduce a lot of the issues here. 
* Even though the new pyfa 2.x ESI login procedure is very similar to the CREST login procedure, there is a new option that allows you to bypass spinning up a local server (and thus havign to do the localhost redirect). Using that option (set in the preferences), the info pyfa requires is printed by pyfa.io - you copy and paste it into pfya and boom, done, no need to use a localhost redirect.

If there's any problems with the new methods, please open a new issue, thanks! :)

**Closed by blitzmann** 2018-05-28 21:51 UTC

**Comment by wvdvegt** [comment] 2018-05-29 08:18
Btw if you want to oAuth login without starting web servers and run into firewall issues, an easier way might be following the URL that an embedded browser is trying to display. 

The last one (just before the redirect to localhost:6461 already contains the token you need to verify the pilot in the URL. Just stop/close the browser when you got the token.

**Comment by blitzmann** [comment] 2018-05-29 14:00
> following the URL that an embedded browser is trying to display (with events like OnNavigate or alike).

Embedded browsers are a big no no for OAuth - the entire idea of OAuth is to take control away from the application requesting permission. If pyfa was a malicious program, it could use an embedded browser to track things like keystrokes, and thus get username and passwords for EVE accounts when they sign into SSO. Even though pyfa would never do this, it's still a pretty significant security breach, as well as a break in the normal operation of OAuth. :)

**Comment by wvdvegt** [comment] 2018-05-29 14:48
It was just a suggestion (which removes all firewall issues) 

Some remarks:

- Starting software is already a risk.
- What you describe is btw a good reason for having 2 factor authentication. 
- Logging keystrokes on other applications is also not that hard (so having an external browser sounds better then it is too). It's what keyloggers do.
- Starting a webserver at a high port number leaves open quite some issues as well.
