### ISSUE TITLE
Extraorbitant stacking with circular projection / command bursting

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#1193] opened 2017-05-27 10:19 UTC
### Expected behavior:
Normal bonus onto Crucifier

### Actual behavior:
TD shows range of 1061km+354km with 581% strength (lol)

### Detailed steps to reproduce:
Create both fittings and open them.
Project Crucifier onto Nighthawk.
Add Nighthawk as Command Booster for Crucifier.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
```
[Crucifier, TEST]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Tracking Disruptor II, Optimal Range Disruption Script
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```
```
[Nighthawk, TEST]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Information Command Burst II, Electronic Superiority Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]


Information Command Mindlink
```
### Release or development git branch? Please note the release version or commit hash:
Pyfa 1.29.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:

Yeah it's me with the Info links again... sorry

**Comment by blitzmann** [comment] 2017-05-28 01:37
Yep, this was reported to me privately along with data needed to verify (which was AT sensitive, so can't post the exact details). I never got around to making a general bug report about it. I know what the problem is and have a potential fix for it, but am wanting to test it out a bit more thoroughly (also, I didn't know this affected projections as well - I only verified and fixed the command issue. Testing recursive projections was on the list of things to test it with)

Will update issue with more info as required, or when a fix is in place. :)

**Closed** 2017-06-01 04:16 UTC
Labels: bug, fixed
