### ISSUE TITLE
Delete fitting shows error

### ISSUE THREAD

**Issue by dyh135** [pyfa-org/Pyfa#1415] opened 2018-02-21 03:37 UTC
Whenever I delete a fit the same error message will pop up, I have try to clean up the .pyfa database and setting, still getting the same errors.

Steps:

1) delete whatever fit you already have.

2) error message pop up

3) Fitting got deleted

---------------------------------------------------------------------------------------------------------------------

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.11.1
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 300, in fitRemoved
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1203, in refreshFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1207, in recalc
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by blitzmann** [comment] 2018-02-23 04:35
This is a duplicate of #1384. I plan to re-work the whole workflow for deleting a fit soonish to hopefully avoid issues like this (in which we're trying to get information about a deleted fit).

In the meantime, make sure the fit you're trying to delete is not open in the fitting window tabs. That should help a great deal in avoiding this error. :)

**Closed by blitzmann** 2018-02-23 04:35 UTC
