### ISSUE TITLE
bug reprot from pifa system

### ISSUE THREAD

**Issue by nissaba** [pyfa-org/Pyfa#1253] opened 2017-07-15 01:48 UTC
OS version: 	Darwin-16.6.0-x86_64-i386-64bit
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.9
Logbook: 	1.0.0
pyfa version: 1.30.0 Stable - YC119.7 1.0
pyfa root: /Applications/pyfa-4.app/Contents/Resources
save path: /Volumes/LaCie/pascale/.pyfa
fs encoding: utf-8

EXCEPTION: 'ascii' codec can't encode characters in position 1-3: ordinal not in range(128)

  File "wx/_core.pyc", line 16766, in <lambda>
  File "/Applications/pyfa-4.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/builtinAdditionPanes/projectedView.py", line 294, in spawnMenu
  File "/Applications/pyfa-4.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/contextMenu.py", line 73, in getMenu
  File "/Applications/pyfa-4.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/builtinContextMenus/itemRemove.py", line 28, in getText

**Comment by blitzmann** [comment] 2017-07-16 02:06
Can you go more into what you were trying to do when the error occurred? It looks like you right clicked an item, do you remember which one?

Can you send me the logs found at `%userprofile%\.pyfa` to sable.blitzmann@gmail.com?

Thanks :)

**Comment by nissaba** [comment] 2017-07-16 19:37
In the projected section right clicked item created from right click on fit and select project onto active fit

Envoyé de mon iPhone

**Comment by blitzmann** [comment] 2017-09-19 03:53
I just got a Mac mini from a friend of mine last week, for the express purpose of testing pyfa on OS X, since I cannot reproduce on Windows.

@nissaba are you still having this issue?  Can you remember the module that you were right-clicking that produced the error? Can you supply a screenshot of the error along with pyfa, with the fitting and projected section clearly shown? Thanks :)

**Comment by blitzmann** [comment] 2017-09-20 02:02
Calling @jasconius,do you think this may be another manifestation of something similar to #1149 / #1196? The reason I ask is because the bug report is from an OS X system, and the offending line is:

`return "Remove {0}".format(itmContext if itmContext is not None else "Item")`

`itmContext ` is something that pyfa itself provides, and is usually "Module", "Drone", etc - nothing fancy. Additionally, the string that is passed is a unicode string. So not sure what is happening here, just thinking it may be a mac only issue?

**Comment by jasconius** [comment] 2017-09-20 02:07
it's not directly the same bug but it's possible that somewhere else in the application you're getting some more bad bits on Mac from Wx, and it's just happening to rear its head here

you should be able to wrap that line in a try/except to skate by for now

**Comment by blitzmann** [comment] 2017-09-20 02:17
Can you attempt to reproduce when you've got some time to kill since you have a mac ready? I still need to set up my mini with dev tools and the like. I may as well add some logging to that area like I did last time which showed the odd characters towards the end.

**Comment by nissaba** [comment] 2017-09-20 10:34
I tested it a few time on the latest version and what ever it was it is fixed. 

Envoyé de mon iPhone

**Comment by nissaba** [comment] 2017-09-20 10:38
That or it is dependent on the data of the specific fit i was working on which :( i deleted. 

Envoyé de mon iPhone

**Comment by nissaba** [comment] 2017-09-20 10:53
I am finding that after adding a celestial item in the “projected” section that I am not able to delete it. I can change it but not delete. The delete options in the contextual menu is available and enabled, clicking it does not remove the celestial. If I have an other ship listed along side in this section I can delete that ship item from the list, but still not able to delete the celestial. 

Envoyé de mon iPhone

**Comment by blitzmann** [comment] 2017-09-21 02:04
> I am finding that after adding a celestial item in the “projected” section that I am not able to delete it. 

Known issue, already fixed, will be available in the next update. In the meantime, you can double click to remove.

>That or it is dependent on the data of the specific fit i was working on which :( i deleted.

It might be dependant on the fit you were working on.

**Comment by blitzmann** [comment] 2017-10-29 23:00
This seems like it was a duplicate of #1313, which was fixed. Gonna close this for now - if it creeps back up, please re-open this or add a new issue :)

**Closed by blitzmann** 2017-10-29 23:00 UTC
Labels: Need More Info
