### ISSUE TITLE
mabook air 2014, os x el capitan

### ISSUE THREAD

**Issue by gradash** [pyfa-org/Pyfa#1337] opened 2017-11-18 00:21 UTC
cant copy-paste api key, just nothing happens
tried opera and safari

**Comment by blitzmann** [comment] 2017-11-23 04:59
There is a known issue with the mac build where we capture ctrl+v (or whatever it is on the mac to paste) so that you can paste EFT fittings into pyfa. You'll have to use the right click menu to paste into the thing.  

The problem is that this is like a global shortcut and text boxes on the mac seem to adhere to it whereas all other OS text controls handle the event themselves first and foremost.  This has been a problem that has been difficult to properly debug for me in the past for lack of a real mac. I hope to look into this issue again soon :)

**Comment by blitzmann** [comment] 2018-05-22 04:36
Never closed this as a duplicate of #490...

No new progress on this unfortunately, but the API keys aren't really a thing anymore so... fixed by deprecation? lol

**Closed by blitzmann** 2018-05-22 04:36 UTC
