### ISSUE TITLE
Importing api key / Verification code for new char is not working on mac

### ISSUE THREAD

**Issue by hugohase** [pyfa-org/Pyfa#877] opened 2016-12-04 15:51 UTC
hi,

i try to create a new char with the char editor and try to ctrl c / ctrl v cmd c / cmd v the api infos from the website but the input fields don't accept this.

if i try to copy a string from an existing char the popup opens for the format and it exports a fit not the key.

**Comment by blitzmann** [comment] 2016-12-05 03:03
Probably a duplicate of #490. Haven't had a chance to fix it yet ;_;

**Closed by blitzmann** 2016-12-05 03:03 UTC
Labels: duplicate
