### ISSUE TITLE
Putting Pyfa inside a folder with special characters breaks it.

### ISSUE THREAD

**Issue by Altrue** [pyfa-org/Pyfa#548] opened 2016-03-27 16:09 UTC
(On Windows 7)

Hi,
I'm a french guy, as such my Download folder is named "Téléchargements". Trying to launch Pyfa from inside this folder (Téléchargements/Pyfa) will display a nasty error message. But "Telechargement" is fine.

It's not major or anything but I thought I should let you know ;)

**Comment by neutronst4r** [comment] 2016-05-28 10:22
I just run "python2 Downloads/P%yfá-mastér/pyfa.py" on my Arch system and it works fine without error messages. So seems to be Windows specific.

**Comment by Ebag333** [comment] 2016-10-16 20:02
Windows has rather strict limits on what you can and can't do with folder names.

Unfortunately, there isn't a good way around this.  I'm planning on looking at some folder stuff anyway (there's issues with the way Pyfa handles it currently) so I might look into this at the same time.

**Comment by blitzmann** [comment] 2016-10-16 23:31
I feel like this would be an easy fix and probably has to do with unicode issue or whatever.

**Comment by Ebag333** [comment] 2016-11-27 05:25
@blitzmann I think I figured out how to fix this...

**Comment by blitzmann** [comment] 2016-11-27 05:29
@Ebag333 Awesome! it really shouldn't be too difficult, just ensuring that we are being safe with unicode paths. I'll await your pull request - I'd like to get this merged sooner rather than later if you've already got a fix in for it :)

**Comment by Ebag333** [comment] 2016-11-27 05:34
It's kinda sorta not difficult?

The fix is basically this (for the save location:
```
    root = os.path.expanduser(os.path.join("~", ".pyfa"))
    if type(root) == str:  # leave unicode ones alone
        try:
            root = root.decode('utf8')
        except:
            root = root.decode('windows-1252')
```

The _catch_ (and there always is one isn't there) is that we bloody use the built in os.path.join all over the freaking place.

I'm writing two functions (one for Pyfa location, one for save location) to handle it, and should handle appending names/etc cleanly as well as returning just the path, so will then need to convert the 64 times we use `os.path.join` (along with the dozens of other path functions) to point to the two functions in `config.py`.

So yeah, relatively easy fix, painful with a lot of refactoring.

**Comment by blitzmann** [comment] 2016-11-27 05:54
@Ebag333 this doesn't seem like a correct fix. =/

Give me a bit of time to look into it before you go through the trouble. I'd like to research this a bit more for my own benefit as well (unicode kicks my ass)

**Comment by blitzmann** [comment] 2016-11-27 06:04
Also @Ebag333 are you able to reproduce this on Windows 10? If so, how? I've tried a variety of ways, and pyfa runs fine with all of them :(

**Comment by Ebag333** [comment] 2016-11-27 06:14
>this doesn't seem like a correct fix.

Numerous StackOverflow threads say otherwise.  All hail our StackOverflow masters!

It flat out works.  When we handle it this way you can debug and see that the path is correct (even shows the correct unicode character, not a ? or just missing).

The one that's throwing me fits right now is Russian, because pyCharm just croaks on it.
`pydev debugger: warning: trying to add breakpoint to file that does not exist: c:\users\ebag333\documents\github\ebag333\??????\config.py (will have no effect)`

So I can't test it against Russian at all, I can only test it against the other ones that have been posted.

Also, to make things even _more_ fun, because we treat the final build differently in code than our non-final build, we have these wonderful things:
`if isFrozen():`

So debugging it in pyCharm runs fine, because it skips a bunch of them, because it's not Frozen.

>Also @Ebag333 are you able to reproduce this on Windows 10? If so, how? I've tried a variety of ways, and pyfa runs fine with all of them :(

Reproduced easily.  Can't reproduce exactly in pyCharm, you have to modify the `isFrozen` statements above to be `not isFrozen`, but then you can see what the path it's trying to use is.  It doesn't exactly break in pyCharm either, it keeps trying to truck along, so pretty much you're looking for if it shows the unicode char correctly or not.

The build is a PITA, because I have to dump the .py file into the zip and pretty much see if it throws an error or not.  But I've gotten at least 2 of the folder names (which I confirmed were broken) to work fine.  At least for launching Pyfa, I'm sure they'd croak on one of the other `os.path` statements we have elsewhere.

**Comment by blitzmann** [comment] 2016-11-27 06:31
This is probably a build issue then, which makes sense - the build was created with a non-unicode locale.

If we can generate a build with the unicode locale as default, should work

**Comment by blitzmann** [comment] 2016-11-27 06:36
Or, we can set the locale:

```
import locale
locale.setlocale(locale.LC_ALL, '')
```

Although records show this was already in mainFrame.py, but removed at some point. This should override the default locale (would need to be tested with the builds...)

**Comment by Ebag333** [comment] 2016-11-27 06:37
That might help with some, but I still think we should properly handle the paths for `unicode`, `utf8`, and `windows-1252`.

It actually wasn't as painful as I thought, most of the references are in the scripts directory.  You're on your own there. :)

**Comment by blitzmann** [comment] 2016-11-27 06:52
Eh, maybe...

Why are you adamant about changing all os.path functions? You should be able to get pyfapath and save path to set correctly with unicode - all other path functions should branch off of those two, so as long as those are set up correctly, no problems.

**Comment by Ebag333** [comment] 2016-11-27 07:03
Wish that were true.  I tried that, and would get errors even if the base path was set properly.  Apparently any time you call `os.path` you can screw it up unless you handle it, a lot of people seem to write a custom walk function to take care of it and replace or enhance the built in function.

Anyway, PR is pushed.  #854

**Comment by blitzmann** [comment] 2016-11-28 03:12
I guess it's not too big of a deal. I still feel there should be a better solution to this, but it may very well be an issue with python 2.7 and it's shit unicode handling. At least we only need to deal with paths in a few select places. :D

**Comment by Ebag333** [comment] 2016-11-28 03:16
>it it may very well be an issue with python 2.7 and it's shit unicode handling

From what I read, it can be an issue for 3 as well.  So might need an enhancement to Eos/Pyfa-NG.  We can burn that bridge when we come to it tho.

**Comment by blitzmann** [comment] 2017-02-14 19:48
@Altrue I'll be making a release in the next couple days which should (hopefully) fix this issue. :D

**Closed** 2017-02-17 04:44 UTC
Labels: bug, fixed
