### ISSUE TITLE
Pyfa 2.17 crash on startup

### ISSUE THREAD

**Issue by Thoreas** [pyfa-org/Pyfa#2134] opened 2020-02-11 16:30 UTC
### Expected behavior:
Running pyfa.exe brings up the GUI.

### Actual behavior:
Running pyfa.exe causes it to crash before any GUI is displayed.

### Release or development git branch? Please note the release version or commit hash:
Release 2.17.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Same scenario on two separate PCs:
Windows 10 Build 17763.1012
Windows 10 Build 18362.356

### Other relevant information:
Log:

```[2020-02-11 16:23:25.467177] INFO: __main__: Starting Pyfa
[2020-02-11 16:23:25.467177] INFO: __main__: 
[2020-02-11 16:23:25.467177] INFO: __main__: Writing log file to: C:\Users\Swevener\.pyfa\pyfa.log
[2020-02-11 16:23:25.467177] INFO: __main__: Running in a frozen state.
[2020-02-11 16:23:25.512188] INFO: eos.db: Initializing database
[2020-02-11 16:23:25.512188] INFO: eos.db: Gamedata connection: sqlite:///C:\Games\Pyfa\eve.db?check_same_thread=False
[2020-02-11 16:23:25.512188] INFO: eos.db: Saveddata connection: sqlite:///C:\Users\Swevener\.pyfa\saveddata.db?check_same_thread=False
[2020-02-11 16:23:25.512188] DEBUG: eos.db: Initializing gamedata
[2020-02-11 16:23:25.516188] DEBUG: eos.db: Getting gamedata version
[2020-02-11 16:23:25.518189] DEBUG: eos.db: Initializing saveddata
[2020-02-11 16:23:25.519189] DEBUG: eos.db: Importing gamedata DB scheme
[2020-02-11 16:23:25.566679] DEBUG: eos.db: Importing saveddata DB scheme
[2020-02-11 16:23:25.606756] DEBUG: eos.db: Importing gamedata queries
[2020-02-11 16:23:25.606756] DEBUG: eos.db: Importing saveddata queries
[2020-02-11 16:23:25.607756] DEBUG: service.prefetch: Run database migration.
[2020-02-11 16:23:25.611757] DEBUG: service.prefetch: Starting database validation.
[2020-02-11 16:23:25.611757] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for character skills.
[2020-02-11 16:23:25.612757] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned characters attached to fits.
[2020-02-11 16:23:25.613699] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned damage patterns attached to fits.
[2020-02-11 16:23:25.614685] ERROR: eos.db.saveddata.databaseRepair: Missing uniform damage pattern.
[2020-02-11 16:23:25.615686] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing damage pattern names.
[2020-02-11 16:23:25.616686] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing target resist names.
[2020-02-11 16:23:25.617686] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned drones items.
[2020-02-11 16:23:25.617686] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned cargo items.
[2020-02-11 16:23:25.618686] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned fighters items.
[2020-02-11 16:23:25.619687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned modules items.
[2020-02-11 16:23:25.620687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (em)
[2020-02-11 16:23:25.620687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (thermal)
[2020-02-11 16:23:25.621687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (kinetic)
[2020-02-11 16:23:25.622687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (explosive)
[2020-02-11 16:23:25.622687] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (em)
[2020-02-11 16:23:25.623697] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (thermal)
[2020-02-11 16:23:25.624689] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (kinetic)
[2020-02-11 16:23:25.625689] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (explosive)
[2020-02-11 16:23:25.625689] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for duplicated selected ammo profiles.
[2020-02-11 16:23:25.626689] DEBUG: service.prefetch: Completed database validation.
[2020-02-11 16:23:26.641044] INFO: gui.bitmap_loader: Using local image files.
[2020-02-11 16:23:26.644045] DEBUG: gui.contextMenu: registering context menu class OpenFitInNewTab
[2020-02-11 16:23:26.645046] DEBUG: gui.contextMenu: registering context menu class AddBrowsedFits
[2020-02-11 16:23:26.647045] DEBUG: gui.contextMenu: registering context menu class AddCurrentlyOpenFit
[2020-02-11 16:23:26.647045] DEBUG: gui.contextMenu: registering context menu class AddEnvironmentEffect
[2020-02-11 16:23:26.775074] DEBUG: service.market: Initialize ShipBrowserWorkerThread.
[2020-02-11 16:23:26.911892] DEBUG: service.fit: Initialize Fit class
[2020-02-11 16:23:26.938898] DEBUG: service.fit: Getting fits with modules
[2020-02-11 16:23:26.960903] DEBUG: gui.contextMenu: registering context menu class AddCommandFit
[2020-02-11 16:23:26.961903] DEBUG: gui.contextMenu: registering context menu class TargetProfileAdder
[2020-02-11 16:23:26.962903] DEBUG: gui.contextMenu: registering context menu class ChangeShipTacticalMode
[2020-02-11 16:23:26.962903] DEBUG: gui.contextMenu: registering context menu class ChangeModuleAmmo
[2020-02-11 16:23:26.962903] DEBUG: gui.contextMenu: registering context menu class ChangeModuleSpool
[2020-02-11 16:23:26.962903] DEBUG: gui.contextMenu: registering context menu class BoosterSideEffects
[2020-02-11 16:23:26.963903] DEBUG: gui.contextMenu: registering context menu class FighterAbilities
[2020-02-11 16:23:26.963903] DEBUG: gui.contextMenu: registering context menu class TargetWrapperResists
[2020-02-11 16:23:26.965904] DEBUG: gui.contextMenu: registering context menu class TargetProfileEditorMenu
[2020-02-11 16:23:26.998914] DEBUG: gui.contextMenu: registering context menu class ItemStats
[2020-02-11 16:23:26.998914] DEBUG: gui.contextMenu: registering context menu class JumpToMarketItem
[2020-02-11 16:23:26.999915] DEBUG: gui.contextMenu: registering context menu class FitSystemSecurityMenu
[2020-02-11 16:23:26.999915] DEBUG: gui.contextMenu: registering context menu class JumpToShip
[2020-02-11 16:23:26.999915] DEBUG: gui.contextMenu: registering context menu class RemoveItem
[2020-02-11 16:23:27.000915] DEBUG: gui.contextMenu: registering context menu class ChangeItemAmount
[2020-02-11 16:23:27.000915] DEBUG: gui.contextMenu: registering context menu class ChangeItemProjectionRange
[2020-02-11 16:23:27.000915] DEBUG: gui.contextMenu: registering context menu class DroneSplitStack
[2020-02-11 16:23:27.001915] DEBUG: gui.contextMenu: registering context menu class ChangeItemToVariation
[2020-02-11 16:23:27.001915] DEBUG: gui.contextMenu: registering context menu class ChangeModuleMutation
[2020-02-11 16:23:27.001915] DEBUG: gui.contextMenu: registering context menu class FillWithModule
[2020-02-11 16:23:27.050926] DEBUG: gui.contextMenu: registering context menu class ExportMutatedModule
[2020-02-11 16:23:27.051926] DEBUG: gui.contextMenu: registering context menu class ChangeAffectingSkills
[2020-02-11 16:23:27.051926] DEBUG: gui.contextMenu: registering context menu class FillWithItem
[2020-02-11 16:23:27.051926] DEBUG: gui.contextMenu: registering context menu class DroneAddStack
[2020-02-11 16:23:27.052927] DEBUG: gui.contextMenu: registering context menu class AddToCargo
[2020-02-11 16:23:27.052927] DEBUG: gui.contextMenu: registering context menu class AddToCargoAmmo
[2020-02-11 16:23:27.052927] DEBUG: gui.contextMenu: registering context menu class ProjectItem
[2020-02-11 16:23:27.052927] DEBUG: gui.contextMenu: registering context menu class AmmoToDmgPattern
[2020-02-11 16:23:27.053927] DEBUG: gui.contextMenu: registering context menu class ImplantSetApply
[2020-02-11 16:23:27.053927] DEBUG: gui.contextMenu: registering context menu class ImplantSetSave
[2020-02-11 16:23:27.054928] DEBUG: gui.contextMenu: registering context menu class DronesPrice
[2020-02-11 16:23:27.054928] DEBUG: gui.contextMenu: registering context menu class CargoPrice
[2020-02-11 16:23:27.054928] DEBUG: gui.contextMenu: registering context menu class ImplantBoosterPrice
[2020-02-11 16:23:27.054928] DEBUG: gui.contextMenu: registering context menu class ChangeDamagePattern
[2020-02-11 16:23:27.054928] DEBUG: gui.contextMenu: registering context menu class FactorReload
[2020-02-11 16:23:27.055927] DEBUG: gui.contextMenu: registering context menu class TargetProfileSwitcher
[2020-02-11 16:23:27.055927] DEBUG: gui.contextMenu: registering context menu class GraphDmgApplyProjectedMenu
[2020-02-11 16:23:27.055927] DEBUG: gui.contextMenu: registering context menu class GraphDmgIgnoreResistsMenu
[2020-02-11 16:23:27.055927] DEBUG: gui.contextMenu: registering context menu class GraphIgnoreLockRangeMenu
[2020-02-11 16:23:27.056927] DEBUG: gui.contextMenu: registering context menu class GraphIgnoreDcrMenu
[2020-02-11 16:23:27.056927] DEBUG: gui.contextMenu: registering context menu class GraphDmgDroneModeMenu
[2020-02-11 16:23:27.056927] DEBUG: gui.contextMenu: registering context menu class AdditionsExportAll
[2020-02-11 16:23:27.057928] DEBUG: gui.contextMenu: registering context menu class AdditionsExportAll
[2020-02-11 16:23:27.057928] DEBUG: gui.contextMenu: registering context menu class AdditionsImport
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: resources
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: resistances
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: recharge
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: firepower
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: outgoing
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: capacitor
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting minimal view for: targetingMisc
[2020-02-11 16:23:27.104938] DEBUG: gui.statsPane: Setting full view for: price
[2020-02-11 16:23:27.152949] DEBUG: gui.mainFrame: Done loading mainframe imports
[2020-02-11 16:23:27.156950] DEBUG: gui.mainFrame: Initialize MainFrame
[2020-02-11 16:23:27.169953] CRITICAL: gui.errorDialog: 

Traceback (most recent call last):
  File "pyfa.py", line 143, in <module>
  File "gui\mainFrame.py", line 172, in __init__
  File "gui\additionsPane.py", line 56, in __init__
  File "gui\bitmap_loader.py", line 83, in getImage
  File "gui\bitmap_loader.py", line 74, in getBitmap
  File "gui\bitmap_loader.py", line 100, in loadBitmap
  File "gui\bitmap_loader.py", line 125, in loadScaledBitmap
  File "gui\bitmap_loader.py", line 145, in loadImage
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

**Comment by DarkFenX** [comment] 2020-02-11 16:48
What are your regional settings? Make screenshots of all tabs (preferably legacy CP if you have option to use that).

**Comment by Thoreas** [comment] 2020-02-11 16:54
These are the only two tabs available in the legacy CP:

![image](https://user-images.githubusercontent.com/44213940/74258898-52529b80-4cf7-11ea-9941-25a404671f86.png)

![image](https://user-images.githubusercontent.com/44213940/74259042-86c65780-4cf7-11ea-9048-a28828e89ffb.png)

Clicking "Language preferences" on the "Formats" tab opens the new settings app:

![image](https://user-images.githubusercontent.com/44213940/74258798-318a4600-4cf7-11ea-8be8-529e292daa60.png)

![image](https://user-images.githubusercontent.com/44213940/74258837-3b13ae00-4cf7-11ea-8fc6-3c3dcab1d38f.png)

**Comment by DarkFenX** [comment] 2020-02-11 16:59
Thanks. Will take a look when i get to my win10 machine.

**Comment by DarkFenX** [comment] 2020-02-11 18:29
"Format: Europe" setting seems to be the cause of that, and some bug in wxwidgets connected to it. The issue is remotely similar to #2128. Did you experience it in 2.16.2 and 2.16.3 as well, or is it new for 2.17.0?

As temporary workaround - set it to US. I will see if it can be fixed in pyfa code, and if it cannot - will check if reverting to wxpython 4.0.6 will help.

**Comment by Thoreas** [comment] 2020-02-11 19:24
Version 2.17.0 was the first where this error started happening. Pyfa 2.16.3 (or whichever was the last latest version) and every version before it worked perfectly.

**Comment by Thoreas** [comment] 2020-02-11 21:53
> As temporary workaround - set it to US.

This fixes it (Pyfa starts and functiones as expected).

**Comment by Sutima** [comment] 2020-02-12 08:10
> As temporary workaround - set it to US.

This worked for me as well.

**Comment by DarkFenX** [comment] 2020-02-12 15:19
Filed an upstream issue: https://github.com/wxWidgets/Phoenix/issues/1515

Will try reverting to 4.0.6 and seeing if it helps

**Comment by DarkFenX** [comment] 2020-02-13 09:15
Worked around it in 61a01805cc28d2c1e17d8c76a05f58ec5ba11102

**Closed by DarkFenX** 2020-02-13 09:15 UTC
Labels: bug, upstream
