### ISSUE TITLE
Error on Settings

### ISSUE THREAD

**Issue by MadameSolette** [pyfa-org/Pyfa#2284] opened 2020-11-04 19:37 UTC
Can't open settings, but here the error log message:

pyfa v2.30.0
EVE Data Version: 1832008 (2020-10-27 09:28:42)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 486, in OnShowPreferenceDialog
  File "gui\preferenceDialog.py", line 68, in __init__
  File "gui\builtinPreferenceViews\pyfaGeneralPreferences.py", line 59, in populatePanel
ValueError: None is not in list

## Detailed steps to reproduce:
Started pyfa after unpacking the pyfa-v2.30.0-win.zip file in the existing folder.

## Release or development git branch? Please note the release version or commit hash:
pyfa-v2.30.0-win.zip

## Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by MadameSolette** [comment] 2020-11-14 06:33
Same Error in Pyfa v2.31.0:

pyfa v2.31.0
EVE Data Version: 1842315 (2020-11-10 09:18:18)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 486, in OnShowPreferenceDialog
  File "gui\preferenceDialog.py", line 68, in __init__
  File "gui\builtinPreferenceViews\pyfaGeneralPreferences.py", line 59, in populatePanel
ValueError: None is not in list

**Comment by AlexLeninEve** [comment] 2020-11-17 17:28
Same in v2.31.0,  even after clear install or unpacking zip

pyfa v2.31.0
EVE Data Version: 1842315 (2020-11-10 11:18:18)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 486, in OnShowPreferenceDialog
  File "gui\preferenceDialog.py", line 68, in __init__
  File "gui\builtinPreferenceViews\pyfaGeneralPreferences.py", line 59, in populatePanel
ValueError: None is not in list

**Comment by DarkFenX** [comment] 2020-11-19 09:47
This happens because pyfa cannot find localizations. Since they are essential part of the package now, I won't add any workarounds for the case when pyfa cannot find them, but would rather look into root issue, which is, why is pyfa not finding localization files?

I will try to reproduce it myself a bit later, but I need some info from you:

1) Do you launch pyfa with any extra arguments/parameters?
2) Do you put unpacked pyfa to some UAC-protected folder, such as program files?

**Comment by DarkFenX** [comment] 2020-11-19 11:36
I tried to download 2.31.0 to my win10 machine, and both exe and zip (unpacked to my downloads folder) worked fine. Need more info on this one to reproduce and do anything.

**Comment by MadameSolette** [comment] 2020-11-19 22:45
> I will try to reproduce it myself a bit later, but most likely I need some extra info from you:
> 
> 1. Do you launch pyfa with any extra arguments/parameters?
> 2. Which distribution do you use, exe or zip? If zip, do you put unpacked pyfa to some UAC-protected folder, such as program files?

The infos you have asked:

1. No, starting the .exe after unpacking the .zip file.
2. Only unpack the .zip in the existing folder and run the .exe. The existing folder is on a external HDD and its not a UAC-protected folder. Its the same folder i unpack every new releases. That error was not before and starts with the 2.30.0 release.

**Comment by DarkFenX** [comment] 2020-11-20 07:15
Open `pyfa\locale` folder, and traverse through its child folders. All of them will have `LC_MESSAGES` folder, which will contain `lang.po` and `lang.mo`.

Your issue indicates that wx cannot load `.mo` files, so first step would be to determine if those files are present.

Also, try moving it to local HDD (say, drive C:\) temporarily and see if it helps, could be that wxPython fails to load these from external HDD.

**Comment by MadameSolette** [comment] 2020-11-20 11:41
> Your issue indicates that wx cannot load `.mo` files, so first step would be to determine if those files are present.
> 
> Also, try moving it to local HDD (say, drive C:) temporarily and see if it helps, could be that wxPython fails to load these from external HDD.

Have checked and try some things:

The `lang.po` & `lang.mo` files in the child folders of the `LC_MESSAGES` folder are all present.
Have moved my pyfa folder to two diffrent (C:\ & C:\Users\x.X.x\Programme) places to my local HDD, nothing changed, same Error.
Have try to install pyfa with the pyfa-v2.31.0-win.**exe** installer, nothing changed, same error.
Have try to install pyfa with the pyfa-v2.31.**1dev1**-win.exe installer, nothing changed, same error.
Have unpack the pyfa-v2.31.1dev1-win.zip file to diffrent places (intern & extern HDD), nothing changed, same error.

Finaly, have doublecheck the **v2.29.0** release again, **no error**.

**Comment by DarkFenX** [comment] 2020-11-24 09:56
Do you have any kind of anti-virus software running? Can't imagine what could interfere with that.

I will try to add extra debug logging for next release. With the data I have it is hard to understand what's the issue.

**Comment by MadameSolette** [comment] 2020-11-24 11:08
No, haven't any extra antivirus software running on my machine.

**Comment by DarkFenX** [comment] 2020-11-24 12:08
https://github.com/pyfa-org/Pyfa/releases/tag/v2.32.0
Please try this build. If it still fails - share log files from the `<user>\.pyfa\` folder.

**Comment by MadameSolette** [comment] 2020-11-24 12:32
Its fixed, Settings are now okay ♥

Note:
Before i start v2.32.0 release ive delet the .pyfa folder.

**Comment by DarkFenX** [comment] 2020-11-24 12:44
Well, the truth is that i did not change a thing to fix, just added some logging to debug it. No idea what helped, but what's fixed is fixed.

**Closed by DarkFenX** 2020-11-24 12:44 UTC
