### ISSUE TITLE
Adding Command Bursts / Guns / Command Processors onto a Loki causes Pyfa to eventually bug out.

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#902] opened 2016-12-13 10:36 UTC
I was playing around with a Cloaky Loki for this one.

Steps to reproduce:

- Start with this base fit:

[Loki, Command_Base]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Covert Ops Cloaking Device II
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Loki Engineering - Power Core Multiplier
Loki Defensive - Warfare Processor
Loki Offensive - Covert Reconfiguration
Loki Propulsion - Interdiction Nullifier
Loki Electronics - Dissolution Sequencer

- Add 2 x Shield Command Bursts with Shield Harmonising ammo (try onlining / offlining each of them at the same time etc)
- Sometimes above doesn't trigger it, if so, add 425mm Autocannons into the high slots
- Or, add a Medium Command Processor...
- Pyfa either adds the module, or doesn't seem to do anything
- But if you move the "empty" slots around the modules then appear
- Either way, Pyfa isn't happy though... and if you move to another tab / reload the fit above it'll show a blank screen
- Can't seem to delete the fits off Pyfa now either...

Not sure if it's true with all T3 / other Command Burst ships as well.

Cheers,

G.

**Comment by blitzmann** [comment] 2016-12-13 15:09
Can you post the contents of `%userprofile%\.pyfa\log.txt`. I doubt anything will be in there, but worth a shot.

**Comment by blitzmann** [comment] 2016-12-13 15:10
Also, you can send me the saveddata.db from that same `.pyfa` directory - email is in readme. If you do this, let me know which fit is causing the issues (can't load, can't delete, etc)...

**Comment by Ebag333** [comment] 2016-12-13 17:13
Cannot replicate against `pyfa-org\master`.  Definitely get @blitzmann the database, it's most likely something local to you.

**Comment by GKFC** [comment] 2016-12-13 20:50
Thanks for the responses all.

blitzmann I've sent both of these through to you.

On Mac OS 10.10.5 btw.

**Comment by GKFC** [comment] 2016-12-13 23:06
OK, even with just the subsystems, cloak, and shield bursts (with charges) I can get this behaviour by trying to enable the shield bursts at the same time too.

Try this fit:

[Loki, Command_Base]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Covert Ops Cloaking Device II
Shield Command Burst II, Shield Harmonizing Charge
Shield Command Burst II, Shield Harmonizing Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Loki Engineering - Power Core Multiplier
Loki Defensive - Warfare Processor
Loki Offensive - Covert Reconfiguration
Loki Propulsion - Interdiction Nullifier
Loki Electronics - Dissolution Sequencer

Then click **once** on the Circle next to the Burst module that isn't enabled.  In my Pyfa this causes the fit to "crash" and closing the fit / reopening shows a blank screen.

Might have something to do with onlining multiple command bursts or something?

Character is All 5... if that makes any difference...

**Comment by blitzmann** [comment] 2016-12-13 23:55
Will take a look asap, thx

**Comment by blitzmann** [comment] 2016-12-14 03:43
> Then click once on the Circle next to the Burst module that isn't enabled. In my Pyfa this causes the fit to "crash" and closing the fit / reopening shows a blank screen.

I can't reproduce with any of your loki fits or examples. ;_;

**Comment by blitzmann** [comment] 2016-12-14 03:44
Ah wait... I can reproduce with the release files. But running from source is fine.

Will investigate further

**Comment by blitzmann** [comment] 2016-12-14 03:50
Ah, this is why... was already fixed with 0ba88d081ac472dd3d0d993de9f260ed3673ce4a

I'll be doing a release in the next few days with some more fixes, including this one. =)

**Comment by GKFC** [comment] 2016-12-14 07:02
Perfect, thanks  :-)

**Closed** 2016-12-18 13:03 UTC
Labels: bug, fixed
