### ISSUE TITLE
Imported fits do not validate if modules fits

### ISSUE THREAD

**Issue by ALERTua** [pyfa-org/Pyfa#512] opened 2016-01-26 15:08 UTC
pyfa 1.18.0 allows importing a fitting with 2 Medium Ancillary Armor Repairers fitted, ignoring "Max Modules Of This Group Allowed" = "1".

**Comment by blitzmann** [comment] 2016-01-26 15:43
Cannot reproduce. Please double check. If it's still the case with you, then provide fitting and screenshot.

Please note that you may be able to achieve this if you import a fit with two AAR's, as I don't believe pyfa checks these things during importing. So if you imported the fit originally, this may be why.

**Comment by ALERTua** [comment] 2016-01-26 15:45
you are right. this was an imported fit. editing ticket. thank you

**Comment by blitzmann** [comment] 2016-01-26 16:42
Changed the title to something a little more relevant to the problem. I will look into validating modules when importing.

Also, can you post the fit that you imported? I'm assuming it's EFT formatted...

**Comment by ALERTua** [comment] 2016-01-26 16:49
[Deimos, Deimos Nahkampf (EVEMon)]

Medium Ancillary Armor Repairer, Nanite Repair Paste
Armor Explosive Hardener II
Damage Control II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Medium Ancillary Armor Repairer, Nanite Repair Paste

Stasis Webifier II
Warp Scrambler II
50MN Microwarpdrive II
Medium Capacitor Booster II, Navy Cap Booster 400

Heavy Neutron Blaster II, Void M
Heavy Neutron Blaster II, Void M
Heavy Neutron Blaster II, Void M
Heavy Neutron Blaster II, Void M
Heavy Neutron Blaster II, Void M

Medium Ancillary Current Router I
Medium Auxiliary Nano Pump I


Hammerhead II x5

**Comment by blitzmann** [comment] 2016-03-19 03:56
Fixed with #538

**Closed** 2016-05-01 00:11 UTC
Labels: fixed
