### ISSUE TITLE
Cap batteries decreases capacitor lasting time on Legion

### ISSUE THREAD

**Issue by OwenTraquemort** [pyfa-org/Pyfa#1248] opened 2017-07-12 19:25 UTC
## Bug Report
Adding Cap Battery decreases the capacitor lasting time on a Legion.

### Expected behavior:
The capacitor lasting time should increase or become more cap stable.

### Detailed steps to reproduce:
Tried this with several types of batteries (small, medium). They all decrease the capacitor lasting time in some amount.
With the fit I am going to link below:
- Using a medium cap battery II -> Capacitor goes from 51.1% to 6m0s
- Using a small cap battery II -> Capacitor goes from 51.1% to 3m12s
- Using both:  Capacitor goes from 51.1% to 2m51s

Checking on a Stratios the behavior is as expected and the capacitor lasting time goes up.

Importing the Legion fit in EVE and playing around in the ghost fitting tool shows that with cap batteries the capacitor lasting time goes up.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Legion, Legion Nullsec Loot Hauler]

Medium Ancillary Armor Repairer, Nanite Repair Paste
Medium Armor Repairer II
Inertial Stabilizers II
Inertial Stabilizers II
Inertial Stabilizers II

50MN Microwarpdrive II
Medium Cap Battery II
Small Cap Battery II

Covert Ops Cloaking Device II
Sisters Expanded Probe Launcher, Sisters Combat Scanner Probe
Medium Energy Nosferatu II
Medium Energy Nosferatu II
Medium Energy Nosferatu II
Medium Energy Nosferatu II
Medium Energy Nosferatu II
Medium Energy Neutralizer II

Medium Hyperspatial Velocity Optimizer II
Medium Hyperspatial Velocity Optimizer II
Medium Hyperspatial Velocity Optimizer II

Legion Core - Energy Parasitic Complex
Legion Defensive - Covert Reconfiguration
Legion Offensive - Assault Optimization
Legion Propulsion - Interdiction Nullifier

Vespa EC-600 x5

Nanite Repair Paste x1000
Sisters Core Scanner Probe x16

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.30.0 Stable YC119.7 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10
![medium](https://user-images.githubusercontent.com/30127432/28136014-90ca7578-6748-11e7-9d00-1a253ee7e6a5.png)
![small](https://user-images.githubusercontent.com/30127432/28136015-90ca7bd6-6748-11e7-8314-a4e9aae23f80.png)
![both](https://user-images.githubusercontent.com/30127432/28136016-90ccd2dc-6748-11e7-8d6a-e051da3cf0ca.png)

**Comment by blitzmann** [comment] 2017-07-16 01:38
Seems to be a duplicate of #1144, I'll try to take a look at that in the near future :)

**Closed** 2017-07-16 02:14 UTC
Labels: duplicate
