### ISSUE TITLE
Program halted refreshing left pane

### ISSUE THREAD

**Issue by wardhowe** [pyfa-org/Pyfa#1723] opened 2018-08-30 07:50 UTC
## Bug Report

I hit a bunch of errors and an assertion by backing out of the current hull and then going back in.

### Expected behavior:

Smooth flying

### Actual behavior:

Primary symptom was that the list of fits only loaded part-way in the left pane and the program didn't respond to further input. Then I noticed if I put my mouse around the middle of the window, it changed to a text-selection icon, without any text being visible, so I clicked and pressed Ctrl+A, Ctrl+C to see what juicy details might be in this hidden text - a bunch of errors. After that a dialog came up about an assertion failure.

### Detailed steps to reproduce:

Unknown exactly. Roughly...

1. Open 3 fits in different tabs and close all these tabs
2. Cruiser -> Moa -> duplicate a fit and name it
3. Open new fit, modify, change single tab view back and forth to old fit
4. (I wanted it to get the list sorted alphabetically) "Back" button to go to Cruiser -> Moa again

### Fits involved in EFT format (Edit > To Clipboard > EFT):

A list of 17 Moa fits. I think this one was open at the time:

[Moa, Moa abyss exotic 2lasb cheap]

Magnetic Field Stabilizer II
Damage Control II
Fourier Compact Tracking Enhancer
Magnetic Field Stabilizer II

Large Ancillary Shield Booster, Navy Cap Booster 150
Tracking Computer II
Large Ancillary Shield Booster, Navy Cap Booster 150
10MN Y-S8 Compact Afterburner
Shield Boost Amplifier II

Anode Ion Particle Cannon I, Caldari Navy Antimatter Charge M
Anode Ion Particle Cannon I, Caldari Navy Antimatter Charge M
Anode Ion Particle Cannon I, Caldari Navy Antimatter Charge M
Anode Ion Particle Cannon I, Caldari Navy Antimatter Charge M
Anode Ion Particle Cannon I, Caldari Navy Antimatter Charge M

Medium Anti-EM Screen Reinforcer I
Medium Processor Overclocking Unit I
Medium Anti-Thermal Screen Reinforcer I

Hornet II x3

Iron Charge M x500
Lead Charge M x500
Caldari Navy Antimatter Charge M x1200
Nanite Repair Paste x40
Optimal Range Script x1
Tracking Speed Script x1
Navy Cap Booster 150 x58

### Release or development git branch? Please note the release version or commit hash:

Release 2.4.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

Attached the errors from the hidden dialog and the text transcribed from the assertion dialog.
[assertdialog.txt](https://github.com/pyfa-org/Pyfa/files/2335148/assertdialog.txt)
[hiddendialog.txt](https://github.com/pyfa-org/Pyfa/files/2335149/hiddendialog.txt)

---

```
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 88, in SortCompareCols
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 134, in PopulateList
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 287, in OnPaint
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 289, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 502, in DrawItem
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 290, in OnPaint
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 235, in Render
wx._core.wxAssertionError: C++ assertion "dataDst && dataSrc" failed at ..\..\src\msw\dc.cpp(2832) in wxAlphaBlend(): failed to get raw data in wxAlphaBlend
```

```
..\..\src\common\dcbufcmn.cpp(132): assert "m_buffer &&m_buffer->IsOk()" failed in wxBufferedIDC::Unmask(): invalid backing store
Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.

Yes | No | Cancel
```

**Comment by blitzmann** [comment] 2018-09-01 21:47
That... is so weird.

Seems it's a bunch of GUI errors, about having an invalid bitmap to draw with (the ship browser uses a custom-drawn widget).

I can't reproduce either. Have you run into this issue since? Sometime these kind of issues come along that are super hard to debug since they are hard to reproduce, usually have very specific reproduction steps.

**Comment by blitzmann** [comment] 2018-09-12 23:55
@wardhowe has this happened again since the initial bug report? Can you reproduce?

**Comment by blitzmann** [comment] 2018-10-12 03:13
Going to close this due to lack of information - I'm assuming this was a one time fluke, and a restart of pyfa fixed it. Please feel free to open a new issue if it happens again... :)

**Closed by blitzmann** 2018-10-12 03:13 UTC
