### ISSUE TITLE
error window requesting to be reported

### ISSUE THREAD

**Issue by WargamingR** [pyfa-org/Pyfa#2567] opened 2024-01-03 18:05 UTC
## Bug Report
Searching for a fitting; after 3 letters "lok" (searching for "Loki") a Pyfa Error window popped up and asked to be reported.

pyfa v2.57.3
EVE Data Version: 2443636 (2023-12-05 11:37:07)

OS version: macOS-10.16-x86_64-i386-64bit
Python version: 3.11.0 (main, Dec  8 2022, 16:43:53) [Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

####################

Traceback (most recent call last):
  File "gui/builtinShipBrowser/sfBrowserItem.py", line 291, in OnPaint
  File "gui/builtinShipBrowser/shipItem.py", line 241, in DrawItem
  File "gui/builtinShipBrowser/shipItem.py", line 206, in UpdateElementsPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

### Expected behavior:
List of fits to be displayed

### Actual behavior:
Error message window pop up displayed.

### Detailed steps to reproduce:
In the fittings search bar, typed "lok" then the error window popped up.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Release or development git branch? Please note the release version or commit hash:
Release version 2.57.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
MacOS 14.2.1

### Other relevant information:
Restarting PYFA and the issue did not happen when I tried to search again.

**Comment by DarkFenX** [comment] 2024-02-20 17:33
I couldn't reproduce iit as well. `self.shipBmp` which is used there is supposed to be always loaded, if not with proper image itself, then fallback image. I am closing this one, reopen if it persists.

**Closed by DarkFenX** 2024-02-20 17:33 UTC
