### ISSUE TITLE
[Tengu Defensive - Covert Reconfiguration] wrong cargo bonus

### ISSUE THREAD

**Issue by KawaiDesu** [pyfa-org/Pyfa#1249] opened 2017-07-12 20:07 UTC
## Bug Report
Tengu Defensive - Covert Reconfiguration adds 300 m^3 cargo instead of 30 m^3.

### Actual behavior:
With Covert Reconfiguration cargo size should become 490 m^3 (tested in game).

### Operating system and version:
Latest stable, Windows 8.1 - 1.30.0

**Comment by minlexx** [comment] 2017-07-13 16:50
Duplicate of issue #1246  ❔

**Comment by KawaiDesu** [comment] 2017-07-13 17:00
@minlexx Hmm, looks like yes.

**Comment by blitzmann** [comment] 2017-07-16 01:42
Yep, it's a duplicate, and is seemingly a bug on CCPs side. Here's my note about this during the upgrade:

> defensive legion covert states 30m3 for cargo, effect does 300, same with tengu and proteus and loki

Meant to send this into CCP as a bug report, will do that now. Closing issue as duplicate of #1246

**Closed** 2017-07-16 02:14 UTC
Labels: duplicate
