### ISSUE TITLE
Error and traceback when using Backup All Fittings

### ISSUE THREAD

**Issue by lucjoy** [pyfa-org/Pyfa#2594] opened 2024-02-26 01:00 UTC
## Bug Report

I attempted to save a backup of my fits. I clicked the backup button and was prompted to save an .XML file. I chose the folder, added my character name to the default file name, and clicked OK.

### Expected behavior:

The backup file is saved to the specified location and I am returned to the pyfa user interface.

### Actual behavior:

The file was successfully save to the specified locations (I've opened it in a text editor and it looks complete and correct), but I also received this traceback:

pyfa v2.58.0
EVE Data Version: 2497879 (2024-02-20 07:05:56)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 884, in backupToXml
wx._core.wxAssertionError: C++ assertion ""IsRunning()"" failed at ..\..\src\common\evtloopcmn.cpp(92) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop

After I closed the traceback pop-up window, I was returned to the pyfa user interface. The program appeared to be operating normally, but I closed it and reopened it anyway. The latest fits I was working on are all looking fine.

### Detailed steps to reproduce:

Go to File->Backup All Fittings
 -- The Save Backup As window opens
Choose a location to save the backup file (XML), and set the file name to bbb.xml
Click the Save button
  -- A pyfa error window opens with the traceback message in it.

### Release or development git branch? Please note the release version or commit hash:

Version 2.58.0
Eve data version: 2497879 (2024-02-20 07:05:56)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 with all the latest updates from Microsoft.

### Other relevant information:

![image](https://github.com/pyfa-org/Pyfa/assets/26280694/cb741edc-e024-42fc-8026-bddcb8c25753)

**Comment by DarkFenX** [comment] 2024-02-26 01:19
Duplicate of #2552. I am working on it. Fixed export to HTML already, need to fix backup all fittings & import from file still.

**Closed by DarkFenX** 2024-02-26 01:19 UTC
