### ISSUE TITLE
Heavy Water Consumption - Orca with Large Industrial Core

### ISSUE THREAD

**Issue by Sanitel** [pyfa-org/Pyfa#2389] opened 2021-12-14 13:16 UTC
## Bug Report
The Hull Traits of the Orca "-5% Fuel reduction for Industrial Core per skill level Industrial Command ship" doesn't get included in the attribute calculation of the Indi cores.

### Expected behavior:
The consumption rate for the T1 Large Industrial Core with maxed skills should be around 112.5 Units per cycle.

### Actual behavior:
In the attribute window in Pyfa with "All 5" skills the consumption per cycle is 150 Units. Thats everything included from "Industrial Reconfiguration" but not the Orca traits.

### Detailed steps to reproduce:
Make a blank Orca with only the T1 Large Industrial Core and Skills at "All 5". 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Orca, T1 Core]

[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Large Industrial Core I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
v2.39.1

**Comment by sanaluria** [comment] 2022-01-17 03:58
i see the same issue with the rorqual, doesnt show proper values for capital indy core 1 and 2, also cant see the capital indy ship skill wean right clicking in module slot window

**Comment by DarkFenX** [comment] 2022-02-04 22:50
CCP initially released expansion with multiple bugs in the data, like rorqual core using subcapital skill (or vice versa). They fixed that later, but we haven't updated the data. I will check that it works as intended before next release

**Comment by DarkFenX** [comment] 2022-02-05 01:58
Fixed in 8cbe094ee6a8744d11cc948e7980ee77e0cdd12e

**Closed** 2022-02-09 20:49 UTC
Labels: bug, fixed
