### ISSUE TITLE
Suggestion: Drag and Drop Implants

### ISSUE THREAD

**Issue by droppedoncaprica** [pyfa-org/Pyfa#370] opened 2015-09-28 15:22 UTC
It would be pretty neat if you could drag a set of implants from the items and drop them into the fitting window or implant pane and have them be set / replace whatever is there.

Example: Say I want to see how a Rattlesnake will tank with different grade Crystal sets.  It would be handy if I could search for High-Grade Crystal, select the entire set, then drop them into the fit instead of double clicking each implant in a row.  Then if I wanted to compare the tank compared to mid grades, searching and dragging them all in at once, replacing the currently set implants would save a lot of time and clicking.

**Comment by droppedoncaprica** [comment] 2015-09-28 20:16
And feel free to let me know if this is especially difficult.  If it's something that should be fairly easy, let me know and I'll take a look at adding it.  

I might need a couple references on where to look, as I'm not really worked with Python / WX before.  WIth a couple examples, I can probably figure it out though.

**Comment by blitzmann** [comment] 2015-10-04 16:04
The problem with this is that when we drag stuff we only drag the first selected object. Whether or not this can be changed easily I don't know.

A little background in how dragging works in pyfa: when we drag something, we store a string of information in the drag that dictates the source and a unique identifier of the item. The target window notices this drag, and based on the information decides what to do with it.

For example, we drag a module from the fitting window to the cargo. The drag string is `fitting:itemID`. The cargo window separates this and sees that we are dragging from the fitting window, and so if we drag onto a cargo item, we can swap the items from cargo into the fitting. If the source is `market`, then we simply add the module to the cargo. 

A good place to start would be `marketBrowser.ItemView.startDrag()`. This is where it stores the source and itemID when dragging from the market. If you look at the booster and cargo GUI files, you will see a class called `BoosterViewDrop` or `CargoViewDrop`, and then in the `__init__` a line that looks like this: `self.SetDropTarget(BoosterViewDrop(self.handleListDrag))`. This basically says that when we are dragging something to this window, use `BoosterViewDrop` to process the data and `self.handleListDrag` to handle that data. It is in `self.handleListDrag` where you would add implants or cargo or boosters, etc. 

You would need to make an `ImplantDropTarget` in the implant GUI and make a handler for it. But again, we only handle the first select object for now. To change this you would have to modify the data structure that is set in `startDrag()` to include all selected modules, and then if needed modify any target sources to account for this change.

I may or may not be easy, but have a go at it. If it's too much, let me know and I can take a look at it, but I won't promise anything =)

**Comment by droppedoncaprica** [comment] 2015-10-05 17:30
Thanks for the detailed writeup, this was a pretty nice outline of what happens when you drag and drop items. 

I'll poke at it and see what progress I can make here and let you know.

**Comment by blitzmann** [comment] 2016-06-16 02:39
I'm going to close this particular issue because I think the issue is now mitigated somewhat with the implementation of character implants and implant sets. :)

**Closed by blitzmann** 2016-06-16 02:39 UTC

**Comment by droppedoncaprica** [comment] 2016-06-16 19:36
Yeah, it really does.  Sorry, I should have closed this earlier!
