### ISSUE TITLE
Abyssal cap batteries visually show warfare resistance bonuses as penalties

### ISSUE THREAD

**Issue by ArtificialQualia** [pyfa-org/Pyfa#1820] opened 2018-12-12 15:51 UTC
### Expected behavior:

Abyssal cap batteries visually display a bonus to 'Capacitor Warfare Resistance Bonus' as green, and a penalty as red, like the in-game version displays.

### Actual behavior:

Abyssal cap batteries visually display a bonus (green and bar moving to the right) as a penalty (red and moving to the left) and vice-versa for the 'Capacitor Warfare Resistance Bonus' attribute

### Detailed steps to reproduce:

Apply mutaplasmid to a cap battery and change 'Capacitor Warfare Resistance Bonus' value

### Fits involved in EFT format (Edit > To Clipboard > EFT):

EFT format does not export abyssal mods

### Release or development git branch? Please note the release version or commit hash:

Release v2.6.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Win 10

### Other relevant information:

Seems to apply to all cap batteries, but other mods with negative value attributes (like webs) do indicate bonuses/penalties correctly

**Comment by burnsypet** [comment] 2018-12-12 16:07
Hey, in the DB it looks like energyWarfareResistanceBonus has highIsGood = false. 

This sounds incorrect to me, however it is my (possibly flawed) understanding that the DB is extracted automatically from the game data. It's possible that this column was worked out manually and this was set to false by mistake. What do you think @blitzmann ?

**Comment by blitzmann** [comment] 2018-12-12 17:51
Possible duplicate of #1686. I made a bug report ages ago, and it looked like CCP "fixed" it, but I think the fix was incorrect. I'll try to poke a dev about this again, and bump my bug report

**Comment by blitzmann** [comment] 2018-12-12 18:07
as a fix for us in the short term, can manually adjust this attribute on db compile time

**Comment by DarkFenX** [comment] 2018-12-13 13:15
HighIsGood is set to 0 for energyWarfareResistanceBonus, which means the lower it is - the better (which is true), so issue seems to be on pyfa side - it doesn't work great with negative values.

**Comment by DarkFenX** [comment] 2018-12-13 15:13
Should be fixed in b8f53f9bb3ea59849b65a540a6e1e397f1f618d0.

I changed behavior a little, hopefully it is intuitive enough. I based all the logic on limitation imposed onto us by wx: when you scroll up in spinbox, it always increases value (that is, we cannot decrease its value when scrolling up if highIsGood=False, roughly speaking).

So, in range of available values (above roll bar), I'm putting min value to the left side and max value to the right, coloring them as good and bad accordingly.

Hopefully this behavior is acceptable, please check it out.

**Comment by DarkFenX** [comment] 2018-12-13 16:39
Nevermind, found a way to decrease value when scrolling up.

![image](https://user-images.githubusercontent.com/275209/49953233-b371ba00-ff0e-11e8-9e7a-48bb5fbc9203.png)

Now scroll up = make value better, scroll down = make it worse.

**Comment by blitzmann** [comment] 2018-12-13 19:49
Nice catch, I didn't actually check to see if the high is good attribute was actually fixed. All the changes done see m to work really well, kudos!

**Closed** 2018-12-20 02:40 UTC
Labels: bug, fixed, logged
