### ISSUE TITLE
Can't create new character

### ISSUE THREAD

**Issue by tmockler69** [pyfa-org/Pyfa#917] opened 2016-12-21 20:54 UTC
On ver 1.26.0, every time I attempt to add a new character, nothing happens.

I enter the character name, and click OK, the dialog box disappears, but the character is not added to the list.

Am I doing something wrong?

**Comment by Ebag333** [comment] 2016-12-21 20:57
Probably not.  Can you upload your user database somewhere and email me a link? ebagola@gmail.com

**Comment by tmockler69** [comment] 2016-12-21 21:02
It's a brand new installation....I'm guessing the user database is empty.

What folder would I find the file you need?

**Comment by Ebag333** [comment] 2016-12-21 21:05
So brand new, never used before?

Here's how you create chars:
https://puu.sh/sWVeX/ed842b8dda.gif

If that's not working, then something is clearly wrong.  Are you running under Windows, Linux, Mac?

**Comment by tmockler69** [comment] 2016-12-21 21:11
Yeah, something is clearly wrong.  As I said before, I click on the new character button, enter the name, click OK, the dialog box disappears, but the new name is not added to the list.

I'm running Windows 10

**Comment by Ebag333** [comment] 2016-12-21 21:28
Try opening the folder you installed Pyfa into, right click, `Run as Administrator`.  See if that makes a difference.

If that doesn't, create a shortcut for the EXE, and add this to the shortcut (under right click, properties):
`-debug`

That should output some information to `c:\Users\<YourUsername>\.pyfa` (which is also where your user database goes).

**Comment by tmockler69** [comment] 2016-12-21 21:51
Run as Adminstrator does not make a difference.

Tried to add -debug to the command line on the shortcut and received the following dialog:

![capture](https://cloud.githubusercontent.com/assets/17017122/21407246/8244c0a8-c79d-11e6-96f3-c7c1b08acf69.JPG)

**Comment by Ebag333** [comment] 2016-12-21 21:52
Can you try it with `-debug` outside of the quotes?

**Comment by blitzmann** [comment] 2016-12-21 21:52
BTW It's `-d`, or `--debug`

**Comment by tmockler69** [comment] 2016-12-21 21:53
OK....the debug switch is now working

**Comment by blitzmann** [comment] 2016-12-21 21:56
That being said, even if it's a brand new install... there have been times when people "try out" pyfa and then drop it, only to reinstall it months / years later. That user database can persist that long as long as you don't manually clean it up. 

Please send me a copy of `%userprofile%\.pyfa\saveddata.db` to the email in the README. Many times, characters not adding is due to some sort of database corruption.

OR if it truly is a new install, then you don't really care about the database anyway. Delete the database and try to launch pyfa again (I would still like a copy of the database before you nuke it so that I can try to analyze what went wrong and maybe prevent this in the future)

:)

**Comment by blitzmann** [comment] 2016-12-21 23:44
@tmockler69 any news?

**Comment by mrspiderbyte** [comment] 2016-12-27 01:13
Hey, so I was having the same issue, but I have been using pyfa for about 4 months or so. Tried to add a character, and it was doing the same thing. I click new character, then name it, and then hit OK. No errors pop up or anything, the character is just not created. I renamed my db file to back it up, and then restarted the program. With the new file I was able to successfully create a character. So, it seems like the database is corrupted. Any ideas?

**Comment by Ebag333** [comment] 2016-12-27 01:14
Without seeing the DB....no.

Can you get it to me?

**Comment by mrspiderbyte** [comment] 2016-12-27 01:33
Sure, got an email or something where I can send it?

**Comment by Ebag333** [comment] 2016-12-27 01:38
Scroll up, second comment. :)

**Comment by mrspiderbyte** [comment] 2016-12-27 01:45
Heh, not only do I corrupt databases, but I can't read. Thanks!

**Comment by Ebag333** [comment] 2016-12-27 01:49
Yup, DB is well and truly corrupted.  Now to try and figure out why.

`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: characterSkills.characterID, characterSkills.itemID [SQL: u'INSERT INTO "characterSkills" ("characterID", "itemID", "_Skill__level") VALUES (?, ?, ?)'] [parameters: ((8, 2403, None), (8, 2406, None), (8, 2495, None), (8, 2505, None), (8, 3184, None), (8, 3300, None), (8, 3301, None), (8, 3302, None)  ... displaying 10 of 423 total bound parameter sets ...  (8, 41410, None), (8, 41537, None))]`

**Comment by mrspiderbyte** [comment] 2016-12-27 01:55
OK! Hope I was able to help. Any more help I can give ya lemme know.

**Comment by Ebag333** [comment] 2016-12-27 02:01
Okay, so the issue is fairly simple. You created a char previously, and either:
A) It didn't fully create for `reasons`
B) You deleted it, and it didn't get fully cleaned up.

Either way, the records didn't get cleaned up, so now it's trying to create a new char when one already partially exists, so it steps on the ID.

This seems to be an on-going issue for a number of similar things, so it's not something you specifically did.

**Comment by blitzmann** [comment] 2017-01-03 00:33
This should be fixed with a recent pull request (#920). It doesn't solve the root issue, but it should pick up integrity issues and clean them up on startup

**Comment by Perdog** [comment] 2017-01-14 22:43
I'd like to add to this.

This just started happening to me today. I was messing around with adjusting my skills on a fit and couldn't figure out a way to reset them to the skills the toon actually has, so I thought I'd delete the character and re-add it. The problem began AFTER I deleted the character.

No idea if this helps at all, figured I'd give you a little more insight.

**Closed** 2017-02-17 04:44 UTC
Labels: bug, fixed
