### ISSUE TITLE
Attempting to use rigs of incorrect size is being handled improperly

### ISSUE THREAD

**Issue by fonsuiplaysvideogames** [pyfa-org/Pyfa#2400] opened 2022-01-31 04:45 UTC
The image below shows the "charge stats" window for the currently loaded rockets, and shows a bonus from a medium missile damage rig that I dragged on to the fitting. The program is treating it as if the rig is fitted, but the rig does not appear in the fitting screen. This is only reversible by using the undo function.

![image](https://user-images.githubusercontent.com/60384561/151739992-d03f35cd-d837-4aa0-9d81-eb6af1eed4f6.png)

**Comment by blitzmann** [comment] 2022-01-31 20:44
A few things:
* Can you post the EFT format of the fitting?
* Do you have overrides enabled? (if you don't know, then probably not)
* Which version of pyfa?
* Can you send me your saveddata.db file (location can be found in preferences > database) to `holmes.ryan.90@gmail.com` and include in the email the fit that is exhibiting this issue? it could be that, somehow, your fit has a phantom rigs applied to it in the database and is involved with calculations, but isn't showing in the UI. Regardless, if it's reproducible with your database file, I can at least try to pin point where that affected by entry comes from.

**Comment by fonsuiplaysvideogames** [comment] 2022-02-01 02:42
Here's a fresh DB with only a Heron in it, with one launcher and one
turret. I don't know if the DB will contain any errors, it might be
entirely ephemeral and only exist in memory.

**Comment by fonsuiplaysvideogames** [comment] 2022-02-01 02:50
- EFT export does not contain the erroneous items
- Overrides are off and fitting restrictions are on
- Current pyfa release as of now (2.39.2)
- Fresh database created with one single Heron fitting, containing one launcher, one turret, and one erroneous rig for each

Further description of observed behavior:
- Closing and re-opening the fitting without exiting the program results in the error persisting, the rig is still visible on "affected by"
- Exiting the program and re-starting will cause the erroneous 
- Removing and re-adding an affected item (module or charge) will cause the erroneous rig to disappear from the "affected by"
- Issue exhibited on hulls, weapons, rigs of all sizes

**Comment by fonsuiplaysvideogames** [comment] 2022-02-01 02:55
It is also worth noting that only dragging the rig into the fitting results in this issue, double-clicking the rig or using the alt+# hotkey do not result in the rig being applied incorrectly.

**Comment by burnsypet** [comment] 2022-02-03 05:45
This does not appear to be limited to rigs, other modules with fitting restrictions like capital sized plates and shield extenders have the same issue. The phantom module can be removed by forcing an update in the GUI by adding a valid module to a different slot. In this case the GUI is not being refreshed when attempting a replace with an invalid module. 

https://github.com/pyfa-org/Pyfa/blob/b62260cd1f308c550ab3ad878964b094859ee9c6/gui/fitCommands/calc/module/localReplace.py#L47-L52

`self.savedStateCheckChanges = sFit.checkStates(fit, newMod)` is being called before checking if the module is valid and undo-ing the replace operation. This sets `self.savedStateCheckChanges` to a tuple of empty dicts, which prevents `needsGuiRecalc` returning true when it's called after the undo replace operation.

https://github.com/pyfa-org/Pyfa/blob/b62260cd1f308c550ab3ad878964b094859ee9c6/gui/fitCommands/calc/module/localReplace.py#L93-L97

I think the easiest solution to this is just to move `self.savedStateCheckChanges = sFit.checkStates(fit, newMod)` out of the conditional where it is now and move it to the end of the method after all the restrictions checks.

**Comment by blitzmann** [comment] 2022-02-03 20:47
Thanks for looking into it @burnsypet! Haven't had a chance to dig, but this seems like the reasoning behind it. I'll look into the proposed solution tonight

**Comment by blitzmann** [comment] 2022-02-04 01:53
Pushed up a fix for this

**Comment by DarkFenX** [comment] 2022-02-04 20:36
The fix is wrong. The code correctly detected that module does not fit. In case of putting it over previously empty module, it correctly used CalcRemoveLocalModulesCommand. What was missing is recalculation after its execution. I pushed proper fix in 3024ccd176c2a1a1e0f617c9857f03669ea01bf5

**Comment by DarkFenX** [comment] 2022-02-04 20:38
FYI checkStates is something keeping track of side-effect changes. E.g. when projected scram is added, MWD is disabled. It should not carry any extra information, and if there were no side-effect changes, it should be kept as None.

**Closed** 2022-02-09 20:49 UTC
Labels: bug, fixed
