### ISSUE TITLE
Weapon Disruption resistance not applied

### ISSUE THREAD

**Issue by sthartman** [pyfa-org/Pyfa#2030] opened 2019-08-24 01:17 UTC
## Bug Report
Projected and Command effects that should grant weapon resistance, aren't doing so.  The tracking debuffs are applied at full strength.

### Detailed steps to reproduce:
I made a crucifier fit with a tracking disruptor and an info links Damnation.  I then applied the command Damnation to the crucifier, and projected the Crucifier onto a Revelation and an Abbadon.  The Revelation's siege module didn't protect against the disruption, and neither did the electronic hardening burst on the Damnation when I applied it to the Rev and Abbadon.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Crucifier, max disrupt]

Signal Amplifier II
Damage Control II
Overdrive Injector System II

Dark Blood Tracking Disruptor, Optimal Range Disruption Script
'Investor' Tracking Disruptor I, Optimal Range Disruption Script
Tracking Disruptor II, Optimal Range Disruption Script
5MN Quad LiF Restrained Microwarpdrive

[Empty High slot]
[Empty High slot]

Small Tracking Diagnostic Subroutines I
Small Tracking Diagnostic Subroutines I
[Empty Rig slot]

[Abaddon, not tachyon beams cheap]

Damage Control II
1600mm Steel Plates II
Energized Adaptive Nano Membrane II
Dark Blood Armor Explosive Hardener
Heat Sink II
1600mm Steel Plates II
Heat Sink II

500MN Cold-Gas Enduring Microwarpdrive
Medium Electrochemical Capacitor Booster I, Navy Cap Booster 800
Optical Compact Tracking Computer, Optimal Range Script
Optical Compact Tracking Computer, Optimal Range Script

Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L
Mega Beam Laser II, Imperial Navy Multifrequency L

Large Trimark Armor Pump I
Large Trimark Armor Pump I
Large Anti-Kinetic Pump I

Bouncer II x3

[Damnation, max info links]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Information Command Burst II, Electronic Hardening Charge
Information Command Burst II, Electronic Superiority Charge
Information Command Burst II, Sensor Optimization Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Command Processor I
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
v2.10.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
This used to work, but I haven't tested it in around 6 months.

**Comment by DarkFenX** [comment] 2019-08-24 04:52
Nothing's changed, this bug is random due to unstable effect ordering. Quite possibly can be fixed by changing runtime of TD effect

**Comment by DarkFenX** [comment] 2019-08-26 01:09
```
e796b748b69f973790e2f8b019523a173dc45301 is the first bad commit
commit e796b748b69f973790e2f8b019523a173dc45301
Author: DarkPhoenix <phoenix@mail.ru>
Date:   Mon Jul 8 16:37:43 2019 +0300

    Make sure dromis can be resisted

 eos/effects.py                                     | 9328 ++++++++++----------
 eos/modifiedAttributeDict.py                       |   32 +-
 eos/saveddata/drone.py                             |   10 +-
 eos/saveddata/fighter.py                           |   10 +-
 gui/builtinGraphs/fitDamageStats/projectedCache.py |   54 +-
 5 files changed, 4658 insertions(+), 4776 deletions(-)
```

**Comment by DarkFenX** [comment] 2019-08-26 06:29
Fixed in b25b038934bf9b25430cf359c104e95385e3ea9c

**Closed by DarkFenX** 2019-08-26 06:29 UTC
Labels: bug

**Comment by Calavoow** [comment] 2020-05-12 16:26
This seems to have regressed. Electronic hardening doesn't seem to affect TDs for a fit I am trying them on.

**Comment by DarkFenX** [comment] 2020-05-14 09:55
@Calavoow works for me. Please share all the fits involved and explain order of operations since you launch pyfa.

**Comment by Calavoow** [comment] 2020-05-14 14:24
@DarkFenX I tried to reproduce but couldn't. If it comes back I'll let you know.

**Comment by DarkFenX** [comment] 2020-05-14 21:25
Such bugs can be random (if it is an effect ordering issue, for example). If it comes back, post all the details in a new issue. This issue was for a systematic breakage in resistance calculation.
