### ISSUE TITLE
"Manual Authentication" SSO character addition does not work.

### ISSUE THREAD

**Issue by wscholine** [pyfa-org/Pyfa#2011] opened 2019-07-19 19:08 UTC
### Expected behavior:
After configuring Manual Authentication, pasting the text response from the local webserver should result in a character being imported.

EDIT: Add screenshot of preferences dialog.

### Actual behavior:
An error message is displayed suggesting that the user should configure pyfa the way pyfa is already configured.

### Detailed steps to reproduce:
1. Start pyfa
2. Select Global->Preferences->EVE SSO->SSO Mode = pyfa.io, Login Authentication Method = Manual, 
![del8](https://user-images.githubusercontent.com/41452690/61559515-d67dc280-aa37-11e9-89a4-35318cf2476f.png)
3.  Select Character->Manage ESI Characters->Add Character.
4. Observe that web browser starts, loads login.eveonline.com
5. Log in to EVE Online. Observe that web browser loads authorization page.
6. Authorize character. Observe web response with text-encoded data:
![del7](https://user-images.githubusercontent.com/41452690/61558634-9c132600-aa35-11e9-8d97-00723b381185.png)
7. Select and copy to clipboard the text-encoded data and alt-tab back to pyfa. 
8. Observe that pyfa is prompting for text-encoded data.
9. Paste the text-encoded data into the pyfa dialog.
![del6](https://user-images.githubusercontent.com/41452690/61558745-dd0b3a80-aa35-11e9-9b81-fb0a6c9a22c9.png)
10. Click OK.
11. Observe that pyfa responds with error message instead of importing the character.
![del5](https://user-images.githubusercontent.com/41452690/61558794-04fa9e00-aa36-11e9-9d9c-ac6664fdeb21.png)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
*Not Applicable*

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.9.4
![deleteme](https://user-images.githubusercontent.com/41452690/61558964-818d7c80-aa36-11e9-9653-3455dd20c9a0.png)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Enterprise

### Other relevant information:
See attached log
[pyfa_debug-2019-07-19.log](https://github.com/pyfa-org/Pyfa/files/3412390/pyfa_debug-2019-07-19.log)

**Comment by DarkFenX** [comment] 2019-08-12 14:55
```
[2019-07-19 19:07:20.895686] ERROR: gui.esiFittings: HTTPSConnectionPool(host='esi.evetech.net', port=443): Max retries exceeded with url: /verify/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```
Looks like there is an issue while establishing TLS connection. Do you have any other programs using ESI? Do they work?

**Comment by DarkFenX** [comment] 2019-08-12 15:01
Duplicate of #1999 - same error is there, although on different action.

**Closed by DarkFenX** 2019-08-12 15:01 UTC
Labels: cannot reproduce
