### ISSUE TITLE
Strategic Cruiser Subsystem skills missing or misplaced in Right-Click Menus

### ISSUE THREAD

**Issue by ECHRE-Zetakya** [pyfa-org/Pyfa#1978] opened 2019-05-17 21:11 UTC
Probably related to #1192, but dealing with T3 Subsystem Skills rather than the Ship skills.

When you go to change the subsystem skill via the right click menu (clicking on a subsystem), under "Change Subsystem Skills" *only* the Ship skill appears.

Some of the Subsystem skills appear under "Change Ship Skills", but not all of them.

Legion: Core, Defensive and Propulsion are present; Offensive is missing.
Loki: Defensive and Propulsion are present; Offensive and Core are missing.
Tengu: Core, Defensive and Propulsion are present; Offensive is missing.
Proteus: Defensive is Present; Core, Propulsion and Offensive are missing.

**Comment by DarkFenX** [comment] 2019-05-17 21:23
Please pyfa version and OS details.

**Comment by DarkFenX** [comment] 2019-05-17 21:32
Nevermind. I've misread you, i can reproduce the issue.

**Comment by ECHRE-Zetakya** [comment] 2019-05-17 21:50
2.9.3 on Win 7

Here's a couple of screenshots (in 1 file) showing the menus as I see them.
![Pyfa_1978](https://user-images.githubusercontent.com/23742102/57957986-3223b680-78f6-11e9-8bc8-6821de76544e.png)

**Comment by ECHRE-Zetakya** [comment] 2019-05-17 21:56
Also, having played with it some more, I think that what Subsystems skills appear in the meus is dependant upon what Subsystems are fitted to the ship.

For example, for the Legion, Amarr Core Systems skill will appear in the ship systems sub menu if the Augmented Antimatter Reactor or the Dissolution Sequencer is fitted, but not if the Energy Parasitic Complex is fitted.

**Comment by DarkFenX** [comment] 2019-05-17 21:59
This is how it works in pyfa. What this context menu does is: it checks what affects specific item, tracks down on which skills are in its modification tree and presents it.

So, subsystem skills affect specific items: e.g. tengu graviton reactor modifies ship neut resistance, so this skill is present in ship skill list. Accelerated ejection bay affects missile launcher rate of fire and missile damage, so offensive skill shows up on both module and charge.

In EVE, ship traits work the following way:
- skill has effect which multiplies ship or subsystem bonus attribute (e.g. systemBonusCaldariCore2 base value is -3, skill level 5 multiplies it by 5 - it becomes -15)
- ship or subsystem effect takes this modified value and applies it onto modules/charges/anything else (in the example above it applies to ship, reducing its susceptibility to neuts)

In Pyfa, ship traits following way:
- ship or subsystem effect fetches skill level and applies it to recipients (takes skill level, takes base value of -3, multiplies them, and without changing subsystem attributes applies to target).

When it was implemented, it was hidden under the hood. Only later various info panels started exposing this info - Affected By tab, change skills context menus. It's alot of manual work to change that which will also negatively affect performance (as it's effectively 2x more effects to run for skill modifications), and quite possibly some race condition bugs (where bonus gets applied before it's modified by skills).

And you are completely right that it's related. In fact, it's duplicate of #1192.

**Closed by DarkFenX** 2019-05-17 21:59 UTC
