### ISSUE TITLE
JWT token expired

### ISSUE THREAD

**Issue by VidVrbnjak** [pyfa-org/Pyfa#2380] opened 2021-11-22 18:50 UTC
pyfa v2.38.1
EVE Data Version: 1957858 (2021-10-28 13:15:53)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "service\esiAccess.py", line 238, in validate_eve_jwt
  File "site-packages\jose\jwt.py", line 153, in decode
  File "site-packages\jose\jwt.py", line 461, in _validate_claims
  File "site-packages\jose\jwt.py", line 302, in _validate_exp
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\characterEditor.py", line 826, in addCharacter
  File "service\esi.py", line 112, in login
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 178, in auth
  File "service\esiAccess.py", line 241, in validate_eve_jwt
service.esiAccess.GenericSsoError: The JWT token has expired: Signature has expired.

Unable to get characters with manual or local server mode

**Comment by blitzmann** [comment] 2021-11-24 14:35
My character seem to register in pyfa, however there does seem to be an issue with getting the skills after registering the character. 
![image](https://user-images.githubusercontent.com/3904767/143256315-668e9e06-156d-42ca-82ce-7bbe367477d7.png)
I've seen this a couple of times, I don't have the dev version running and I don't think the error is logged, I'll have to check, but last time this happened it seemed it was a timeout issue on the servers side.

This seems like a separate issue tho, the JWT not validating is new, never seen that fail before. Usually if it's expired, then it should refresh. It might be possible that the refresh token got mangled. I would recommend, if you haven't already, removing all characters in the Manage ESI Characters window, and then starting over. Is this something you've already tried?

**Comment by blitzmann** [comment] 2022-02-04 02:41
Possibly the  same as #2402. @VidVrbnjak  which time zone is your PC set to?

**Comment by blitzmann** [comment] 2022-05-09 02:57
Latest release has an option to disable signature verification. Due to lack of information, going to close this. Still have no idea the cause of it

**Closed by blitzmann** 2022-05-09 02:57 UTC
