### ISSUE TITLE
Error on revoke character(esi)

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1540] opened 2018-05-07 07:58 UTC
## Bug Report
Error when revoking a character in sso character management.

### Expected behavior:
Character gets revoked without issue.

### Actual behavior:
The following error is shown.
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 795, in ssoListChanged
RuntimeError: wrapped C/C++ object of type Choice has been deleted

### Detailed steps to reproduce:
1. Go into character editor>EVE SSO tab
2. click log in with eve sso and login a character
3. exit character editor
4. go into evesso>manage characters
5. revoke the added character
6. note error.

*error also occurs on step 2 after it has happened once on step 5.

### Release or development git branch? Please note the release version or commit hash:
v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by Neugeniko** [comment] 2018-05-07 08:06
Error does not occur when adding then revoking a sso character via the eve sso>character management.

**Comment by blitzmann** [comment] 2018-05-07 16:48
Probably a duplicate of #1501. Whenever you open one of the windows to do esi stuff, it attaches itself to events to look for login / log out (revoke). When those windows close, they don't properly unbind themselves from the events, which allows the python object to stay alive while the c++ object is destroyed.

I have a quick fix for this, just have to apply it. A longer term fix would be to determine why the events aren't unbinding properly (might even be a wxPython bug?)

**Closed by blitzmann** 2018-05-07 16:48 UTC
