### ISSUE TITLE
Pyfa loads slow and i cant add drones to a fit

### ISSUE THREAD

**Issue by wallymarts** [pyfa-org/Pyfa#1457] opened 2018-03-02 13:47 UTC

**Comment by blitzmann** [comment] 2018-03-02 15:34
Hi there!

As for the drone issue, this was fixed with b3: https://github.com/pyfa-org/Pyfa/releases/tag/v2.0.0b3

You may not have gotten an update notification as that code is still in flux with the new beta versions, I'm still looking into it.

As for the slow loading, how does pyfa perform when it's finally loaded? Is there any slowdowns (apart from complex fitting calculations?). Does slowness starting up happen with the 1.35.x releases?

We run a a few database scripts at startup that might slow it down a bit, especially for larger databases, but it shouldn't be for close to 3 minutes... You said that you're on SSD, can you check to make sure both pyfa and it's database files are on the SSD instead of installed to another drive? You can check your paths in Preferences > Database.

**Comment by wallymarts** [comment] 2018-03-05 23:54
So it runs fine once it is open, just when i double click it, it can take
up to 2-3 minutes to open.

**Comment by wallymarts** [comment] 2018-03-05 23:54
also, my computer ONLY has an SSD

**Comment by blitzmann** [comment] 2018-03-10 17:26
@wallymarts That's very weird then... I don't really have a good idea what could be going on. I wonder if there's some sort of anti-virus that is analyzing it when it starts up.

I don't see you mentioning it - have you tried 1.35.2? Does that show the same slowness when starting up? Also, maybe try the new 2.0.0b4 pre-release if you haven't.

**Comment by prozn** [comment] 2018-03-26 14:00
Just to +1 the slow start up. I'm on an 8700K running entirely on SSDs. PYFA takes 3 minutes to start up with no visual indication that the application is starting.

**Comment by blitzmann** [comment] 2018-03-26 16:07
@prozn @wallymarts please try v2.0.0b5 and see if there's any improvement (I suspect not).

Otherwise, next time pyfa loads slow, please go to preferences > Logging > and click the dump logs button. Then go to `%userprofile%/.pyfa` and find the `.log` file that it generated and copy that to this thread. It should have various times associated with log lines, I can take a look at them and see if it's hanging on a specific thing.

We have database maintenance queries that run everytime, which depending on the size of the database could take a while (but not three minutes!)

@prozn I'm particularly interested in your setup, since I also run a 8700k on an m.2 drive. Would you mind actually zipping up your entire `%userprofile%/.pyfa` directory and sending it to me at sable.blitzmann@gmail.com?

Additionally, can you guys post a screenshot of Preferences > Database. This will show me the paths of the databases and where pyfa lives on your system.

It's a lot to ask, I know! But hopefully this will give me a lot more information than is currently available to me. Thanks guys!

**Comment by prozn** [comment] 2018-03-26 23:50
Log below shows the delay - it was actually only 21 second this time, although it has been much longer in the past.

I upgraded to the latest version (I was on 2.0.0b3 already) and it actually seems fine now. I cannot reproduce the issue.

My fitting database is in my user directory, and my game database is in C:\Program Files\pyfa\eve.db

**Log With Delay (2.0.0b3)**
```
[2018-03-26 23:05:28.566572] INFO: __main__: Starting Pyfa
[2018-03-26 23:05:28.567073] INFO: __main__: 
[2018-03-26 23:05:28.567073] INFO: __main__: Writing log file to: C:\Users\matth\.pyfa\pyfa.log
[2018-03-26 23:05:28.567073] INFO: __main__: Running in a frozen state.
[2018-03-26 23:05:28.615702] INFO: eos.db: Initializing database
[2018-03-26 23:05:28.615702] INFO: eos.db: Gamedata connection: sqlite:///C:\Program Files\pyfa\eve.db?check_same_thread=False
[2018-03-26 23:05:28.615702] INFO: eos.db: Saveddata connection: sqlite:///C:\Users\matth\.pyfa\saveddata-py3-dev.db?check_same_thread=False
[2018-03-26 23:05:30.200418] DEBUG: service.prefetch: Run database migration.
[2018-03-26 23:05:30.209943] DEBUG: service.prefetch: Import Required Database Values.
[2018-03-26 23:05:30.260578] DEBUG: service.prefetch: Starting database validation.
[2018-03-26 23:05:30.260578] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for character skills.
[2018-03-26 23:05:30.263086] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned characters attached to fits.
[2018-03-26 23:05:30.265091] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned damage patterns attached to fits.
[2018-03-26 23:05:30.266594] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing damage pattern names.
[2018-03-26 23:05:30.268098] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing target resist names.
[2018-03-26 23:05:30.269602] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned drones items.
[2018-03-26 23:05:30.270605] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned cargo items.
[2018-03-26 23:05:30.272109] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned fighters items.
[2018-03-26 23:05:30.274115] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned modules items.
[2018-03-26 23:05:30.276621] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (em)
[2018-03-26 23:05:30.277624] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (thermal)
[2018-03-26 23:05:30.279127] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (kinetic)
[2018-03-26 23:05:30.280632] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (explosive)
[2018-03-26 23:05:30.282136] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (em)
[2018-03-26 23:05:30.283640] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (thermal)
[2018-03-26 23:05:30.285143] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (kinetic)
[2018-03-26 23:05:30.286648] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (explosive)
[2018-03-26 23:05:30.288152] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for duplicated selected ammo profiles.
[2018-03-26 23:05:30.289656] DEBUG: service.prefetch: Completed database validation.
[2018-03-26 23:05:32.426339] INFO: gui.bitmap_loader: Using local image files.
[2018-03-26 23:05:53.946084] DEBUG: service.market: Initialize SearchWorkerThread.
[2018-03-26 23:05:53.947087] DEBUG: service.market: Initialize ShipBrowserWorkerThread.
[2018-03-26 23:05:53.985188] DEBUG: service.fit: Initialize Fit class
[2018-03-26 23:05:54.009253] DEBUG: gui.statsPane: Setting full view for: resources
[2018-03-26 23:05:54.009253] DEBUG: gui.statsPane: Setting full view for: resistances
[2018-03-26 23:05:54.009253] DEBUG: gui.statsPane: Setting full view for: recharge
```

**Log without Delay (2.0.0b5)**
```
[2018-03-26 23:44:33.775005] INFO: __main__: Starting Pyfa
[2018-03-26 23:44:33.775005] INFO: __main__: 
[2018-03-26 23:44:33.775005] INFO: __main__: Writing log file to: C:\Users\matth\.pyfa\pyfa.log
[2018-03-26 23:44:33.775005] INFO: __main__: Running in a frozen state.
[2018-03-26 23:44:33.816114] INFO: eos.db: Initializing database
[2018-03-26 23:44:33.816114] INFO: eos.db: Gamedata connection: sqlite:///C:\Program Files\pyfa\eve.db?check_same_thread=False
[2018-03-26 23:44:33.816114] INFO: eos.db: Saveddata connection: sqlite:///C:\Users\matth\.pyfa\saveddata-py3-dev.db?check_same_thread=False
[2018-03-26 23:44:33.890312] DEBUG: service.prefetch: Run database migration.
[2018-03-26 23:44:33.898333] DEBUG: service.prefetch: Import Required Database Values.
[2018-03-26 23:44:33.945960] DEBUG: service.prefetch: Starting database validation.
[2018-03-26 23:44:33.945960] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for character skills.
[2018-03-26 23:44:33.947464] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned characters attached to fits.
[2018-03-26 23:44:33.948968] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned damage patterns attached to fits.
[2018-03-26 23:44:33.950472] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing damage pattern names.
[2018-03-26 23:44:33.951474] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing target resist names.
[2018-03-26 23:44:33.952978] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned drones items.
[2018-03-26 23:44:33.953981] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned cargo items.
[2018-03-26 23:44:33.955485] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned fighters items.
[2018-03-26 23:44:33.956989] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned modules items.
[2018-03-26 23:44:33.958493] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (em)
[2018-03-26 23:44:33.959997] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (thermal)
[2018-03-26 23:44:33.961501] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (kinetic)
[2018-03-26 23:44:33.962504] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (explosive)
[2018-03-26 23:44:33.964008] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (em)
[2018-03-26 23:44:33.965512] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (thermal)
[2018-03-26 23:44:33.966514] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (kinetic)
[2018-03-26 23:44:33.968018] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (explosive)
[2018-03-26 23:44:33.969021] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for duplicated selected ammo profiles.
[2018-03-26 23:44:33.970525] DEBUG: service.prefetch: Completed database validation.
[2018-03-26 23:44:33.999101] INFO: gui.bitmap_loader: Using local image files.
[2018-03-26 23:44:35.109054] DEBUG: service.market: Initialize SearchWorkerThread.
[2018-03-26 23:44:35.109555] DEBUG: service.market: Initialize ShipBrowserWorkerThread.
[2018-03-26 23:44:35.134120] DEBUG: service.fit: Initialize Fit class
[2018-03-26 23:44:35.153672] DEBUG: gui.statsPane: Setting full view for: resources
[2018-03-26 23:44:35.153672] DEBUG: gui.statsPane: Setting full view for: resistances
[2018-03-26 23:44:35.153672] DEBUG: gui.statsPane: Setting full view for: recharge
```

**Comment by blitzmann** [comment] 2018-03-27 04:33
Thanks for the logs. I'll take a look at what has changed between those two versions (I can't think of anything that would affect this). Please keep an eye on this though - if you notice it being sluggish, please post some more logs. I'll also try to get more logging included in the next beta release so that I can better determine what is actually taking a while to initialize. :)

**Comment by blitzmann** [comment] 2018-05-22 04:12
We've had a few recent report of slow start up times again... are you guys's still experiencing any issues?

If you are, please continue discussion here: #1605 And please provide log files as instructed.

I'm just curious whether this is still a problem, so trying to get feelers out for it again. :)

**Closed by blitzmann** 2018-05-22 04:12 UTC
