### ISSUE TITLE
Mining Calculations

### ISSUE THREAD

**Issue by TDIScott93** [pyfa-org/Pyfa#1702] opened 2018-08-20 20:23 UTC
### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Hulk]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Strip Miner I
Strip Miner I

[Empty Rig slot]
[Empty Rig slot]

[Covetor]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

[Empty Med slot]

Strip Miner I
Strip Miner I

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Both ships in the module view are displaying 1366M3 under mining amount. The Hulk is higher on the mining yield tab, and is displaying correctly more than the Covetor. 

However the hulk i believe should be 2741.69 per strip and Covetor 2313.07
This is taking into account perfect Orca boosts. so mining laser cycle of 73.9.

**Comment by feyyd** [comment] 2018-08-21 03:13
The amount is the same, but the cycle time is different.  122 on hulk compared to 103 on covetor.  The ships do not have bonuses to yield, but bonus to cycle duration so module view behavior seems to be correct.  If you compare mining yield by toggling the firepower -> mining yield you can see the value taking into account cycle time and it should give you the number you are looking to compare.

**Comment by blitzmann** [comment] 2018-11-29 04:17
I apologize for missing this issue before, but was diriected here because #1790 opened up and figured I'd address this as well

> This is taking into account perfect Orca boosts. so mining laser cycle of 73.9.

For future reference, please paste any boost fittings. I don't know what perfect orca boosts means, as I'm not a miner :) Like, is this with/without (faction?) Mindlink? "perfect boosts" statement could go either way.

Additionally, if the boosts aren't the problem (the problem is still apparent when the boosts are removed), please list unboosted expected vs actual stats, to simplify reproduction. The less things affecting stuff, the better.

> Both ships in the module view are displaying 1366M3 under mining amount. 

Both ships indeed have the same amount per cycle, They differ only ion that the Hulk gets an extra bonus to duration, hence the higher yield.

> However the hulk I believe should be 2741.69 per strip and Covetor 2313.07

What do these values mean? Is this the mining amount per cycle that you are expecting? Please let me know how you're getting these values, as I believe they are far off (about twice as much as I would expect)

I don't see any immediate issue here, though. Taking a look at all the bonuses that are applied, everything looks proper. But, as stated, I'm not a miner, so I could be missing something obvious

![image](https://user-images.githubusercontent.com/3904767/49198966-b6dc4180-f363-11e8-8cb0-12c94a84b2a5.png)

**Comment by blitzmann** [comment] 2018-11-29 04:18
Will keep this issue open for the next few days, @TDIScott93 if you can clarify some of the questions I have that would be great. Otherwise will close this

**Comment by blitzmann** [comment] 2018-12-02 22:42
Going to close this issue - @TDIScott93 if you notice off values again, please reopen another issue and provide the clarifications requested above, and I'll take another look at it :)

**Closed by blitzmann** 2018-12-02 22:42 UTC
