### ISSUE TITLE
Projected tab right-click menu does not appear until there's an entry in Projected

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1316] opened 2017-10-20 05:43 UTC
## Bug Report

Pyfa 1.32.0 Stable, Linux. Right-clicking on any portion of the Projected tab I can find doesn't do anything. 

Workaround: if I project the same fit I'm using onto the current fit, it will project the fit onto itself, creating an entry in the Projected tab. I can then right-click that to add a wormhole effect, then delete the projected fit.

### Expected behavior:

Right-clicking in an empty Projected tab produces a right-click menu.

### Actual behavior:

Nope.

### Detailed steps to reproduce:

Load a fit. Go to the Projected tab. Right click around trying to find a menu.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any fit seems to have the problem.

### Release or development git branch? Please note the release version or commit hash:

Pyfa 1.32.0 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Stretch

### Other relevant information:

See workaround above.

**Comment by blitzmann** [comment] 2017-10-22 01:54
Hmm, unable to reproduce on Windows, will have to try on Linux. This might be an issue with the bindings that linux handles differently. Thanks for the report :)

**Comment by blitzmann** [comment] 2017-10-29 02:28
@BartMassey I'm afraid I can't reproduce on my Linux Mint VM :/ Are you still having the problem with 1.33?

**Comment by BartMassey** [comment] 2017-10-29 06:17
Ayup. I wonder if I'm just not right-clicking in the correct place? I've tried the Projected tab itself, the column headings, and the place where it says "Drag an item or fit, or use right-click menu for wormhole effects". 

Oh wait. If I'm careful not to have the prompt text highlighted and I right click close enough to the bottom of the Projected area, the right-click menu appears! I thought I'd tried that before, but for whatever reason it works now.

So: not sure how this was intended to work, but apparently it does work if you poke at it right. Apologies for all the confusion.

**Comment by blitzmann** [comment] 2017-10-29 15:45
It should work anywhere marked in the red area (behold my lvl5 paint skills):

![image](https://user-images.githubusercontent.com/3904767/32145402-4eef0b9a-bc9e-11e7-9031-aac0f5aa2b1f.png)

I did noticed that it doesn't work on the helper text, which really should be fixed. I forgot to mention that in my previous post. I also noticed on Linux Mint that if that is highlighted, it won't spawn even if you right click the whitespace below it (whereas on Windows, right clicking on the whitespace forces the helper text to lose focus and the menu spawns as normal)

I'll look at adding a binding to the helper item to allow it to spawn the menu as well :)

**Comment by blitzmann** [comment] 2017-10-29 16:25
e5a0ef1 should fix this, feel free to pull from master and have a go with it to confirm. :)

**Closed** 2017-10-29 22:56 UTC
Labels: bug, fixed

**Comment by BartMassey** [comment] 2017-11-01 05:53
Thanks huge as always! If it's not too much trouble, you might want to add a handler for the tab itself also. This is an intuitive place to right-click. If it's a hassle, forget it.
