### ISSUE TITLE
Cannot Fetch Skills

### ISSUE THREAD

**Issue by shadsky** [pyfa-org/Pyfa#1528] opened 2018-04-26 08:50 UTC
## Bug Report
Pyfa does not fetch skills in character Editor window.

### Expected behavior:
Open character editor window. Click on API tab. Input KeyID and vCode.
Get Characters. Fetch Skills.

### Actual behavior:
After inputting API info (keyID and vCode) am able to Get Character, but cannot Fetch Skills.

Get message "Unable to retrieve [char]'s skills. Error message."

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.36.0 Stable - YX120.3 1.8

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

### Other relevant information:
this is an alpha account. I created a second account with a new API, and got the same problem. Could retrieve the character, but could not fetch the skills.

**Comment by blitzmann** [comment] 2018-04-28 23:51
Hi there @shadsky.

Thanks for the bug report. I just checked but cannot reproduce the issue, works for me. It could be that CCPs' api servers had a hiccup when you tried, or could be a network issue (ie: behind a corporate firewall or something). That being said, even if there was an issue, the XML api will be shut off by CCP early next month, so there really isn't much point in fixing any potential problems with it. I have an ESI-based replacement that should be dropping tonight or tomorrow as a pre-release, if you want to check it out. :)

Going to close this as it's going to be invalid in a couple weeks.

**Closed by blitzmann** 2018-04-28 23:51 UTC
