### ISSUE TITLE
Segmentation Fault when deleting a fit that is being viewed.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#164] opened 2014-09-01 09:08 UTC
Software: Slackware 14.1 linux installation
Packages: wxPython-2.8.12.1-i486-2_SBo.tgz, SQLAlchemy-0.9.6-i486-1_SBo.tgz, python-dateutil-2.2-i486-1_SBo.tgz, matplotlib-1.1.1-i486-1_SBo.tgz, numpy-1.8.0-i486-1_SBo.tgz 
Hardware: 1.7Ghz Celeron 32-bit (Single core)

Steps to reproduce.
1. View a fit.
2. Delete the fit as its being viewed.

Other messages: Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem.

Cheers,
Neug

**Comment by blitzmann** [comment] 2015-01-08 20:14
I had a similar issue with a seg fault when destroying wx.ProgressDialog, see: #232 

The way I fixed it was a workaround: don't Destroy, instead Hide. There was also a possible work aroud that may work for this issue: insert a small delay before destroying. Sometimes there is still activity in the events queue when you want to destroy, and that causes the seg fault. Adding a small delay might help.

**Comment by ChemicalRascal** [comment] 2015-09-09 13:27
This crash (though possibly not the exact same one -- regardless, the cause is the same) also appears to occur under Windows 8.1.

**Comment by blitzmann** [comment] 2016-07-02 04:21
I'm taking another look at this. If I comment out this bit that actually deletes the fit, it can still crash, so the fit itself deleting doesn't seem to be the cause.

**Comment by blitzmann** [comment] 2016-07-02 05:09
```
self.mainFrame.Unbind(gui.shipBrowser.EVT_FIT_RENAMED, handler=self.fitRenamed)
```

in `fittingView.py::Destroy()` seems to be causing the issue. If I comment it out, I can't reproduce.

I'm starting to think that this is an event issue or collision of some sort. Each fitting view has events attached to it so that it can look for changes. A proper fix would be to have the fitting view only display the modules, and have all the event handing in the parent, the MultiSwitch. That would be proper design, anyway.

**Comment by DarkFenX** [comment] 2019-08-12 18:07
I haven't been getting any issues with this lately. What about other people in this thread?

**Comment by DarkFenX** [comment] 2019-10-02 12:24
Closing, reopen if still applicable.

**Closed by DarkFenX** 2019-10-02 12:24 UTC
