### ISSUE TITLE
Implants not factoring

### ISSUE THREAD

**Issue by Project462** [pyfa-org/Pyfa#1343] opened 2017-11-25 23:26 UTC
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
Upon updating a set of implants (High Grade Crystal was the tested set) no changes are made in the simulated amounts.

### Expected behavior:
Referencing a set of implants should ideally reflect pertinent metric changes.

### Actual behavior:
No changes seem to be reflected when using implants.

### Detailed steps to reproduce:
I tried using the Implants Editor, which had no effect on multiple characters. I deleted this set and updated each character with their relevant implants, but no effects were witnessed. I closed and restarted PyFa, which did not have any effect. I refreshed the API on each character, which also had no effect.

### Release or development git branch? Please note the release version or commit hash:
1.33.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment] 2017-11-26 06:29
Hi @Project462 ,

I can't reproduce your issue unfortunately, but I think there might be a misunderstanding on how the implants works. So, there are two sources of implants that are used for fitting calculation: implants attached to the character, and implants directly attached to the fit. This can be toggled per fit with these controls:

![image](https://user-images.githubusercontent.com/3904767/33237637-ed76568e-d246-11e7-82ab-11d7977d059d.png)

The reason behind this (besides legacy code) is so that someone can use character implants that travel from fit to fit with the character that's attached to the fit, or switch to fit implants if they want to tweak the implants being used without modifying the character.

The character implant options gets implants that are set up through the character editor for that character. These changes are then reflected to any fit that uses that character and is using character implants.

As for implant sets set up through Window > Implant Set Editor, these aren't actually used directly via the fitting calculations. This is meant to be a repository for you to edit implant sets and easily change a fit / characters implants via the use of the context menu. For example, if you have made a High Grade Crystal set, you then need to apply it to the fit by using Right Click > Add Implant Set.

![image](https://user-images.githubusercontent.com/3904767/33237678-03631b48-d248-11e7-955b-46f89b5f7525.png)

You can also do this on the implants editor for the character. Once you do this, the implants will be applied (basically copied) to that source, but any changes made to the implant set itself afterwards '''will not be propagated'''  (you're basically copying the implants from the set to the fit / character, not linking them).

Hope that clarifies things, but if it's still not working please feel free to respond with some more information such as step-by-step explanation of what you're doing, the fit that you're working with, etc.

**Comment by Project462** [comment] 2017-11-26 14:14
Apologies, I did locate the problem. My own PyFa appears to work correctly.
The issue was with an installation on my friend's computer. After some
digging, I realized that all API refreshed material (market data for
instance) was not updating.

As it turned out, their computer had marked the program suspect,
dissalowing it internet access shortly after the initial API character
pull. I am not sure what triggered that, but if it helps...

The computer uses the following:

Windows 7 Ultimate
Bitdefender 2018 Total Internet Security
ADN (I'm not even sure what that is, but my friend claims it deletes
cookies/addresses for him)

The problem seemed to happen because of some interaction between PyFa and
these (Windows being mentioned only for the firewall) although what what
exactly happened, I'm not entirely sure. After whitelisting PyFa in
Bitdefender and ADN, the issue cleared up (Bitdefender apparently controls
Windows Firewall; learn something new everyday)

**Comment by blitzmann** [comment] 2017-11-26 17:39
> After some digging, I realized that all API refreshed material (market data for instance) was not updating.

I'm a bit confused. Not having network access shouldn't have any affect on how implants function within pyfa. Implants aren't gotten from the characters API, and it's completely local apart from fetching the prices on the implants. ¯\_(ツ)_/¯

Anywho, I'm glad you guys were able to resolve it. A note on market - evecentral is down, so if you want prices to get fetched, change this in the Preferences window. The next release should automatically cascade to other sources if one fails. :)

Closing this as it's resolved, feel free to reopen if anything else pertaining to this issues pop up :)

**Closed by blitzmann** 2017-11-26 17:39 UTC
