### ISSUE TITLE
Error while adding/deleting fits "from clipboard"

### ISSUE THREAD

**Issue by alundil** [pyfa-org/Pyfa#1224] opened 2017-06-08 15:31 UTC
# Submit a bug report bug report or feature request
Adding fits copied from Clipboard. Deleting duplicated fitting.
Upon restarting Pyfa, the fittings in question look to have correctly imported/saved.
---

## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.3 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\awintle\.pyfa
fs encoding: mbcs

EXCEPTION: A conflicting state is already present in the identity map for key (<class 'eos.saveddata.fit.Fit'>, (32,))

  File "C:\Program Files (x86)\pyfa\library.zip\gui\sfBrowserItem.py", line 317, in OnLeftUp
    btn.DoCallback()
  File "C:\Program Files (x86)\pyfa\library.zip\gui\sfBrowserItem.py", line 50, in DoCallback
    self.callback()
  File "C:\Program Files (x86)\pyfa\library.zip\gui\shipBrowser.py", line 1802, in deleteBtnCB
    self.deleteFit()
  File "C:\Program Files (x86)\pyfa\library.zip\gui\shipBrowser.py", line 1819, in deleteFit
    sFit.deleteFit(self.fitID)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 188, in deleteFit
    eos.db.saveddata_session.delete(fit)
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1632, in delete
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\identity.py", line 132, in add

### Expected behavior:
Adding fits copied from clipboard. Each fit should open in the corresponding tab.

### Actual behavior:
Added several fits "from clipboard". Last successful "from clipboard" was the Oracle fit. Added the Typhoon fit and the tab for the Oracle displayed while still showing the Typhoon on the Fittings panel to the left. Deleted that fitting. Attempted to add the Typhoon again. Same result. Deleted the fitting again and Pyfa threw the error above.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Oracle, Oracle]
 
Nanofiber Internal Structure II
Nanofiber Internal Structure II
Heat Sink II
Heat Sink II
Heat Sink II
Damage Control II
 
Large Shield Extender II
Large Shield Extender II
50MN Quad LiF Restrained Microwarpdrive
 
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
 
Medium Anti-EM Screen Reinforcer II
Medium Core Defense Field Extender I
Medium Hyperspatial Velocity Optimizer II

[Typhoon, Typhoon]
 
1600mm Steel Plates II
1600mm Steel Plates II
1600mm Steel Plates II
1600mm Steel Plates II
Damage Control II
Energized Adaptive Nano Membrane II
Energized Adaptive Nano Membrane II
 
Large Micro Jump Drive
500MN Y-T8 Compact Microwarpdrive
Heavy Electrochemical Capacitor Booster I
Heavy Electrochemical Capacitor Booster I
Burst Jammer II
 
Heavy Gremlin Compact Energy Neutralizer
Heavy Gremlin Compact Energy Neutralizer
Heavy Gremlin Compact Energy Neutralizer
Medium Gremlin Compact Energy Neutralizer
Medium Gremlin Compact Energy Neutralizer
Improved Cloaking Device II
Core Probe Launcher II
 
Large Hyperspatial Velocity Optimizer I
Large Hyperspatial Velocity Optimizer I
Large Higgs Anchor I

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: 	Windows-8-6.2.9200

**Comment by blitzmann** [comment] 2017-06-08 23:24
Duplicate of #1207, gonna make a release tonight to address this

**Comment by blitzmann** [comment] 2018-05-28 23:17
Closing this as fixed a while ago

If you have any other issues crop up, please feel free to open a new issue 😄

**Closed by blitzmann** 2018-05-28 23:17 UTC
Labels: duplicate
