### ISSUE TITLE
Change Charge Skills > no entry for weapon skill

### ISSUE THREAD

**Issue by unpoetical** [pyfa-org/Pyfa#535] opened 2016-03-12 00:47 UTC
I'm just adding cruise missiles to my training and using them in a fit in pyfa.

If I right click on a fitted cruise missile launcher > change module skills, cruise missiles doesn't show in the list of skills that can be modified.   It's not there in change charge skills either.   It does show in charge stats > affected by.   There are 8 things in charge stats > affected by, but only 5 items in change charge skills.

**Comment by blitzmann** [comment] 2016-03-12 01:07
Confirmed, I'll look into it soon.

**Comment by aacn500** [comment] 2016-03-20 23:22
I took a look at this, and I think there are two interrelated issues. The first is that the skills in Change Charge Skills is a duplicate of Change Module Skills, which I have a fix for. 

The second is that Cruise Missiles (and similar skills for other missile launchers) don't technically affect the module itself, but instead affect the missile. (The module doesn't deal the damage, the missile does). Pyfa recognises this, and lists those skills as only affecting the missile. 

So, the change I have would list the Cruise Missiles skill, but under the Charge skills submenu, where people might not expect it. Is that okay, or should pyfa force all those skills to be listed under the module?

**Comment by blitzmann** [comment] 2016-03-20 23:37
That should be fine, and it's the way it should happen. Submit a pull request and I'll take a loot at it. =)

**Comment by blitzmann** [comment] 2016-03-20 23:57
Took a look at it, looks good. Thanks!

**Closed** 2016-05-01 00:10 UTC
Labels: bug, fixed
