### ISSUE TITLE
Pyfa crashes when deleting a fit that is current open (Windows+Mac)

### ISSUE THREAD

**Issue by mkemnetz** [pyfa-org/Pyfa#725] opened 2016-09-06 15:28 UTC
If you have a fit open and delete it in the sidebar, Pyfa crashes and must be rebooted.

**Comment by blitzmann** [comment] 2016-09-07 03:28
Most probably a duplicate of #518, which itself is probably a duplicate of #164. This bug has persisted for quite a while - I've gone back to it occasionally trying to figure it out (I believe it's a crash on the wxWidget side of things, rather than something wxPython / pyfa is doing), with no real luck. The problem for me is that it's not always reproducible.

**Closed by blitzmann** 2016-09-07 03:28 UTC
Labels: duplicate
