### ISSUE TITLE
GraphFrame: FIT_CHANGED event is not properly unbinding when the window is closed

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1442] opened 2018-02-27 05:35 UTC
See # 1430 for more discussion.

The `GE.FIT_CHANGED` event is linked to `draw()`. It would seem that this method is called even when the GraphFrame is closed. It seems to only do it once though (doing reproduction steps multiple times does not output multiple warnings).

It's possible it may be related to the `MainFrame.graphFrame` keeping a reference of it around even after it closing, might be a decent place to start looking.

**Comment by Neugeniko** [comment] 2018-02-27 06:16
Although the error does not pop up anymore the fit frame fails to refresh anymore and the client needs to be restarted, after triggering the problem using #1430 reproduction steps.

**Comment by Neugeniko** [comment] 2018-02-27 11:14
Reversing the order of the unbind events seems to solve the problem. But may introduce another......although i havent been able to trip up left double click.

def close(self, event):
        self.mainFrame.Unbind(GE.FIT_CHANGED)
        self.fitList.fitList.Unbind(wx.EVT_LEFT_DCLICK)

**Comment by Neugeniko** [comment] 2018-02-27 11:48
Putting in the handler parameter seems to fix things. Did some autoconversion remove it? Its used in master?

def close(self, event):
        self.fitList.fitList.Unbind(wx.EVT_LEFT_DCLICK, handler=self.removeItem)
        self.mainFrame.Unbind(GE.FIT_CHANGED, handler=self.draw)
        event.Skip()

**Comment by blitzmann** [comment] 2018-02-27 14:53
>Although the error does not pop up anymore the fit frame fails to refresh anymore

Gah! >.<

> Putting in the handler parameter seems to fix things. Did some autoconversion remove it? Its used in master?

I removed them when addressing the similar issue described in https://github.com/wxWidgets/Phoenix/issues/624

According to Robin, `handler=` wasn't working correctly in 4.0.0b2, but was fixed for rc1 (I think). Since we're using b2 right now... I'm not sure why that works but the others didn't. Possibly has to do with how they are set up...

I'll try this when I get home and make the fix, unless you want to submit a PR to get credit for finding a solution! :)

**Comment by Neugeniko** [comment] 2018-02-27 16:29
I put the PR in, might be a bit messy because its been a while since Iv'e done one.

**Comment by blitzmann** [comment] 2018-02-27 16:54
No worries, looks great! Will test when I get home tonight and merge in, hopefully that puts this issue to rest lol

**Comment by blitzmann** [comment] 2018-02-28 02:11
Merged in your fix, thanks! However, `draw()` still runs. Gonna sit down this weekend and really take a good look at the events, what's binding, and how, and maybe get a small reproducible app going that I can play with without all the other things that the Graph window does

**Comment by DarkFenX** [comment] 2019-08-07 09:33
I removed workaround and it seems to work after graph rework. Closing issue.

**Closed by DarkFenX** 2019-08-07 09:33 UTC
Labels: 2.x, bug
