### ISSUE TITLE
Certain Boosters causeing erros.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2005] opened 2019-06-25 03:06 UTC
This data in boosters table was causing a error, its a cerebral accelerator

"75"	"48614"	"1844"	"1"	"2019-01-05 10:00:21.336277"

this error
pyfa v2.9.4
EVE Data Version: 1514398 (2019-05-28 23:07:48)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.4
Logbook version: 1.4.3
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 89, in fitSelected
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 344, in fitSelected
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 603, in slotsChanged
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 554, in generateMods
  File "C:\projects\pyfa\service\fit.py", line 309, in getFit
  File "C:\projects\pyfa\service\fit.py", line 482, in recalc
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 453, in clear
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 247, in boosters
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 282, in __get__
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 712, in get
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1322, in set_committed_value
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 661, in append_multiple_without_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1114, in append
  File "C:\projects\pyfa\eos\effectHandlerHelpers.py", line 283, in append
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1121, in remove
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1094, in __del
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 732, in fire_remove_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1172, in fire_remove_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1518, in emit_backref_from_collection_remove_event
KeyError: '_Fit__boosters'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 573, in Refresh
  File "C:\projects\pyfa\service\fit.py", line 309, in getFit
  File "C:\projects\pyfa\service\fit.py", line 482, in recalc
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 453, in clear
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 247, in boosters
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 282, in __get__
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 712, in get
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1322, in set_committed_value
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 661, in append_multiple_without_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1114, in append
  File "C:\projects\pyfa\eos\effectHandlerHelpers.py", line 283, in append
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1121, in remove
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1094, in __del
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 732, in fire_remove_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1172, in fire_remove_event
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1518, in emit_backref_from_collection_remove_event
KeyError: '_Fit__boosters'

**Comment by DarkFenX** [comment] 2019-06-25 05:32
What exactly are you trying to do and which boosters you already have during said action?

**Comment by DarkFenX** [comment] 2019-08-07 09:40
As this booster is not published, I've added it to random Jaguar fit manually via editing saveddata.db. I could not reproduce the issue. Closing it, if you still can reproduce it please reopen with extra data.

**Closed by DarkFenX** 2019-08-07 09:40 UTC
Labels: bug
