### ISSUE TITLE
Skills being generated without a character assigned, usually after API import, error with Affecting Skills menu

### ISSUE THREAD

**Issue by AlhiraK** [pyfa-org/Pyfa#1234] opened 2017-06-19 23:18 UTC
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.4 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\Tom\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'name'

  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 577, in spawnMenu
    menu = ContextMenu.getMenu(selection, *contexts)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\contextMenu.py", line 85, in getMenu
    sub = m.getSubMenu(srcContext, selection, rootMenu, it, rootItem)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinContextMenus\changeAffectingSkills.py", line 88, in getSubMenu
    bitmap = BitmapLoader.getBitmap("lvl%s" % skill.level, "gui")
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 337, in level
    if self.character.name == "All 5":

I tried to rightclick on a 125mm Gatling AutoCannon I in a Vulture fitting. Restarting PyFa didn´t let this Issue come up again.

**Comment by blitzmann** [comment] 2017-07-10 05:18
Apologies for the delay; went on vacation, then came back to figurative fires at the office, now recovering from Steam Summer Sale and prepping for July release/ two conferences in the next three weeks @_@

We keep getting this error popping up randomly for some folks. I don't get it, and can't find the cause of it. I know it's been a few weeks since you reported this, but do you by chance remember if you had updated your characters API before that error popped up? That seems to be a common theme surrounding this issue. :/

**Comment by blitzmann** [comment] 2017-07-16 02:12
With 1.30.0, I introduced code that would (should) bypass this issue, but not address the core of it (skills being created without characters assigned). Due to the "fix", some situations may come up where the skill lever shown is not correct (for alpha characters, and I hope only limited to the affecting skills submenu, as that's where this error particularly keeps popping up).

Marking this to investigate the cause as some point in future.

**Comment by blitzmann** [comment] 2018-03-01 05:35
I believe we have a fix for this in place for the next release. Please keep an eye on this - if you happen to run across it after the next release (in a couple days), please open another ticket. Thanks!

**Closed** 2018-03-04 22:13 UTC
Labels: bug, fixed, investigate, logged, workaround-available
