### ISSUE TITLE
paste into notes

### ISSUE THREAD

**Issue by epmd34** [pyfa-org/Pyfa#899] opened 2016-12-12 16:11 UTC
When the notes pane is active copy,paste cut etc should act on the clipboard as text, not try to import / export fittings.

**Comment by Ebag333** [comment] 2016-12-12 16:15
Unfortunately we hijack copy/paste, because of the import/export fittings option.  It's been that way for years, and it's set very low level.  I'm not sure we can override that, and if we do we're changing the default behavior of the whole app (ctrl-c does one thing most places, something else in on specific case, that sort of thing tends to be bad UI and confusing to end users).

You can right click to bring up the context menu (at least in Windows, not sure on Linux/Max).

**Comment by blitzmann** [comment] 2016-12-12 16:21
We need to fix this for #490 as well, sooner rather than later.

We should be able to specifically define C&P shortcuts on a per-widget level. We want to keep the global shortcut for fittings, but this definitely needs to be fixed when we need it.

**Comment by resinneublem** [comment] 2016-12-13 05:23
@epmd34 What platform are you running in? OSX?

**Comment by epmd34** [comment] 2016-12-13 09:22
OSX

**Comment by blitzmann** [comment] 2016-12-13 15:11
@epmd34  Ah, yeah, then that's the problem. I thought this was a Windows bug, so this is really a duplicate of #490. Still need to find a solution for this tho...

**Comment by DarkFenX** [comment] 2019-08-22 05:53
Closed as duplicate of #490 (which should be fixed starting from next release)

**Closed** 2019-08-22 05:53 UTC
Labels: bug, duplicate, macOS
