### ISSUE TITLE
[OS X] Right-clicking in Character Editor Skill Window Reliably Produces Crash

### ISSUE THREAD

**Issue by lambo117** [pyfa-org/Pyfa#1915] opened 2019-04-08 14:14 UTC

**Comment by burnsypet** [comment] 2019-04-08 14:23
I can reproduce this on Mac OSX 10.13.3, seems to be some kind of segmentation fault:

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by DarkFenX** [comment] 2019-04-08 15:10
Is it reliably reproducible with the same items? Or maybe it sometimes crashes, sometimes it doesn't?

Try finding same skills via search and see if they still crash/do not crash, collapsing/expanding some skill groups.

Also, check if crash happens in "affected" tab of item stats window.

**Comment by lambo117** [comment] 2019-04-08 15:58
I did a few more tests, and here is what I've found:

I can avoid the crash by first expanding a skill category. Once this is done, right clicks will not result in a crash. However, if I collapse the expanded section, then right click, Pyfa will crash. 

I tried right-clicking in the other tabs of the Character Editor, and this did NOT result in a crash. I tried right clicking with multiple player characters and the default All V character, and the crash occurred with all of them.

Again, for clarification, this crash only occurs when right-clicking a skill category in the Skills tab of the Character Editor PRIOR to expanding a category with a left click.

Thanks!

**Comment by DarkFenX** [comment] 2019-04-08 17:10
I am at loss. What are you right-clicking? Skill category or skill? If skill, how do you right click it without expanding skill category?

**Comment by lambo117** [comment] 2019-04-08 18:10
Sorry for the confusion. I'll try to be clear:

- In the skills tab of the character editor, if I **have not expanded a skill category** and I make a right click **anywhere** in the skills "pane", Pyfa crashes.

- In the skills tab of the character editor, if I **have expanded a skill category**, then I make a right click anywhere in the window, **sometimes** Pyfa will crash. Sometimes it will not. The crash does not seem to be dependent on where in the skill "pane" I have right clicked. Sometimes it crashes when I right click on a skill, sometimes it crashes when I right-click empty whitespace. Other times, it does not crash at all.

Does this help?

**Comment by DarkFenX** [comment] 2019-04-08 20:17
Yes, definitely. But no promises that it will be fixed by next release which is due after EVE update which is tomorrow.

**Comment by blitzmann** [comment] 2019-04-09 01:55
I'll try to take a look tomorrow, but no promises on my end either

@lambo117 your original error message states 2.7.0. But we've updated to 2.8.0. Can you confirm the version in which you are using?

**Comment by lambo117** [comment] 2019-04-09 18:57
Sorry... I must've fat-fingered it. The version I'm using is the latest, version 2.8.0.

Also, no need to make promises. I just thought you guys might like to know.

Thanks again.

**Comment by herk** [comment] 2020-05-29 10:12
I just stumbled upon this and just made a quick change to fix the segfault when right clicking, can be found over here https://github.com/herk/Pyfa/commit/bec9b15eb

I'm not so familiar with wxPython but would be much better if you could get the position and select the item just like the in the fitting view.

**Comment by DarkFenX** [comment] 2020-06-18 03:03
I tried to implement similar functionality but I doubt it is possible. The issue is that `TreeListEvent` doesn't expose coordinates of the event. `ListCtrl` context menu events do - and via some hackery I was able to enforce selection there, as you mention.

https://wxpython.org/Phoenix/docs/html/wx.dataview.TreeListEvent.html

Taking your fix to prevent crashes.

**Comment by DarkFenX** [comment] 2020-06-18 03:04
Fixed in 62d1d6a06d7c402bd8d1b1ec962c0d5df3938d1c

**Closed by DarkFenX** 2020-06-18 03:04 UTC
Labels: bug, gui, macOS
