### ISSUE TITLE
Feature request  -  Dark Theme

### ISSUE THREAD

**Issue by knowfear1337** [pyfa-org/Pyfa#1331] opened 2017-11-01 03:37 UTC
# Feature request
---

Dark Theme ? 

I have no idea how hard it would be to implement but i imagine it wouldn't be too hard, but we are all nerds that have sensitive eyes yes ? 

I'd be willing to help but i've never done UI/UX programming only 'simple' embedded stuff

**Comment by burnsypet** [comment] 2017-11-01 09:53
It looks like a fork was developed to support a dark mode in #1206 but I'm not sure if it was ever merged into master. Looks kinda cool:

https://puu.sh/wkYf4/6439d5e5b2.png

**Comment by Ebag333** [comment] 2017-11-01 09:54
This and about 500 other bugfixes and enhancements... M

**Comment by blitzmann** [comment] 2017-11-01 16:53
I'm working on a couple other projects at the moment that may help benefit this. Ebag333 indeed has done some work on it but there's a few issues and from what I remember not ready for publication. The biggest issue that I ran into when looking at it is the column headers - there's no real way for us to declare a custom color for that as it's drawn using the operating system's GUI control. I have a few ideas, but all of them require a bit of work to get implemented.

Optional workaround: switch to Linux. =P Joking obviously, but to elaborate, Linux, unlike Windows (and maybe osx?) allows full customization of the system theme, and that is what pyfa uses - the systems current theme. It makes it look much more... native. There were some screenshots way back when Kadesh maintained pyfa on pyfa running on a dark theme Linux box, but can't find those atm. Quick google search pulled up this tho (guy running linux with dark theme: http://i.imgur.com/o1B5xds.png).

Gonna close this as it's a duplicate of #1206

**Closed by blitzmann** 2017-11-01 16:53 UTC

**Comment by knowfear1337** [comment] 2017-11-02 17:16
yup that Linux dark theme does look nice, but in all honesty even if it is only half dark with the white border from windows i would still be happy with it as a start or if that's as dark as it can get :) but its def not urgent like bug-fixes or crashes
