### ISSUE TITLE
Error upon attempting to export fits with both html and xml options

### ISSUE THREAD

**Issue by PeterVLee** [pyfa-org/Pyfa#2566] opened 2023-12-30 21:13 UTC
## Bug Report
When attempting to back up or export fits to a file in either format, the pyfa error window will appear and the file will not be created. 

### Expected behavior:
Select either "Backup All Fittings" or "Export All Fittings to HTML", expect files in chosen folder for xml or the pyfa folder for HTML.

### Actual behavior:
Export fails, pyfa error window appears.

### Release or development git branch? Please note the release version or commit hash:
Release, version v2.57.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro

### Other relevant information:
Interestingly, backing up or exporting will work while the error window is still open, though the HTML export will give incomplete results. Attached is the broken HTML export.

### Files:
[pyfa error.txt](https://github.com/pyfa-org/Pyfa/files/13799178/pyfa.error.txt)
[pyfaFits.txt](https://github.com/pyfa-org/Pyfa/files/13799183/pyfaFits.txt) (had to replace .html with .txt to attach this here)
[pyfa-2023-12-30.txt](https://github.com/pyfa-org/Pyfa/files/13799185/pyfa-2023-12-30.txt) (ditto)

**Comment by DarkFenX** [comment] 2024-02-20 16:07
I suspect it's caused by #2552, which in turn is caused by https://github.com/wxWidgets/Phoenix/issues/1610. Since I don't have access to windows machine, I can't really make and test necessary adjustments. If someone can, please follow links and see if you can help with it.

**Comment by DarkFenX** [comment] 2024-02-26 01:24
I am working on it. Will be resolved after I close #2552. Closing this one as duplicate.

**Closed by DarkFenX** 2024-02-26 01:24 UTC
