### ISSUE TITLE
Harvester set bonuses not applying to rorqual harvester drones

### ISSUE THREAD

**Issue by aydjay** [pyfa-org/Pyfa#918] opened 2016-12-22 17:07 UTC
Using the following fit:

[Rorqual, Rorqual Drones]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Capital Drone Mining Augmentor I
Capital Drone Mining Augmentor I
Capital Drone Mining Augmentor I

'Excavator' Mining Drone x5

And then applying the full Mid-Grade Harvest set as Fit-specific implants

![image](https://cloud.githubusercontent.com/assets/9460838/21433738/f38e85ca-c868-11e6-93b0-a7e2c5c26b6b.png)

After removing the implants the drone yield is still the same.

![image](https://cloud.githubusercontent.com/assets/9460838/21433774/15a051a2-c869-11e6-8a37-15d90545641d.png)

This is using version 1.26.0

**Comment by Ebag333** [comment] 2016-12-27 07:44
>And then applying the full Mid-Grade Harvest set as Fit-specific implants
>After removing the implants the drone yield is still the same.

That would be because the Harvest set does not affect drones.
```
Primary Effect: +3 bonus to Charisma 
Secondary Effect: 5% bonus to the range to all mining lasers 
Set Effect: 10% bonus to the strength of all Harvest implant secondary effect
```

While drones use mining lasers, any effects that affect mining laser stats don't pass their bonuses on to drones.  Contrast that to Rorqs hull bonus.
```
Capital Industrial Ships bonuses (per skill level):
10% bonus to Drone hitpoints, damage and ore mining yield
10% reduction in Drone ice harvesting cycle time
```

You can see that Drones are specifically called out.

So, working as designed.

**Comment by blitzmann** [comment] 2017-01-27 02:17
I can confirm that the set does not affect drones. If you are noticing discrepancies between pyfa and EVE, please provide more details. But for now I'll be closing this issue. :)

**Closed by blitzmann** 2017-01-27 02:17 UTC
