### ISSUE TITLE
Error Connecting to CREST

### ISSUE THREAD

**Issue by ManixI** [pyfa-org/Pyfa#1295] opened 2017-09-23 10:16 UTC
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
Attempted to login to crest.  Login failed.  

### Expected behavior:
Login to CREST

### Actual behavior:
Login succeeds on login.eve.com returning:
If you see this message then it means you should be logged into CREST. You may close this window and return to the application.

pyfa returns the error message:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: H:\Documents\pyfa
save path: C:\Users\Ian\.pyfa
fs encoding: mbcs

EXCEPTION: The C++ part of the ExportToEve object has been deleted, attribute access no longer allowed.

  File "H:\Documents\pyfa\library.zip\gui\crestFittings.py", line 245, in ssoLogin
    self.updateCharList()
  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__

the export and brows functions in the CREST menu remain grayed out, with only the login to EVE function accessible.  

### Detailed steps to reproduce:
CREST > Login
Enter login information
authorize pyfa to login

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Stratios, Camp Tacle]

Republic Fleet Medium Armor Repairer
Republic Fleet Medium Armor Repairer
Damage Control II
Energized Adaptive Nano Membrane II
Drone Damage Amplifier II

50MN Microwarpdrive II
Caldari Navy Stasis Webifier
Dark Blood Warp Scrambler
'Thurifer' Large Cap Battery
Medium Capacitor Booster II, Navy Cap Booster 800

Medium 'Ditch' Energy Neutralizer
Medium 'Ditch' Energy Neutralizer
Small Energy Neutralizer II
Covert Ops Cloaking Device II
Sisters Core Probe Launcher

Medium Anti-Explosive Pump I
Medium Nanobot Accelerator II
Medium Auxiliary Nano Pump II

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: H:\Documents\pyfa
save path: C:\Users\Ian\.pyfa
fs encoding: mbcs

EXCEPTION: The C++ part of the ExportToEve object has been deleted, attribute access no longer allowed.

  File "H:\Documents\pyfa\library.zip\gui\crestFittings.py", line 245, in ssoLogin
    self.updateCharList()
  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__

### Other relevant information:
This is not specific to this particular fit, attempting to login with other Stratios fits or fits of other ships also returns the same error message.

**Comment by blitzmann** [comment] 2017-09-23 17:23
Thanks for bug report!

It's a duplicate of #1260 - I haven't had a chance to delve into it, but I think this is the next thing on my list. I plan to make a release today / tomorrow, so I'm not sure if this fix will be included. To solve the issue, restart pyfa. :)

Would help, just for completeness, to have a copy of your pyfa log containing this error found at `%userprofile%/.pyfa` - simply drag it into the comment and it should upload.

Additionally, just to confirm, you're able to log in at least once, and subsequent log ins are erroring out, correct?

**Comment by ManixI** [comment] 2017-09-23 20:47
[Pyfa-2017-09-22.log](https://github.com/pyfa-org/Pyfa/files/1326846/Pyfa-2017-09-22.log)
[Pyfa-2017-09-23.log](https://github.com/pyfa-org/Pyfa/files/1326850/Pyfa-2017-09-23.log)


Yes, I had previously logged onto a different account successfully.  I had been logged out automatically before attempting the login that resulted in the error.  

Restarting seems to have reset the issue so that I can get one successful login.  Also, if I login, logout, and login again without exporting I don't get the error message, but if I login, export a fit, and logout then the next login will result in the above error.

**Comment by blitzmann** [comment] 2017-09-23 22:22
kk thanks for the extra info, sounds exactly like the other issue. Gonna close this one, please subscribe to the other one (#1260) for updates :)

**Closed by blitzmann** 2017-09-23 22:22 UTC
Labels: duplicate
