### ISSUE TITLE
Undoing a abyssal module deletion causes error and halts.

### ISSUE THREAD

**Issue by mdmss** [pyfa-org/Pyfa#1903] opened 2019-03-25 18:10 UTC
## Bug Report
Pyfa prints an error message and halts when you remove an abyssal module from the fit and try to undo change.

### Expected behavior: 
Refits the deleted module.

### Actual behavior:
Error messsage. 
Does not refit module.

### Detailed steps to reproduce:
Add imported or make your own abyssal module. Delete it with delete-button or doubleclicking. Press CTRL-Z or select Edit - Undo.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Possibly any fit with abyssal module. Tested with many abyssal modules.

### Release or development git branch? Please note the release version or commit hash:
Relase, issue has been present since abyssal modules were added to pyfa.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Enterprise

### Other relevant information:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\fitCommands\calc\fitRemoveModule.py", line 57, in Undo
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by DarkFenX** [comment] 2019-03-25 18:13
Duplicate of #1848

**Closed by DarkFenX** 2019-03-25 18:13 UTC
