### ISSUE TITLE
Mac deprecated version crashes on launch 

### ISSUE THREAD

**Issue by JoshuaNotowitz** [pyfa-org/Pyfa#954] opened 2017-01-27 19:16 UTC
When I try to launch it it just bounces in the dock for a little while and then closes

**Comment by Ebag333** [comment] 2017-01-27 19:32
Can you please send me your saveddata database? ebagola@gmail.com 

If you see a log file there, see if there is anything logged.

**Comment by JoshuaNotowitz** [comment] 2017-01-27 20:01
Where do i find this file?

**Comment by Ebag333** [comment] 2017-01-27 20:07
https://github.com/pyfa-org/Pyfa/wiki/Database

Let me know if you have any trouble finding it.

**Comment by JoshuaNotowitz** [comment] 2017-01-27 20:11
Sent

**Comment by Ebag333** [comment] 2017-01-27 20:49
There is some database corruption.

```
2017-01-27 12:46:57,012 eos.db.saveddata.databaseRepair DEBUG    Running database cleanup for orphaned characters attached to fits.
2017-01-27 12:46:57,056 eos.db.saveddata.databaseRepair ERROR    Database corruption found. Cleaning up 5 records.
```

Next release of Pyfa will have some cleanup that it will perform.  Still looking over the log file, that has a ton of stuff in it that might be the cause for it failing to launch.

Also, dang.  I thought I had a lot of fits, your DB is twice my size.

**Comment by JoshuaNotowitz** [comment] 2017-01-27 20:52
yea that might contribute to why the non deprecated version seems to run so slow

**Comment by Ebag333** [comment] 2017-01-27 21:09
@blitzmann some of the relevant info from the logs.

All these tracebacks in the log are old (2015).  I want to still double check on them to make sure that we have a fix in place for them, since we've had some issues that go back that far that we still haven't been able to identify the cause of yet.  Skip past the tracebacks for the recent errors.

```
2015-11-04 11:20:34,592 STDERR                   ERROR    Traceback (most recent call last):
2015-11-04 11:20:34,593 STDERR                   ERROR      File "/Users/USER/Desktop/pyfa.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14640, in <lambda>
2015-11-04 11:20:34,601 STDERR                   ERROR    lambda event: event.callable(*event.args, **event.kw) )
2015-11-04 11:20:34,601 STDERR                   ERROR      File "/Users/USER/Desktop/pyfa.app/Contents/Resources/gui/mainFrame.py", line 205, in ShowUpdateBox
2015-11-04 11:20:34,602 STDERR                   ERROR    dlg.Destroy()
2015-11-04 11:20:34,602 STDERR                   ERROR      File "/Users/USER/Desktop/pyfa.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14590, in __getattr__
2015-11-04 11:20:34,604 STDERR                   ERROR    raise PyDeadObjectError(self.attrStr % self._name)
2015-11-04 11:20:34,604 STDERR                   ERROR    wx._core
2015-11-04 11:20:34,605 STDERR                   ERROR    .
2015-11-04 11:20:34,605 STDERR                   ERROR    PyDeadObjectError
2015-11-04 11:20:34,605 STDERR                   ERROR    :
2015-11-04 11:20:34,605 STDERR                   ERROR    The C++ part of the UpdateDialog object has been deleted, attribute access no longer allowed.
```

Looks like we're trying to delete something already gone.

```
2015-11-02 21:52:27,700 STDERR                   ERROR    Traceback (most recent call last):
2015-11-02 21:52:27,700 STDERR                   ERROR      File "/Users/USER/Downloads/pyfa.app/Contents/Resources/gui/statsPane.py", line 39, in fitChanged
2015-11-02 21:52:27,701 STDERR                   ERROR    view.refreshPanel(fit)
2015-11-02 21:52:27,701 STDERR                   ERROR      File "/Users/USER/Downloads/pyfa.app/Contents/Resources/gui/builtinStatsViews/resistancesViewFull.py", line 194, in refreshPanel
2015-11-02 21:52:27,701 STDERR                   ERROR    ehp = (fit.ehp if self.showEffective else fit.hp) if fit is not None else None
2015-11-02 21:52:27,701 STDERR                   ERROR      File "/Users/USER/Downloads/pyfa.app/Contents/Resources/eos/saveddata/fit.py", line 888, in ehp
2015-11-02 21:52:27,701 STDERR                   ERROR    ehp = self.damagePattern.calculateEhp(self)
2015-11-02 21:52:27,701 STDERR                   ERROR      File "/Users/USER/Downloads/pyfa.app/Contents/Resources/eos/saveddata/damagePattern.py", line 35, in calculateEhp
2015-11-02 21:52:27,701 STDERR                   ERROR    ehp[type] = self.effectivify(fit, rawCapacity, type)
2015-11-02 21:52:27,701 STDERR                   ERROR      File "/Users/USER/Downloads/pyfa.app/Contents/Resources/eos/saveddata/damagePattern.py", line 50, in effectivify
2015-11-02 21:52:27,702 STDERR                   ERROR    totalDamage = sum((self.emAmount, self.thermalAmount, self.kineticAmount, self.explosiveAmount))
2015-11-02 21:52:27,702 STDERR                   ERROR    TypeError
2015-11-02 21:52:27,702 STDERR                   ERROR    :
2015-11-02 21:52:27,702 STDERR                   ERROR    unsupported operand type(s) for +: 'int' and 'NoneType'
```

Looks like we have a bad damage pattern here, one of the amounts is None.

```
2015-11-02 21:50:30,813 STDERR                   ERROR    Traceback (most recent call last):
2015-11-02 21:50:30,813 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/cargoView.py", line 138, in fitChanged
2015-11-02 21:50:30,813 STDERR                   ERROR    self.original = fit.cargo if fit is not None else None
2015-11-02 21:50:30,813 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/eos/saveddata/fit.py", line 190, in cargo
2015-11-02 21:50:30,814 STDERR                   ERROR    return self.__cargo
2015-11-02 21:50:30,814 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/attributes.py", line 163, in __get__
2015-11-02 21:50:30,814 STDERR                   ERROR    instance_dict(instance))
2015-11-02 21:50:30,814 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/attributes.py", line 383, in get
2015-11-02 21:50:30,814 STDERR                   ERROR    value = callable_(passive=passive)
2015-11-02 21:50:30,814 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/strategies.py", line 646, in __call__
2015-11-02 21:50:30,814 STDERR                   ERROR    result = q.all()
2015-11-02 21:50:30,814 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1492, in all
2015-11-02 21:50:30,815 STDERR                   ERROR    return list(self)
2015-11-02 21:50:30,815 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1715, in instances
2015-11-02 21:50:30,815 STDERR                   ERROR    rows = [process[0](row, None) for row in fetch]
2015-11-02 21:50:30,815 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/mapper.py", line 2290, in _instance
2015-11-02 21:50:30,816 STDERR                   ERROR    state._run_on_load(instance)
2015-11-02 21:50:30,816 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/state.py", line 142, in _run_on_load
2015-11-02 21:50:30,816 STDERR                   ERROR    self.manager.events.run('on_load', instance)
2015-11-02 21:50:30,816 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/attributes.py", line 919, in run
2015-11-02 21:50:30,816 STDERR                   ERROR    fn(*args)
2015-11-02 21:50:30,817 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/eos/saveddata/cargo.py", line 50, in init
2015-11-02 21:50:30,817 STDERR                   ERROR    self.__itemModifiedAttributes.original = self.__item.attributes
2015-11-02 21:50:30,817 STDERR                   ERROR    AttributeError
2015-11-02 21:50:30,817 STDERR                   ERROR    :
2015-11-02 21:50:30,817 STDERR                   ERROR    'NoneType' object has no attribute 'attributes'
```

Need to wrap this in a `getattr()` maybe.

```
2015-11-02 21:19:14,803 STDERR                   ERROR    Traceback (most recent call last):
2015-11-02 21:19:14,804 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/__boot__.py", line 32, in <module>
2015-11-02 21:19:14,804 STDERR                   ERROR    _run('pyfa.py')
2015-11-02 21:19:14,804 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/__boot__.py", line 29, in _run
2015-11-02 21:19:14,804 STDERR                   ERROR    execfile(path, globals(), globals())
2015-11-02 21:19:14,804 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/pyfa.py", line 97, in <module>
2015-11-02 21:19:14,805 STDERR                   ERROR    MainFrame()
2015-11-02 21:19:14,805 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/mainFrame.py", line 136, in __init__
2015-11-02 21:19:14,805 STDERR                   ERROR    self.additionsPane = AdditionsPane(self.FitviewAdditionsPanel)
2015-11-02 21:19:14,805 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/additionsPane.py", line 62, in __init__
2015-11-02 21:19:14,806 STDERR                   ERROR    self.notebook.AddPage(CargoView(self.notebook), "Cargo", tabImage = cargoImg, showClose = False)
2015-11-02 21:19:14,806 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/cargoView.py", line 50, in __init__
2015-11-02 21:19:14,806 STDERR                   ERROR    d.Display.__init__(self, parent, style=wx.LC_SINGLE_SEL | wx.BORDER_NONE)
2015-11-02 21:19:14,807 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/display.py", line 58, in __init__
2015-11-02 21:19:14,807 STDERR                   ERROR    col = colClass(self, paramDict)
2015-11-02 21:19:14,807 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/gui/builtinViewColumns/attributeDisplay.py", line 33, in __init__
2015-11-02 21:19:14,807 STDERR                   ERROR    info = sAttr.getAttributeInfo(params["attribute"])
2015-11-02 21:19:14,808 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/service/attribute.py", line 33, in getAttributeInfo
2015-11-02 21:19:14,808 STDERR                   ERROR    info = eos.db.getAttributeInfo(identity, eager=("icon", "unit"))
2015-11-02 21:19:14,808 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/eos/db/gamedata/queries.py", line 56, in checkAndReturn
2015-11-02 21:19:14,809 STDERR                   ERROR    return function(*args, **kwargs)
2015-11-02 21:19:14,809 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/eos/db/gamedata/queries.py", line 225, in getAttributeInfo
2015-11-02 21:19:14,809 STDERR                   ERROR    result = gamedata_session.query(AttributeInfo).options(*processEager(eager)).filter(filter).one()
2015-11-02 21:19:14,810 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1561, in one
2015-11-02 21:19:14,812 STDERR                   ERROR    ret = list(self)
2015-11-02 21:19:14,812 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1708, in instances
2015-11-02 21:19:14,813 STDERR                   ERROR    fetch = cursor.fetchall()
2015-11-02 21:19:14,813 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/engine/base.py", line 2499, in fetchall
2015-11-02 21:19:14,816 STDERR                   ERROR    self.cursor, self.context)
2015-11-02 21:19:14,816 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/engine/base.py", line 2493, in fetchall
2015-11-02 21:19:14,817 STDERR                   ERROR    l = self.process_rows(self._fetchall_impl())
2015-11-02 21:19:14,817 STDERR                   ERROR      File "/Users/Downloads/pyfa.app/Contents/Resources/lib/python2.7/sqlalchemy/engine/base.py", line 2460, in _fetchall_impl
2015-11-02 21:19:14,817 STDERR                   ERROR    return self.cursor.fetchall()
2015-11-02 21:19:14,818 STDERR                   ERROR    sqlalchemy.exc
2015-11-02 21:19:14,818 STDERR                   ERROR    .
2015-11-02 21:19:14,818 STDERR                   ERROR    DatabaseError
2015-11-02 21:19:14,818 STDERR                   ERROR    :
2015-11-02 21:19:14,818 STDERR                   ERROR    (DatabaseError) database disk image is malformed None None
```

Here it looks like there's an issue accessing the database, which is odd.  Also from 2015....

```
2015-09-23 21:31:41,307 STDERR                   ERROR    Traceback (most recent call last):
2015-09-23 21:31:41,307 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/gui/builtinViews/fittingView.py", line 166, in OnMouseMove
2015-09-23 21:31:41,308 STDERR                   ERROR    tooltip = self.activeColumns[col].getToolTip(mod)
2015-09-23 21:31:41,308 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/gui/builtinViewColumns/state.py", line 42, in getToolTip
2015-09-23 21:31:41,308 STDERR                   ERROR    if isinstance(mod, Module) and not mod.isEmpty:
2015-09-23 21:31:41,308 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/eos/saveddata/module.py", line 132, in isEmpty
2015-09-23 21:31:41,308 STDERR                   ERROR    return self.dummySlot is not None
2015-09-23 21:31:41,308 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/attributes.py", line 163, in __get__
2015-09-23 21:31:41,308 STDERR                   ERROR    instance_dict(instance))
2015-09-23 21:31:41,308 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/attributes.py", line 383, in get
2015-09-23 21:31:41,309 STDERR                   ERROR    value = callable_(passive=passive)
2015-09-23 21:31:41,309 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/state.py", line 281, in __call__
2015-09-23 21:31:41,309 STDERR                   ERROR    self.manager.deferred_scalar_loader(self, toload)
2015-09-23 21:31:41,309 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/mapper.py", line 2466, in _load_scalar_attributes
2015-09-23 21:31:41,309 STDERR                   ERROR    only_load_props=attribute_names)
2015-09-23 21:31:41,310 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1875, in _get
2015-09-23 21:31:41,310 STDERR                   ERROR    return q.one()
2015-09-23 21:31:41,310 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1561, in one
2015-09-23 21:31:41,311 STDERR                   ERROR    ret = list(self)
2015-09-23 21:31:41,311 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1604, in __iter__
2015-09-23 21:31:41,311 STDERR                   ERROR    return self._execute_and_instances(context)
2015-09-23 21:31:41,311 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/query.py", line 1609, in _execute_and_instances
2015-09-23 21:31:41,311 STDERR                   ERROR    mapper=self._mapper_zero_or_none())
2015-09-23 21:31:41,312 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/session.py", line 700, in execute
2015-09-23 21:31:41,312 STDERR                   ERROR    return self._connection_for_bind(engine, close_with_result=True).execute(
2015-09-23 21:31:41,312 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/session.py", line 641, in _connection_for_bind
2015-09-23 21:31:41,312 STDERR                   ERROR    return self.transaction._connection_for_bind(engine)
2015-09-23 21:31:41,312 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/session.py", line 301, in _connection_for_bind
2015-09-23 21:31:41,312 STDERR                   ERROR    self._assert_is_active()
2015-09-23 21:31:41,312 STDERR                   ERROR      File "/Users/Downloads/pyfa 2.app/Contents/Resources/lib/python2.7/sqlalchemy/orm/session.py", line 233, in _assert_is_active
2015-09-23 21:31:41,313 STDERR                   ERROR    "The transaction is inactive due to a rollback in a "
2015-09-23 21:31:41,313 STDERR                   ERROR    sqlalchemy.exc
2015-09-23 21:31:41,313 STDERR                   ERROR    .
2015-09-23 21:31:41,313 STDERR                   ERROR    InvalidRequestError
2015-09-23 21:31:41,313 STDERR                   ERROR    :
2015-09-23 21:31:41,313 STDERR                   ERROR    The transaction is inactive due to a rollback in a subtransaction.  Issue rollback() to cancel the transaction.
```

Eww.  Rollback. :/

------

In addition to the stacktraces, we are getting a _ton_ (a truly insane number) of:
`2015-10-26 17:57:45,991 eos.saveddata.module     ERROR    Item (id: 0) is not a Module`

We are also seeing some:
```
2016-11-25 09:10:54,486 eos.saveddata.module     ERROR    Item (id: 4262) does not exist
2016-11-25 16:25:26,714 service.market           ERROR    Could not get item: [Empty High slot]
2016-11-26 16:23:56,678 service.market           ERROR    Could not get item: Skirmish Warfare Link - Rapid Deployment II
2016-11-27 04:55:55,115 eos.saveddata.module     ERROR    Item (id: 11014) does not exist
```

I suspect that your fix for T3Cs and slot numbers changing will help with those. But should look into the first one especially, seems odd that we're getting so many item IDs of 0 (604 in this file, granted it goes back to 2015....).  That's the one error that's been consistent.

**Comment by blitzmann** [comment] 2017-01-27 21:23
Which os x version are you running? The deprecated one doesn't work for newer versions iirc. ( 10.11+)

**Comment by JoshuaNotowitz** [comment] 2017-01-27 21:26
I'm on 10.12.2 Is the no way to get it to work because the non deprecated versions seems to run dreadfully slow and I feel like the deprecated version ran much faster.

**Comment by Ebag333** [comment] 2017-01-27 21:48
I shot a cleaned up version of your database back to you.  Please make sure you backup the original first.

So what changed between the last time that Pyfa worked and now?

**Comment by blitzmann** [comment] 2017-01-27 21:57
Unfortunately apple seems to have everything made changes that prevented the old deprecated builds from working. I don't know enough about Mac development to be much more use.

I'm aware that the non deprecated version runs like shit on 10.11+. again, Apple seems to have dinner changed something that causes the underlying wxwidgets to run like crap. I haven't yet attempted building new binaries on these newer os x releases since it's a pita, it's possible that would solve it. But I wouldn't bet on it.

We just do the have a dev that is knowledgeable on the os x side of things, so it's very difficult. Worse case scenario, use wine and the windows release :/

**Comment by Ebag333** [comment] 2017-01-27 22:06
>Worse case scenario, use wine and the windows release :/

What about running it straight out of pyCharm?

Now that we have `requirements.txt`, should make it much easier to setup.  (Would still need wx and a few other things of course.)

**Comment by Ebag333** [comment] 2017-01-29 19:20
>I shot a cleaned up version of your database back to you. Please make sure you backup the original first.
>So what changed between the last time that Pyfa worked and now?

@JoshuaNotowitz did you have a chance to try the cleaned DB?

Any insight into what changed between the last time Pyfa worked and now?

**Comment by JoshuaNotowitz** [comment] 2017-01-30 04:39
sounds like it was just that I updated my laptop to the latest version.  the cleaned up db had no affect on the speed of the non deprecated version and the deprecated version still does not launch.

**Comment by blitzmann** [comment] 2017-01-30 04:58
> to the latest version

of os x? Yeah, that would do it.

It's been a while since I've tested the non-deprecated version in 10.11+. What exactly is sluggish about it? I know that the stats "gauges" were really slow (doing animation was very slow, and you now have the option to disable the gauge animations in the preferences). But what else specifically is up with the client?

I'm wanting to set up another hackintosh soon and maybe try rebuilding the binaries to hopefully get better performance out of it. But I can't promise anything happening soon :(

**Comment by JoshuaNotowitz** [comment] 2017-01-30 19:10
it seems that the latest pyfa patch has fixed the deprecated version, and they both seem to a bit faster. but as far as sluggishness goes loading a ship for the first time in a session can take 10-15 seconds, putting on several modules in a short time, like putting guns on, can take several seconds per module.  other than those specific cases is mostly just occasional sluggishness and slow response times.

**Comment by blitzmann** [comment] 2017-01-30 19:21
>it seems that the latest pyfa patch has fixed the deprecated version

(╯°□°）╯︵ ┻━┻

**Comment by blitzmann** [comment] 2017-02-09 03:47
@JoshuaNotowitz 

Can you check this build for me? It includes more changes, and I haven't been able to verify if it works yet, and want to know if it still runs on you os x version

http://eve-files.com/dl/280807

**Comment by JoshuaNotowitz** [comment] 2017-02-09 09:44
That build crashes immediately on launch with this screen <img width="461" alt="screenshot 2017-02-09 01 36 55" src="https://cloud.githubusercontent.com/assets/8390690/22777669/d5ac4274-ee68-11e6-810c-e636bd9d6623.png">
http://homepages.cwi.nl/~jack/macpython/index.html is the website "Visit the MacPython Website" points to, last updated in 2004

**Comment by blitzmann** [comment] 2017-02-09 15:12
@JoshuaNotowitz 

> http://homepages.cwi.nl/~jack/macpython/index.html is the website "Visit the MacPython Website" points to, last updated in 2004

Yeah, I have no idea why that points to that. v0v

I'll take a look tonight and see if I can get it to work. In the mean time, can you try running it via terminal (`> pyfa.app/Contents/MacOS/pyfa`) and see if it outputs anything?

**Comment by JoshuaNotowitz** [comment] 2017-02-09 19:26
```
Joshuas-MacBook-Pro:~ Joshua$ /Users/Joshua/Downloads/pyfa.app/Contents/MacOS/pyfa ; exit;
Traceback (most recent call last):
  File "/Users/Joshua/Downloads/pyfa.app/Contents/Resources/__boot__.py", line 32, in <module>
    _run('pyfa.py')
  File "/Users/Joshua/Downloads/pyfa.app/Contents/Resources/__boot__.py", line 29, in _run
    execfile(path, globals(), globals())
  File "/Users/Joshua/Downloads/pyfa.app/Contents/Resources/pyfa.py", line 138, in <module>
    MainFrame(options.title)
  File "/Users/Joshua/Downloads/pyfa.app/Contents/Resources/gui/mainFrame.py", line 153, in __init__
    self.disableOverrideEditor = disableOverrideEditor
NameError: global name 'disableOverrideEditor' is not defined
2017-02-09 11:24:37.473 pyfa[6871:1278703] pyfa Error
2017-02-09 11:24:37.473 pyfa[6871:1278703] pyfa Error
```

**Comment by Ebag333** [comment] 2017-02-09 19:37
Likely means this failed to import:
`from gui.propertyEditor import AttributeEditor`

@blitzmann the PR I just submitted has a fix for this specific error.  I  don't remember _why_ `AttributeEditor` did not import though.

**Comment by blitzmann** [comment] 2017-02-14 03:54
This has been fixed in master, will be available in the next release in a couple days.

a4de0f2b5bdc6d069f96c9e8198df3bd0c13ed4b

**Closed** 2017-02-17 04:44 UTC
Labels: bug, fixed
