### ISSUE TITLE
Crash when opening module stats

### ISSUE THREAD

**Issue by DerMika** [pyfa-org/Pyfa#2188] opened 2020-05-15 12:34 UTC
## Bug Report

When right-clicking a gyrostabilizer and clicking "module stats" i got the stacktrace below:

pyfa v2.20.3
EVE Data Version: 1706308 (2020-04-15 10:32:35)

OS version: Darwin-19.4.0-x86_64-i386-64bit
Python version: 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.16
Logbook version: 1.5.3
Requests version: 2.23.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui/contextMenu.py", line 174, in handler
  File "gui/contextMenu.py", line 307, in _baseActivate
  File "gui/builtinContextMenus/itemStats.py", line 71, in activate
  File "gui/itemStats.py", line 96, in __init__
  File "gui/itemStats.py", line 172, in __init__
  File "gui/builtinItemStatsViews/itemAttributes.py", line 67, in __init__
  File "gui/builtinItemStatsViews/itemAttributes.py", line 209, in PopulateList
  File "gui/builtinItemStatsViews/itemAttributes.py", line 174, in SetupImageList
TypeError: ImageList.Add(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'NoneType'
  overload 2: argument 1 has unexpected type 'NoneType'
  overload 3: argument 1 has unexpected type 'NoneType'

### Detailed steps to reproduce:

open this fit, right-click a gyro, click "module stats"

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Tempest, deeps]

Damage Control II
1600mm Steel Plates II
Gyrostabilizer II
Gyrostabilizer II
Energized Adaptive Nano Membrane II
Gyrostabilizer II

[Empty Med slot]
Faint Epsilon Scoped Warp Scrambler
Fleeting Compact Stasis Webifier
[Empty Med slot]
Medium Capacitor Booster II

800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile

Large Anti-Explosive Pump I
Large Trimark Armor Pump I
Large Trimark Armor Pump I

Garde II x3

Navy Cap Booster 800 x1
EMP L x1

### Release or development git branch? Please note the release version or commit hash:

release v2.20.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Mac OSX Darwin-19.4.0-x86_64-i386-64bit

**Comment by DarkFenX** [comment] 2020-05-21 08:04
Seems like it fails to fetch `pyfa/imgs/gui/transparent16x16.png` for some reason. But since images are compressed into binary on macOS, it's harder than normally to debug it. I will try to reproduce it on my mac before making the following release.

**Comment by DarkFenX** [comment] 2020-06-15 16:03
@DerMika I've checked it on my Mac and cannot reproduce it on latest release. Could you check if it is still an issue for you?

**Comment by DerMika** [comment] 2020-06-18 18:49
I can't reproduce it either anymore on v2.22.0

**Comment by DarkFenX** [comment] 2020-06-18 18:55
Okay, probably icon update (or something else) solved it. Closing.

**Closed by DarkFenX** 2020-06-18 18:55 UTC
