### ISSUE TITLE
crash @ start

### ISSUE THREAD

**Issue by xMADDINx** [pyfa-org/Pyfa#1156] opened 2017-05-11 08:28 UTC
YC119.5 - v1.29.0

OS version: 	Windows-8-6.2.9200 ?  my os ist Win 10
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.0 Stable - YC119.5 1.0
pyfa root: C:\Users\xMADDINx\Desktop\pyfa
save path: C:\Users\xMADDINx\.pyfa
fs encoding: mbcs

EXCEPTION: (sqlite3.OperationalError) table damagePatterns has 9 columns but 7 values were supplied [SQL: 'INSERT INTO damagePatterns VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: (1, 'Uniform', 25, 25, 25, 25, None)]

  File "C:\python-2.7.10\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "C:\Users\xMADDINx\Desktop\pyfa\library.zip\pyfa__main__.py", line 373, in <module>
  File "C:\Users\xMADDINx\Desktop\pyfa\library.zip\service\prefetch.py", line 40, in <module>
  File "C:\Users\xMADDINx\Desktop\pyfa\library.zip\eos\db\migration.py", line 41, in update
    func(saveddata_engine)
  File "C:\Users\xMADDINx\Desktop\pyfa\library.zip\eos\db\migrations\upgrade6.py", line 11, in upgrade
    (1, "Uniform", 25, 25, 25, 25, None))
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 1989, in execute
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 906, in execute
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 1054, in _execute_text
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute

**Comment by blitzmann** [comment] 2017-05-11 23:32
Were you testing out the dev branch recently by any chance? 

Can you send me the contents of your `%userprofile%/.pyfa` directory to sable.blitzmann@gmail.com? It contains logs and other information that will help in figuring this out. From the looks of things, it looks like the table had the new createdate and modifydate columns added, however for some reason is trying to run a fairly old migration from when those columns didn't exist... Which doesn't make much sense since the new columns came out with this release. =/

**Comment by xMADDINx** [comment] 2017-05-11 23:59
It does not matter which version I use it crashes. I've tested it with many different.

**Comment by blitzmann** [comment] 2017-05-12 00:19
@xMADDINx please send me the `.pyfa` directoy zipped up in an email so that I may be able to better assist. It's an odd issue =/

**Comment by xMADDINx** [comment] 2017-05-12 00:20
i have send an email to your email account

**Comment by blitzmann** [comment] 2017-05-12 00:23
Awesome, thanks. I'll take a look at it :)

**Comment by blitzmann** [comment] 2017-05-12 00:30
@xMADDINx which version were you using before you updated to v1.29? Are you a newer user of pyfa, or have you been using it for a long time? 

Sorry about the questions, but I would like to figure out why your database looks so funky

**Comment by xMADDINx** [comment] 2017-05-12 00:34
https://github.com/Pyfa-fit/Pyfa-fit 26.04.2016_v2 with this version the problem starts. and then i saw that your version is newer but the problem stays.  and i tested your older version and a fix of your version. but the problem stays. :(

**Comment by blitzmann** [comment] 2017-05-12 00:35
This is why I'm confused...

![image](https://cloud.githubusercontent.com/assets/3904767/25977328/e2161716-3688-11e7-9aee-e84c02e53f2a.png)

So the first migration took place 4/28, and only went from version 0 to version 1. This is _very_ strang. If you started using pyfa a couple weeks ago, it would have went from version 0 to something like 21. Then the version increments by 1, which again is very odd, because again, it should migrate all the way to the latest version. 

Additionally, it seem that the first migration database has columns that were added to dev versions of pyfa and only released with v1.29.0, so I'm wondering why this is like this...

**Comment by Ebag333** [comment] 2017-05-12 00:36
Do you get that using my branch? 

DB wise, it should match this branch.

**Comment by xMADDINx** [comment] 2017-05-12 00:38
i used your branch frist the it chrashed @ start and i looked for an update and found blitzmans version but this chrashes @ start

**Comment by blitzmann** [comment] 2017-05-12 00:38
> https://github.com/Pyfa-fit/Pyfa-fit 26.04.2016_v2 with this version the problem starts. and then i saw that your version is newer but the problem stays. and i tested your older version and a fix of your version. but the problem stays. :(

Oh, well this explains a lot. pyfa-fit is not the official pyfa application. It's developed separately, and apparently broke things with migrations.

@Ebag333 this is exactly why I wanted you to change your suser database file. FFS

@xMADDINx the fix to this is simple: delete everything in your `.pyfa` directory and start anew. Sorry for the confusion, but such is why happens when someone else forks an established product.

As a reminder, official pyfa releases are always found here: https://github.com/pyfa-org/Pyfa/releases/latest

**Comment by xMADDINx** [comment] 2017-05-12 00:39
problem solved iver deleted .pyfa and it works

**Closed** 2017-05-12 00:39 UTC

**Comment by xMADDINx** [comment] 2017-05-12 00:40
thanks for your help :)

**Comment by Ebag333** [comment] 2017-05-12 01:16
>Oh, well this explains a lot. pyfa-fit is not the official pyfa application. It's developed separately, and apparently broke things with migrations.

Nope. Migrations are the same. 

>@Ebag333 this is exactly why I wanted you to change your user database file. FFS

This is why I wanted to work with you. 

>@xMADDINx the fix to this is simple: delete everything in your .pyfa directory and start anew. 

@xMADDINx sorry to hear you had an issue with it. If you want to have a more elegant answer than "delete everything" let me know. 

I will continue to maintain cross compatibility with Pyfa-org, so you can go back and forth if you like to.

>but such is why happens when someone else forks an established product.

And the dozens of crashes is what happens when you ignore the work that the most active dev does. 😂

**Comment by alexandre75** [comment] 2017-05-15 21:59
Hello I've the same issue since I've upgraded from 
pyfa-1.28.1-yc119.3-1.0-linux.zip -> pyfa-1.29.1-yc119.5-1.0-linux.zip

I could downgrade both the binaries and the db and fixed the issue.

Any idea how I could have 1.29.1 binaries work without trashing my db?

**Comment by Ebag333** [comment] 2017-05-21 19:20
>@Ebag333 this is exactly why I wanted you to change your user database file. FFS

So just to comment on this to clear it up, this is _not_ being caused by users using Pyfa.fit.  migration 23 or 24 fails to run for <reasons> (haven't figured out why), and the DB version gets reverted back to whatever number it started on, and several migrations don't understand the new DB schema.

@alexandre75 I don't know if you're still looking at this, but if you want to email me your DB (`ebagola@gmail.com`) I can fix it for you.
