### ISSUE TITLE
Phantasm

### ISSUE THREAD

**Issue by ANDEN10** [pyfa-org/Pyfa#525] opened 2016-03-04 11:26 UTC
i've found that the Fall-off is not changing on medium sized laser's

**Comment by blitzmann** [comment] 2016-03-06 03:09
I cannot reproduce. Per the trait, you get 7.5% bonuses per Amarr Cruiser skill level. The following image shows a Heavy Pulse Laser I (medium sized laser) fitted to a Phantasm. First image is All 0 showing base stats of the module, second image is Amarr Cruiser 1 showing `0.0813 * 1.075 = 0.0873`, which is expected. Third image is Amarr Cruiser 5 showing `0.0813 * 1.375 = 0.112`, which is also expected.

![capture](https://cloud.githubusercontent.com/assets/3904767/13552044/4d37ee8a-e31e-11e5-8480-6255ed222ec5.PNG)

Closing this issue as it's invalid. However, if you are still having issues and believe it's still wrong, please let me know, and post a bit more info (exact fit, what you are getting vs what you are expecting, make sure pyfa is up to date, etc). The more info I get the more I can help

Thanks =)

**Closed by blitzmann** 2016-03-06 03:09 UTC

**Comment by ANDEN10** [comment] 2016-03-06 03:14
I said fall off doesn't change, track speed is fine, I said FALL OFF. Ingame falloff with scorch is 22km in pyfa falloff is 7.5km falloff doesn't change at all with the changing of crystals

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 6, 2016 at 6:10 AM, blitzmann<notifications@github.com> wrote:   
Closed #525.

**Comment by blitzmann** [comment] 2016-03-06 04:53
Continued at #526
