### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by oovarvu** [pyfa-org/Pyfa#1182] opened 2017-05-19 10:37 UTC
## Bug Report  

this showed up, i had just finished pulling updated api for the characters i have in pyfa and returned to tinker with fis there were several of these windows but as far as i could see they all said the same thing

```
OS version: 	Windows-7-6.1.7601-SP1
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.2 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\1st\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'name'

  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 555, in spawnMenu
    menu = ContextMenu.getMenu(selection, *contexts)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\contextMenu.py", line 85, in getMenu
    sub = m.getSubMenu(srcContext, selection, rootMenu, it, rootItem)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinContextMenus\changeAffectingSkills.py", line 88, in getSubMenu
    bitmap = BitmapLoader.getBitmap("lvl%s" % skill.level, "gui")
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 337, in level
    if self.character.name == "All 5":
```

**Comment by blitzmann** [comment] 2017-05-20 06:03
Thanks for the bug report! Some other folks have stated that they've run into this issue as well (or something similar, which was thought to have been fixed in the latest release). Can you reproduce it consistently?

**Comment by blitzmann** [comment] 2017-05-21 23:32
@oovarvu Can you reproduce this consistently, or is it very intermittent? Can you also please send me `C:\Users\1st\.pyfa` zipped up to sable.blitzmann@gmail.com? It contains database and logs, and will hopefully help determine the cause of this :)

**Comment by oovarvu** [comment] 2017-06-20 14:43
hi

sorry for the delay. no i can't repropduce it and on the whole i find pyfa
very stable, and i have found that deleting old update data and fits helps
greatly with speed. anyway great work bud hope you will be able to keep it
up. your efforts are really appreciated.

**Comment by blitzmann** [comment] 2018-05-28 23:05
Closing this issue, I believe this particular error was addressed and fixed in another issue. On top of that, with the new ESI support in pyfa 2.x, not sure if we're using the same mechanisms that this issue touches upon.

If you run into any other issues, feel free to open another issue with details. Thanks!

**Closed by blitzmann** 2018-05-28 23:05 UTC
