### ISSUE TITLE
Target Resist Profile menu popup stops working periodically

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#651] opened 2016-06-13 22:06 UTC
After right clicking to pop open the resist profile window, it will occasionally stop responding. 

All other menus seem to work fine.  No errors in the console.  Doesn't trip the debug stuff I have in gui.contextMenu (as it does when it's working), so it's not even getting that far.

This issue predates my messing with it to do the database defaults.

**Comment by blitzmann** [comment] 2016-06-13 23:12
Any errors in the console?

**Comment by Ebag333** [comment] 2016-06-13 23:46
>No errors in the console. Doesn't trip the debug stuff I have in gui.contextMenu (as it does when it's working), so it's not even getting that far.

**Comment by Ebag333** [comment] 2016-06-13 23:48
No stack trace either, so it's not hard failing. 

Wonder if it thinks it's getting switched to mining yeild. Toggling that doesn't fix it though.

**Comment by blitzmann** [comment] 2016-06-14 01:09
Missed the bit about no errors heh.

I believe I have noticed similar issues before. When I noticed it, it would stop responding unless you right click in specific spots (like, pixel-perfect spots). I don't know what happens, and I can't reproduce all the time. It probably has something to do with the bindings, especially if the mining stats are toggled.

**Comment by Ebag333** [comment] 2016-06-14 03:07
That sounds like it to me.

What if we just relocate it to a dedicated button for profiles?  I'd like to see the resists profile displayed anyway (since it's hidden, and you'll come back to a ship a week later and wonder WTF it has such terrible DPS).

It's also bugged me that there's not a dedicated button for switching damage profiles, even though there's a perfect spot for it.

If we put a similar bar graph as the current damage profiles in place as resist profiles, there'd be a wonderful gap to the right that would be the perfect size for a button.  See existing spot next to damage profiles:

http://puu.sh/prXg5/0e023e69ac.png

Multi function buttons tend to be confusing for end users, and I'm not sure that there's a need for one there anyway.

**Comment by blitzmann** [comment] 2016-06-14 03:40
> I'd like to see the resists profile displayed anyway (since it's hidden, and you'll come back to a ship a week later and wonder WTF it has such terrible DPS).


This is why the firepower header has `(Effective)` on it, to signify that there are target resists in play.

There is issues with displaying more things in the stats view, namely our minimum vertical space. We are already hugging the boundaries of what we can vertically fit on a standard laptop. This is why things like target resists are not currently shown, and mining panel is toggled.

Can you explain in more detail how to envision adding another button would work out? Was kind of confused in your description.

One way we may combat this is to have the mouse cursor change if there is a context menu available. I have no idea if this would be feasible to do or how it would be done without looking at it, but it'll give a clue that there is something there (same can be done for those stats that have additional info, like lock speed)

That being said, I'm inclined to leave it as it is for now. It's not great, no, but it works. There is always the wiki section that provides more info on the lesser known uses of pyfa.

**Comment by Ebag333** [comment] 2016-06-14 05:39
Just throwing some thoughts out here.  Some are more feasible than others, but some of these would be pretty easy to implement.

If space is a concern, could move price to the fitting window.  We already have almost everything there as it is, so just add three lines at the bottom:

Fitting Cost      1234.32M
Ship                 345.7M
Total                 1590.02M

That would eliminate 3 lines worth in the display area on the right, which would free up more than enough room for a target resists profile bar.

One other way we could free up room is in the resist profiles.  Typically you don't care too much about your non-primary HP, so you could make that section a three way expansion instead of current 2 way.

Current:
1) Minimized (arrow up)
2) Everything

Three way toggle
1) Minimized (arrow up)
2) Primary tank (tank with greatest EHP, arrow to right)
3) Everything (arrow down)

That would eliminate two more lines.

Another option might be to have a toggle on the targeting & misc section ala the firepower section.  It's fairly rare that you need to see *all* those values, fitting/resists/damage/cap are the four primary ones that need to be up.  So could move price under targeting & misc as a toggle, and have various toggles.  Maybe something like:
1) Targeting (targets, targeting range, scan res, sensor strength)
2) Navigation (speed, align, signature, warp speed)
3) Drones (drone range, # of drones used, amount of drone bay used)
4) Cargo (current cargo used)
5) Price (fold price into)
6) Harvesting amount (it kinda sorta doesn't make sense to have this a toggle from DPS, since you often want to see how much DPS you can do while you're fitting your mining boats, as it's defense from rats, gankers, etc)

As for example of what I was thinking for a button, something like this.  But prettier.
http://puu.sh/ps3uS/e7bab8484f.png

**Comment by Ebag333** [comment] 2017-03-14 22:58
@blitzmann I haven't seen this happen in ages (since we did all the refactoring), have you?

If not, I'd suggest we close this.

**Comment by blitzmann** [comment] 2017-03-23 02:17
Thought I closed this. If you notice it, please reopen. Thanks for the info :)

**Closed by blitzmann** 2017-03-23 02:17 UTC
Labels: bug
