### ISSUE TITLE
Mac Deprecated version no longer works on macOS sierra version 10.12

### ISSUE THREAD

**Issue by JoshuaNotowitz** [pyfa-org/Pyfa#780] opened 2016-10-21 21:59 UTC
As is it says in the tittle the program doesn't launch it just bounces in the dock.  This wouldn't be a problem but, at least on my machine, the non deprecated version is measurable worse in regards to performance and ease of use.

**Comment by blitzmann** [comment] 2016-10-21 22:32
Unfortunately I don't think there's anything I can do about it, unless we bring on a developer with mac experience. I simply don't have the time myself to get a copy of 10.12, go through the process of installing it as a hackintosh, and testing / developing on it.

Could you open the package file, browser to `Contents/MacOS`, and run the `pyfa` file in the terminal? Hopefully it pops up with an error that is useful.

Also, i know the wx3 version is less than ideal for anyone >10.10 (or 10.11, don't remember) due to performance, but what exactly are you having problems with?

**Comment by Ebag333** [comment] 2016-10-21 22:33
Isn't there a beta wxPython version for newer macs?

**Comment by JoshuaNotowitz** [comment] 2016-10-22 00:47
> Joshua$ /Users/Joshua/Downloads/pyfa\ 2.app/Contents/MacOS/pyfa ; exit;
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

> [Process completed]

Is what it says terminal when I try to launch it.  And as far as problems its mostly just a general slow down as compared to before with the deprecated version.  Search results load slower and ship fits load slower.

**Comment by blitzmann** [comment] 2016-10-22 01:57
> Isn't there a beta wxPython version for newer macs?

Are you talking about wxPython Pheonix? That's a thing, but it's incompatible with Classic (and might be only python 3, not sure). It could help, and converting wouldn't be too diffult, just time consuming, and I don't know if it'll help.

> Is what it says terminal when I try to launch it. And as far as problems its mostly just a general slow down as compared to before with the deprecated version. Search results load slower and ship fits load slower.

yeah, that error doesn't help at all. =/ You're gonna have to go with the new version. I know it's not optimal, but my hands are tied at the moment. I know that it's slow and sluggish. There is an option in the preferences to disable animations that help with the stats panel updating.

Or, you could always try the Windows release in Wine. >_>

**Comment by blitzmann** [comment] 2016-10-22 01:58
Would you be able to run pyfa from source? Do you have the tools / know how to do so?

**Comment by JoshuaNotowitz** [comment] 2016-10-22 03:44
I don't think I would be able to I'm not very technically skilled 😄

**Comment by blitzmann** [comment] 2017-01-30 19:35
Duplicate of #954

**Closed by blitzmann** 2017-01-30 19:35 UTC
