### ISSUE TITLE
Feature: Compare Fittings

### ISSUE THREAD

**Issue by ErrZwoDehZwo** [pyfa-org/Pyfa#2149] opened 2020-03-19 02:45 UTC
Hey folks,

since in most alliances/coalitions in EVE you have multiple fittings for one ship, it would be nice to see the difference between fittings of the same hull. If this possible, this would be an greate improvement ! -

Kindly,
Joseph / Keve Rezal (Ingame)

**Comment by DarkFenX** [comment] 2020-04-06 07:17
Duplicate of #2127

**Closed by DarkFenX** 2020-04-06 07:17 UTC
