### ISSUE TITLE
Capital Ancillary Armor Repairer not showing correct repair amount in attributes window when nanite paste is loaded. 

### ISSUE THREAD

**Issue by xErgoProxyx** [pyfa-org/Pyfa#2383] opened 2021-11-27 19:37 UTC
Hello,

We were playing with some fits and I've found a discrepancy between Pyfa and the Eve Simulation that we've tested - the attributes page when looked at, does not display the corresponding value that the in game simulator does. It does show the value after Siege Module II bonuses are applied as 9600HP Per Cycle, which is correct, but the value after Nanite Paste is added does not update to the correct amount repaired per cycle.

It does update the the EHP/s when loading Nanite Paste but we're not sure with that attribute value in the module stats window being off it that's possibly affecting any accuracy.

**Comment by DarkFenX** [comment] 2021-11-28 10:07
I just checked stats of my AAR in-game and it does not show amount of reps tripled with paste loaded. It was intentional decision to keep it consistent with in-game values.

Is ghost fitting any different in this regard?

**Comment by xErgoProxyx** [comment] 2021-12-02 11:49
Ah I see what you're saying - you're right, the module stats don't change under the module info tab, but the reps do triple in the fitting window when paste is added. I'm attaching an SS of the in-game value change to show where the confusion came in. 

https://imgur.com/a/8VP8y2d

**Comment by DarkFenX** [comment] 2021-12-02 13:21
Pyfa takes paste into account when it displays amount of EHP repaired in main fitting pane "misc" column or in any of stats panes. But yeah in item attribute themselves it's kept unmodified just like in game. Closing this as not a bug.

**Closed by DarkFenX** 2021-12-02 13:21 UTC
