### ISSUE TITLE
Multiple Interdiction Sphere Launcher I's allowed to be fitted

### ISSUE THREAD

**Issue by robmburke** [pyfa-org/Pyfa#1278] opened 2017-09-11 13:51 UTC
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

### Expected behavior:
Module presence on a ship should be limited to a single Interdiction Sphere Launcher I per the module limitations

### Actual behavior:
Pyfa allows 2 Launchers to be fitted

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Flycatcher, Flycatcher]

Ballistic Control System II

5MN Y-T8 Compact Microwarpdrive
X5 Enduring Stasis Webifier
X5 Enduring Stasis Webifier
Sensor Booster II, Scan Resolution Script
Caldari Navy Medium Shield Extender

Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Interdiction Sphere Launcher I, Warp Disrupt Probe
Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Interdiction Sphere Launcher I, Warp Disrupt Probe

Small Polycarbon Engine Housing II
Small Polycarbon Engine Housing II

Warp Disrupt Probe x50
Scourge Rage Rocket x700
Nanite Repair Paste x200
Surgical Warp Disrupt Probe x20

### Release or development git branch? Please note the release version or commit hash:
1.31.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by burnsypet** [comment] 2017-09-14 21:11
@robmburke Could you please let me know what steps you took to get both launchers on there? I've tried copying your fit but the second is automatically removed, and I am unable to either double-click or drag a second launcher onto the ship.

**Comment by robmburke** [comment] 2017-09-14 21:15
Oh, CTRL-Drag from one already being fitted on the ship.

**Comment by robmburke** [comment] 2017-09-14 21:16
What was interesting is that Eve doesn't check that and lets it be displayed in the import view, but then, obviously, won't fit it when you flick the Fit button to create the ship.

**Comment by burnsypet** [comment] 2017-09-14 22:16
Interesting I had no idea that was even a feature. It seems like when we do a clone module there isn't any validation to check if that module is valid, will try and fix tomorrow.

**Comment by blitzmann** [comment] 2017-09-19 05:13
> Oh, CTRL-Drag from one already being fitted on the ship.

You sneaky bastard... :P

It's weird that you can only do this once, after which it will no longer clone.

@burnsypet did you get very far? I have a few other things that I need to look into before I get to this as it's fairly low priority, but if you haven't gotten anywhere I would be happy to take a look asap :)

**Comment by blitzmann** [comment] 2017-09-22 06:40
Took a look at this today, the source of the issue is the following

https://github.com/pyfa-org/Pyfa/compare/bug/1278

In situations where you're moving cargo to the fitting window, `self.owner` is always going to point to the fit that we are fitting the module to, so it's always going to start the count at `-1`. I'm not exactly sure the original reasoning behind this - that line is from way back when pyfa first got started, before the eos engine was part of the repo. Back then, there was no cargo support, copying modules around probably wasn't really a thing... I'm not sure why the counter started differently based on the modules parent as we lost historical commit messages when that part of the code base was permanently moved into pyfa in 2013

This seems to work, but I will be doing a bit more testing on it tomorrow. Hopefully I will get it merged in and released by this weekend if everything goes well

**Closed** 2017-09-24 22:38 UTC
Labels: bug, fixed
