### ISSUE TITLE
Import Fittings failed

### ISSUE THREAD

**Issue by Altarus94** [pyfa-org/Pyfa#1985] opened 2019-05-24 21:48 UTC
## Bug Report

I exported my fits from pyfa v2.9.4dev3 (or dev2, not sure) before reformatting. I just reinstall windows and try to import them on my new Pyfa install. v2.9.4dev3
It failed to import.

### Expected behavior:

Old fittings to appear in the new pyfa installation

### Actual behavior:

Pyfa sits in "Processing file:" for xml dump indefinitely, elapsed time remains at 0:00:00, then close after 10 to 20s.
![image](https://user-images.githubusercontent.com/39195083/58358212-44fe3400-7e7e-11e9-9a23-65fe98d02f08.png)

### Detailed steps to reproduce:

Source => file -> backup all fittings -> save in Documents
Recipient => fit -> Import Fittings -> window open, then close without doing nothing

### Fits involved in EFT format (Edit > To Clipboard > EFT):
All of them?
Will not release them publicly. We can talk about that in private. 

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.9.4dev3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Fresh install of W10 pro

### Other relevant information:
The top of the xml file:
```
<?xml version="1.0" ?>
<fittings count="1513">
```

You can contact me via PM if you need more informations

**Comment by DarkFenX** [comment] 2019-05-24 22:07
Send the file to phoenix@mail.ru. I am unable to reproduce it on my database.

**Comment by Altarus94** [comment] 2019-05-24 23:00
Sent

**Comment by DarkFenX** [comment] 2019-05-25 11:11
Reproduced it, thanks. Will see what causes such behavior.

**Comment by DarkFenX** [comment] 2019-05-25 14:44
Importer was coded in a way that it accepts either all strings with localized hints or none of them. Your file has a mix. Fixed in 4fbbc18f9f5e4a3a95f942c2c5c3350c45bb5250

**Closed by DarkFenX** 2019-05-25 14:44 UTC
