### ISSUE TITLE
Pyfa exception during fitting export to CREST

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1260] opened 2017-07-25 02:51 UTC
## Bug Report

About the third fit I exported through CREST raised an error dialog instead of working. I was then logged out of CREST. Relogging and trying again produced the same behavior.

### Expected behavior:

Fit went to CREST.

### Actual behavior:

Error dialog.

### Detailed steps to reproduce:

Unknown. It is repeatable now that it has started.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Astero, SW™ Scan Club L3]

Shadow Serpentis Inertial Stabilizers
Republic Fleet Nanofiber Structure
Republic Fleet Nanofiber Structure
Thukker Micro Auxiliary Power Core

Corelum A-Type 10MN Afterburner
Scan Rangefinding Array II
Scan Rangefinding Array II
Scan Acquisition Array II

Sisters Core Probe Launcher, RSS Core Scanner Probe
Covert Ops Cloaking Device II

Small Gravity Capacitor Upgrade II
Small Anti-Explosive Pump I
[Empty Rig slot]

Hornet EC-300 x5
'Augmented' Acolyte x5
'Augmented' Warrior x5

### Exception information

OS version: 	Linux-4.11.0-2-amd64-x86_64-with-debian-buster-sid
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.11
Logbook: 	1.0.0
pyfa version: 1.30.0 Stable - YC119.7 1.0
pyfa root: /usr/local/apps/pyfa-1.30.0
save path: /home/bart/.pyfa
fs encoding: UTF-8

EXCEPTION: The C++ part of the ExportToEve object has been deleted, attribute access no longer allowed.

  File "/usr/local/apps/pyfa-1.30.0/gui/crestFittings.py", line 245, in ssoLogin
    self.updateCharList()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16710, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)

**Comment by blitzmann** [comment] 2017-09-19 04:59
Sorry for the late response.

So, I am able to export this fit just fine, I'm not sure what originally went wrong. You state that it was repeatable once it started. Was the error message you posted the same one as the first error? I'm thinking it errors out during export, but then subsequent calls ran into an issue with the ExportToEve dialog the pops up.

Can you still reproduce the error?

Honestly, with XML API and CREST going away sometime next year, I'm not sure if I'm interested in pursuing this too far, especially if you got it to work after a restart. 

As for the error that was posted, it seems that when you log into CREST, open the export to eve window, close it, log out, and then relogin, the error pops up. Seems to be a reference issue (whenever you log in, pyfa tries to notify the CREST windows that may be shown. the error here states that that C++ object has been destroyed, and so we're left with an empty python wrapper object without a lower level object representing it). This is something I will probably take a look at soon, as it can be quite annoying.

**Comment by BartMassey** [comment] 2017-09-19 23:33
I'd be fine with fixing the surface problem and waiting to see if the underlying issue reappears. As you say, everything is going to have to be redone for the new API anyhow. Thanks for looking at it.

**Comment by blitzmann** [comment] 2017-09-23 23:14
k, got a fix. Was what I expected - when we open the Export Fit window, we bind an event handler to the main window so that it can receive events on EVE Login / Logout. When the dialog closes, we never unbind those event, so when you go to log back in, it tries to send that even to a window that no longer exists. Fix was simple, and was simply an overlooked Unbind :)

**Closed** 2017-09-24 22:38 UTC
Labels: bug, fixed

**Comment by BartMassey** [comment] 2017-09-25 14:17
Thanks!
