### ISSUE TITLE
sqlAlchemy DB Restraints largely disabled

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#1121] opened 2017-04-11 02:08 UTC
So in playing around with the session issues, I've found that the DB restraints are largely ignored/disabled.

Case in point, when we swap in a dummy module, there's a hard restraint that `fitID` can't be null.  But if you query the dummy module that was just created, `dummy.fitID` is....null. 😕 

Stuff like this is easily resolved by adding a single line:
```
    def toDummy(self, index):
        mod = self[index]
        if not mod.isEmpty:
            dummy = mod.buildEmpty(mod.slot)
            dummy.position = index
            dummy.fitID = mod.fitID
            self[index] = dummy
```

(Specifically: `dummy.fitID = mod.fitID`)

But, it seems pretty endemic.  Clear that one and you get....
`EXCEPTION: (sqlite3.IntegrityError) NOT NULL constraint failed: modules.fitID [SQL: u'UPDATE modules SET "fitID"=?, modified=CURRENT_TIMESTAMP WHERE modules."ID" = ?'] [parameters: (None, 27771)]`

☹️

**Comment by Ebag333** [comment] 2017-04-11 02:10
This explains where the DB corruption is coming from at least.

**Comment by blitzmann** [comment] 2017-04-11 02:32
So, took  a look at this as it piqued my curiosity. You're both right and wrong. Right in that we don't set `fitID` when building an empty module, and we get all the way to `commit()` without setting it. Certainly confusing. 

However, we don't need to manually set `fitID` because the module is assigned that value by virtue of it being part of a fit's module collection. When that module object is committed to the database, SQLAlchemy is smart enough to know, based on the relationships that we define, that it is attached to a `Fit` object and thus assigns it that fit's ID. This is evident in a large number of SQLAlchemy tutorials, where you create a simple object and append it to another objects collection, and it inherits the parent objects attributes when committed. So this is working as intended.

The odd database corruption that has been reported may be similar or even related to this. It's generally caused by the deletes not cascading down properly (so, character skills having a bad reference to a deleted character). But it's also not all the time and no one has been able to consistently reproduce that particular issue - if it was a reference not being set correctly, I would think it would happen all the time. I personally have no leads on it (except maybe they were pretty old databases that got fucked at some point).

**Comment by Ebag333** [comment] 2017-04-11 02:47
Just thought I'd document this. No need to keep open. :)

**Closed** 2017-04-11 02:47 UTC

**Comment by blitzmann** [comment] 2017-04-11 04:15
I left it open for the time being in case you found some wonky stuff happening and wanted to respond with anymore details of said wonky stuff. If you do, please reopen and we can discuss. :D

**Comment by Ebag333** [comment] 2017-04-11 04:27
Oh there's lots of wonky stuff. Not _directly_ related to this, but still stuff that we shouldn't do.

```
    eos.config.saveddata_connectionstring = "sqlite:///" + saveDB + "?check_same_thread=False"
    eos.config.gamedata_connectionstring = "sqlite:///" + gameDB + "?check_same_thread=False"
```

`check_same_thread` is an undocumented switch.  🤔 

```
sessionmaker(bind=saveddata_engine, autoflush=False, expire_on_commit=False)
```

`autoflush` and `expire_on_commit` both default to on, there's warnings that switching them off is something that _probably_ shouldn't be done.

Unfortunately it'd take a massive refactor of how we handle the database to fix it.  We have `commit` (and other things) littered all over the place, there's no standard `create session, do stuff, commit, close session` workflow.

Technically, it's faster to never have to handle opening/closing sessions, but it's also more dangerous (changes can not get committed, especially if something bombs out early, probably a source of DB corruption) and of course it's not "standardized" so you're never going to quite be sure where you are in the process when you're touching the DB (or where other things are).
