### ISSUE TITLE
Booster nonfunctional when previous pyfa was not closed gracefully?

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#439] opened 2015-11-17 23:38 UTC
Pyfa doesn't recover on it's own from some previous bad voodoo. Should probably be able to handle bad saved data. 

Steps I did to reproduce: 
- On non-wx3, run pyfa, can't set/unset boosters at all. Repeat attempts. Restarts don't help. 
  (Right click on fit, select 'Booster Fit', observe yellow fleet icon does not toggle!, exit app)
- Open wx3 build, set the booster, no problem, yellow icon is now present. 
  (being careful not to trigger the bug #424, then exit app )
- Return to non-wx3, now able to set/unset boosters! The bad state was cured. 
  ( #424 doesn't happen on non-wx3, and it is now in a working state: set, unset, set, no prob, exit app)
- Open wx3 build again and crash it
  (just try to toggle a boost a second time on this build)
- Repeat steps; you are in a bad state again. 

Testing was on OSX 10.11.x using the 1.16.2 downloaded builds.

**Comment by blitzmann** [comment] 2015-11-18 02:15
Interesting. Setting the fit as a booster didn't work in 1.15.0. I wonder if it ever worked. I haven't yet check what it's doing or even tried it through the interpreter. Nice find =)

**Comment by blitzmann** [comment] 2015-11-29 04:19
So I can't really reproduce the crash. Regardless, I'm hoping that the problem fixes itself within the next couple of releases when we make the final switch to mac-wx3

**Comment by Ebag333** [comment] 2016-10-17 05:35
@blitzmann this can probably be closed since links are going away #738

**Comment by blitzmann** [comment] 2016-12-12 05:53
Closing this as it has to do with previous mechanics of fleet boosts. Please open another tocket if you have an issue with the new command bursts :)

**Closed by blitzmann** 2016-12-12 05:53 UTC
Labels: invalid, osx
