### ISSUE TITLE
Capitals + Supercapitals can only use one Command Burst

### ISSUE THREAD

**Issue by SomeoneStrange** [pyfa-org/Pyfa#2031] opened 2019-08-25 22:35 UTC
## Bug Report
Carriers, FAX, Supercarriers, and Titans have Role bonuses that allow the use of extra command burst modules. After the latest update, these hulls can only have one command burst online at a time.

### Expected behavior:
2 Simultaneous bursts for Supercarriers, Carriers, FAX, 3 bursts for Titans

### Actual behavior:
1 Burst max for all mentioned hulls.

### Detailed steps to reproduce:
Load any mentioned hull, attempt to fit multiple command bursts.

### Release or development git branch? Please note the release version or commit hash:
Confirmed in 2.10.0 and 2.11.0dev1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Tested on Windows 7 and Windows 10

### Other relevant information:
Tested in Portable mode (-r) as well as with no launch arguments.

**Comment by DarkFenX** [comment] 2019-08-26 00:40
This is regression caused by incomplete effect implementation, exposed by fix for #2020

**Comment by DarkFenX** [comment] 2019-08-26 00:49
Fixed in 3b50dddef200c62d4c585e188975cac4315e93cd

**Closed by DarkFenX** 2019-08-26 00:49 UTC
Labels: bug
