### ISSUE TITLE
Citadel fitting: Projected effects tab disabled while effects can be projected

### ISSUE THREAD

**Issue by zhabry** [pyfa-org/Pyfa#707] opened 2016-08-27 03:38 UTC
When fitting a Citadel, one can choose to project various effects onto it (Neuts and Damps have very much noticeable effect). Sadly, there's no way to cancel that, as Projected tab is disabled for Citadels.
I must admit I have no idea whether you can activate Neuts or E-war on a Citadel in-game or not :)

**Comment by blitzmann** [comment] 2016-08-27 04:45
Hmm I thought I checked for this use case... I will take a look and release
a point release with a fix. Thanks

On Aug 27, 2016 12:06 AM, "zhabry" <notifications@github.com> wrote:
>
> Apparently, me playing with aforementioned stuff resulted in some kind
data corruption. A Fortizar fit does not show anything on it, not even
slots, and cannot be deleted. Opening any ship or citadel fitting and then
switching back to that Fortizar (same tab or different tabs) results in
right pane (Resources, Resistances, etc.) not refreshing.

**Comment by graywolf** [comment] 2016-08-27 22:29
having same issue, even didn't have to play with anything. just launched pyfa and opened astrahus fitting. Also, after alt-tabbing into eve and back it looks like this http://imgur.com/a/aodMG , almost like the part of the window where the fitting is supposed to be isn't responding to redraw event at all.

**Comment by blitzmann** [comment] 2016-08-28 18:31
@zhabry, @graywolf can you please email me at sable.blitzmann@gmail.com and attach your `saveddata.db` file found in `%homeprofile%/.pyfa/`

I cannot get mine to crash like that. =/

**Comment by graywolf** [comment] 2016-08-28 21:52
done

**Comment by blitzmann** [comment] 2016-08-28 23:39
I still can reproduce the crash causing the fitting window to not work. @graywolf when I open your citadel fit, it opens fine...

You you give me a specific step-by-step reproduction

**Comment by graywolf** [comment] 2016-08-29 00:10
Sure I can :) Assuming you are using my save file, the Astrahus fitting should be preselected when opening pyfa. So the repo steps are:

	1) Open PyFa

even when I delete it and start over, the steps are only slightly longer:

	1) Open PyFa
	2) Create new Astrahus fitting <-- already I don't see any slots, just blank panel

I supposed more info could help too:

	Version: v1.23.0
	Installed by: .exe file ( https://github.com/pyfa-org/Pyfa/releases/download/v1.23.0/pyfa-1.23.0-yc.118.7-1.4-win.exe )
	OS: Windows 7 (Ultimate N)
	Arch: amd64

Can I somehow enable more logging? Or is there log file I can send to you?

**Comment by blitzmann** [comment] 2016-08-29 00:31
yeah... the citadel fitting is showing fine for me...

There is a log, but it's not very good and usually doesn't work... `%userprofile%\.pyfa\log.txt` go ahead and post that if there's anything in there

**Comment by graywolf** [comment] 2016-08-29 00:36
yeah nothing useful in there :/

hm, I'll try nuking PyFa and reinstalling, maybe will help

**Comment by zhabry** [comment] 2016-08-29 03:01
Sent

**Comment by blitzmann** [comment] 2016-08-29 13:31
Thanks. I'll take a look at yours this week, but from what you've said in the email it seems that it's difficult to reproduce as well. 

Regardless, I have a fix ready for the issue of projections on citadels, which will also remove any that users have applied. If nothing comes from testing on both your DB and @graywolf, then I will release the point release and have you guys test to see if that helps any...

@graywolf I did notice in your database that the citadel in question did not have any projected modules applied, is that correct? So your issue may be completely separate from this one. Again, after th epoint release, if you notice anything, open another issue with a description. :)

**Comment by blitzmann** [comment] 2016-08-29 21:20
Update: Do you guys have colored slots enabled in your preferences? #711 was just filed, and I'm thinking that the fitting view is crashing due to that.

**Comment by zhabry** [comment] 2016-08-30 05:41
Disabled here:
![ss 2016-08-30 at 07 36 49](https://cloud.githubusercontent.com/assets/20880053/18077298/f5fccf8a-6e84-11e6-8467-93aa6575fa03.png)

**Comment by blitzmann** [comment] 2016-08-31 03:47
I'm going to release the point release tomorrow probably, which will include a fix for this. I implore you guys to give it a try once it releases and let me know if any other issues pop up.

Also, the point release should automatically remove the projected modules from the fits with a migration script. If for some reason that doesn't work, simply recreate the fit from scratch. :)

**Closed** 2016-09-02 02:29 UTC
Labels: bug, fixed

**Comment by zhabry** [comment] 2016-09-03 18:32
Confirming that 1.23.1 fixed bugged Citadel fits for me.
