### ISSUE TITLE
"Project on to Active Fit" option causes Error

### ISSUE THREAD

**Issue by SomeoneStrange** [pyfa-org/Pyfa#1954] opened 2019-04-24 16:46 UTC
pyfa v2.9.1
EVE Data Version: 1492195 (2019-04-16 09:50:22)

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

**Comment by DarkFenX** [comment] 2019-04-24 17:24
Duplicate of #1953

**Closed by DarkFenX** 2019-04-24 17:24 UTC
