### ISSUE TITLE
Few bugs when a fit projected by itself, and remote sensor booster ECCM bug

### ISSUE THREAD

**Issue by sephasis** [pyfa-org/Pyfa#714] opened 2016-08-31 02:48 UTC
![self projected proteus](https://cloud.githubusercontent.com/assets/21352052/18114146/e2f66450-6f6f-11e6-865d-95442edd3a24.PNG)

when a fit projected by itself, DPS and Recharge Rate shows weird.

This proteus' DPS is 605 and armor repairing rate must be 188/s.
(it's like 50% remote repairing effective bonus of Adaptive Augmenter is not applied.)

---

![remote sensor booster eccm](https://cloud.githubusercontent.com/assets/21352052/18114211/6a2530dc-6f70-11e6-8cf5-18a61eeede2b.PNG)

This Osprey is jammed by a Griffin with 5 Gravimetric ECM but its sensor strength is being boosted by another osprey with 4 remote sensor boosters (ECCM Script).
so sensor strength is 183 but pyfa says jamming chance is 97.5%.
it's same chance with normal Osprey without any boosting of remote sensor boosters.

**Comment by blitzmann** [comment] 2016-09-02 02:10
I'm not sure I understand the first bit with the prteus. Can you lay out exactly what values you expect to see vs the values that pyfa is showing?

As for the second issue with the sensor strength, I'll look into it. :)

**Comment by sephasis** [comment] 2016-09-03 11:59
I cannot reenact about DPS bug in this home computerm i'll check about that later but i could reenact remote repair bug so i'll show it.

![image](https://cloud.githubusercontent.com/assets/21352052/18224650/236d8720-7218-11e6-9e30-6abeea28709b.png)

proteus's remote repairing rate is +188/s. It was about +125.3/s but 'Proteus Defensive - Adaptive Augmenter' subsystem gives 50% bonus.

![image](https://cloud.githubusercontent.com/assets/21352052/18224662/70f1fc24-7218-11e6-9088-17a76d8d296a.png)

But when i set something repaired by proteus, pyfa says the rate is +125.3/s (raw HP).

![image](https://cloud.githubusercontent.com/assets/21352052/18224677/cd2227e4-7218-11e6-95f6-4f93310f12ed.png)

whatever proteus repairs...

![image](https://cloud.githubusercontent.com/assets/21352052/18224683/19e7596e-7219-11e6-9ac0-5d9773daf3fd.png)

another T3 cruisers are same. but another ships with logistics bonus like T1 frigs or cruisers, or T2 logistic frigates, etc, don't have any bug like this.

**Comment by Ebag333** [comment] 2016-10-16 19:44
It's because subsystems are being calculated later in the fitting engine. I'll submit a PR shortly with a fix.

**Comment by Ebag333** [comment] 2016-10-16 19:51
>remote sensor booster ECCM bug

@sephasis 
Can you submit a new issue with details on the remote ECCM bug?  It's very possible that it's also just a timing issue (when it get calculated), but more info would be nice.

Love the screenshots, but do me a favor and post the EFT fit so I can just copy/paste to import rather than having to hand build it. :)

@blitzmann Because this issue has so many things going on in it, I'd recommend closing this one and @sephasis can open a new one with specific in about the ECCM (and another one for the damage) if he figures out how to replicate it, or can give us more info.

**Comment by blitzmann** [comment] 2018-05-28 20:40
Gonna close this due to the following:

* Since this issue opened, t3c's have been re-balanced, thus it's difficult to reproduce the issues noted in this thread (one of the issues seems like it couldn't be reproduced anyway?)
* One of the bugs was fixed a while ago courtesy of ebag

If things are still funky, please open a new issue. thanks!

**Closed by blitzmann** 2018-05-28 20:40 UTC
