### ISSUE TITLE
Graphs option in v 1.27.0 is disabled

### ISSUE THREAD

**Issue by Dag99** [pyfa-org/Pyfa#1003] opened 2017-02-18 18:24 UTC
Window -> Graphs option is disabled ("grayed out") after installing v 1.27.0.

### Expected behavior:
Expected Graphs option to be available.

### Actual behavior:
Graphs option not available.

### Detailed steps to reproduce:
Download pyfa-1.27.0-yc119.2-1.2-win.zip and install.
Open the Window menu.
The Graphs option is unavailable.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7 Professional SP 1

### Other relevant information:
I rolled back to 1.26.0 and Graphs option works again.

Thx!

**Comment by Ebag333** [comment] 2017-02-18 18:28
Duplicate of #1001 and a fix has  been submitted i n #1002 

There's a temporary fix posted in #1001 if you don't want to wait for the next build.

**Closed** 2017-02-18 23:15 UTC
Labels: duplicate
