### ISSUE TITLE
Hard-coded item group causes localization failure

### ISSUE THREAD

**Issue by mingl0280** [pyfa-org/Pyfa#781] opened 2016-10-21 22:44 UTC
I've been doing some translation on the project, and I found when I localized the item name, pyfa cannot be started properly. After digging into the code, I found following lines:
service\market.py
```
self.ITEMS_FORCEGROUP = {
            "Opux Luxury Yacht": self.les_grp, # One of those is wedding present at CCP fanfest, another was hijacked from ISD guy during an event
            "Silver Magnate": self.les_grp,  # Amarr Championship prize
            "Gold Magnate": self.les_grp,  # Amarr Championship prize
            "Armageddon Imperial Issue": self.les_grp,  # Amarr Championship prize
            "Apocalypse Imperial Issue": self.les_grp, # Amarr Championship prize
            "Guardian-Vexor": self.les_grp, # Illegal rewards for the Gallente Frontier Tour Lines event arc
            "Megathron Federate Issue": self.les_grp, # Reward during Crielere event
            "Raven State Issue": self.les_grp,  # AT4 prize
            "Tempest Tribal Issue": self.les_grp, # AT4 prize
            "Apotheosis": self.les_grp, # 5th EVE anniversary present
            "Zephyr": self.les_grp, # 2010 new year gift
            "Primae": self.les_grp, # Promotion of planetary interaction
            "Freki": self.les_grp, # AT7 prize
            "Mimir": self.les_grp, # AT7 prize
            "Utu": self.les_grp, # AT8 prize
            "Adrestia": self.les_grp, # AT8 prize
            "Echelon": self.les_grp, # 2011 new year gift
            "Malice": self.les_grp, # AT9 prize
            "Vangel": self.les_grp, # AT9 prize
            "Cambion": self.les_grp, # AT10 prize
            "Etana": self.les_grp, # AT10 prize
            "Chremoas": self.les_grp, # AT11 prize :(
            "Moracha": self.les_grp, # AT11 prize
            "Stratios Emergency Responder": self.les_grp, # Issued for Somer Blink lottery
            "Miasmos Quafe Ultra Edition": self.les_grp, # Gift to people who purchased FF HD stream
            "InterBus Shuttle": self.les_grp,
            "Leopard": self.les_grp, # 2013 new year gift
            "Whiptail": self.les_grp, # AT12 prize
            "Chameleon": self.les_grp, # AT12 prize
            "Victorieux Luxury Yacht":  self.les_grp,  # Worlds Collide prize \o/ chinese getting owned
            "Imp": self.les_grp,  # AT13 prize
            "Fiend": self.les_grp,  # AT13 prize
        }

        self.ITEMS_FORCEGROUP_R = self.__makeRevDict(self.ITEMS_FORCEGROUP)
        self.les_grp.addItems = list(self.getItem(itmn) for itmn in self.ITEMS_FORCEGROUP_R[self.les_grp])
        self.customGroups.add(self.les_grp)

        # List of items which are forcibly published or hidden
        self.ITEMS_FORCEPUBLISHED = {
            "Data Subverter I": False, # Not used in EVE, probably will appear with Dust link
            "QA Cross Protocol Analyzer": False, # QA modules used by CCP internally
            "QA Damage Module": False,
            "QA ECCM": False,
            "QA Immunity Module": False,
            "QA Multiship Module - 10 Players": False,
            "QA Multiship Module - 20 Players": False,
            "QA Multiship Module - 40 Players": False,
            "QA Multiship Module - 5 Players": False,
            "QA Remote Armor Repair System - 5 Players": False,
            "QA Shield Transporter - 5 Players": False,
            "Goru's Shuttle": False,
            "Guristas Shuttle": False,
            "Mobile Decoy Unit": False,  # Seems to be left over test mod for deployables
            "Tournament Micro Jump Unit": False,  # Normally seen only on tournament arenas
            "Council Diplomatic Shuttle": False,  # CSM X celebration
            "Civilian Gatling Railgun": True,
            "Civilian Gatling Pulse Laser": True,
            "Civilian Gatling Autocannon": True,
            "Civilian Light Electron Blaster": True,
        }
        ...
```
Which caused the market service can't find proper name when you localized every string in the database.

**Comment by Ebag333** [comment] 2016-10-21 22:46
What exactly are you trying to do? Are you using the localized strings in the DB? Got working code?

**Comment by mingl0280** [comment] 2016-10-22 00:46
> What exactly are you trying to do? Are you using the localized strings in the DB? Got working code? 

The case is, if you changed all the "Name" columns in DB (such as categoryName, typeName, and so on), the whole program crashes.

**Comment by mingl0280** [comment] 2016-10-22 01:00
Here's a snapshot
![error-crash](https://cloud.githubusercontent.com/assets/3364434/19615708/ac53f3e4-97c0-11e6-9dfc-4d056f7e86d1.png)

**Comment by mingl0280** [comment] 2016-10-22 01:03
And here's a copy of translated database.
[evedb.zip](https://github.com/pyfa-org/Pyfa/files/545503/evedb.zip)

**Comment by blitzmann** [comment] 2016-10-22 01:53
pyfa was never designed to be localized unfortunately. This attempt to make is so is wholly unsupported, thus I'm going to be closing the ticket.

That being said... we can continue discussion here so that hopefully you can get a working version up and running. :) Localization has always interested me, so I am eager to see where this goes.

First: check out this repo: https://github.com/liuyuran/Pyfa I found out that someone had already started localization efforts for pyfa for Chinese (at least I think it's Chinese, I admit I am uncultered :P) 

However, that repo leaves the database intact, so the names are still in English IIRC. Your attempt at converting the database as well is interesting.

The problem is that you have a database with Chinese names, but there are many places in the code that explicitly looks for a ship / group / category name in English.

The error in question is trying to get the item category called "Ships". but since you have the database in another language, this of course fails. To fix this:

* change the line in question from `ships = self.getCategory("Ships")` to `ships = self.getCategory(u"舰船")`
* Add `# -*- coding: utf-8 -*-` as the very first line in the file (this tells python that there are unicode characters in the source file directly)

After those two changes, that particular line no longer errors out. However, pyfa still crashes because of other, similar errors throughout. You'll have to track them down to figure out where (the large list of hard coded items is a good place to start -  convert all of them and it should work better). Just note that there are hardcoded Enlgish names strewn about the source files, so hunting them all down is going to be a task. :) Let me know if you ave any more questions

**Closed by blitzmann** 2016-10-22 01:53 UTC
Labels: invalid

**Comment by Ebag333** [comment] 2016-10-22 02:02
Yeah. Looms about like when I was hacking it to use FuzzySteves SDE. 

I am curious about this now. Hmm. I think I might know of a way to do SOME things localized. It would NOT localize anything like labels or GUI elements, just dynamically generated text. 

Shit, means that I am going to have to look at wxPython again.
