### ISSUE TITLE
Un-plug implants

### ISSUE THREAD

**Issue by xpapahet** [pyfa-org/Pyfa#1789] opened 2018-10-31 09:44 UTC
Hello!

When i unplag implans in additions-implant sstats don't change.
Tested on zealot with high-grade asklepian and med armor rep t2.

**Comment by blitzmann** [comment] 2018-10-31 20:36
Seems to be a duplicate of #1777. Great news is that it's already been fixed internally, just waiting to release it. In the meantime, after unplugging an implant, toggle another modules state (offline then back online) or so something else that should trigger a refresh of stats, and it should show the new stats :)

**Closed by blitzmann** 2018-10-31 20:36 UTC
