### ISSUE TITLE
Survey Scanner / exception 'none type'

### ISSUE THREAD

**Issue by EodpEllecon** [pyfa-org/Pyfa#1403] opened 2018-02-18 01:00 UTC
## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.35.1 Stable - YC120.2 1.2
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\J\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'ID'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinMarketBrowser\itemView.py", line 115, in selectionMade
    items = sMkt.getItemsByMarketGroup(mg)
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 641, in getItemsByMarketGroup
    forceditms = set(self.getItem(itmn) for itmn in self.ITEMS_FORCEDMARKETGROUP_R[mg.ID])
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 641, in <genexpr>
    forceditms = set(self.getItem(itmn) for itmn in self.ITEMS_FORCEDMARKETGROUP_R[mg.ID])
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 391, in getItem
    item = eos.db.getItem(identity, *args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\db\gamedata\queries.py", line 59, in checkAndReturn
    return function(*args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\db\gamedata\queries.py", line 94, in getItem
    itemNameMap[lookfor] = item.ID

### Expected behavior:
RIght click survey scanner for market group

### Actual behavior:
got bug report, no market group

### Detailed steps to reproduce:
Fitted survey scanner II on old fit would not produce market group on click.
Search for survey scanner would not produce market group.

### Release or development git branch? Please note the release version or commit hash:
Release downloaded and current as of Feb 17, 2018

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10

**Comment by blitzmann** [comment] 2018-02-18 08:10
Thanks for the bug report! I can reproduce as well. It's an odd one for sure, will take a look at it more closely tomorrow. :)

**Comment by blitzmann** [comment] 2018-02-19 04:19
The reason for this is because there is an item that was removed from EVE that pyfa is expecting to be there (due to some ancient pre-processing thing that it does).

I don't believe this is a situation which calls for a new point release all by itself, as it only affect that market group (as I'm currently aware), and one can still search for the items. Once I get a fix in place, I will post a link to an automated build for those folks that may want it. :)

**Comment by blitzmann** [comment] 2018-02-19 05:17
https://ci.appveyor.com/project/blitzmann/pyfa/build/master-424/artifacts

Here's a link to the build with the fix if anyone needs it. If there are other bugs reported with v1.35, I'll bundle this and them into an official point release

**Comment by blitzmann** [comment] 2018-02-24 07:06
Whoops, forgot to flag this as fixed in a1aa78adc094982f20468df7ba77d5813dcc133e :)

**Closed** 2018-03-04 22:13 UTC
Labels: bug, fixed, logged
