### ISSUE TITLE
Error in line 3259, in <lambda> durrign start od PyFa

### ISSUE THREAD

**Issue by mrkaczor83** [pyfa-org/Pyfa#2144] opened 2020-03-11 15:50 UTC
pyfa v2.18.0
EVE Data Version: 1683031 (2020-03-10 10:17:44)

OS version: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.14
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.7.3

####################

Traceback (most recent call last):
  File "/home/kaczor/.local/lib/python3.7/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/kaczor/Software/pyfa/gui/mainFrame.py", line 245, in ShowUpdateBox
    with UpdateDialog(self, release, version) as dlg:
  File "/home/kaczor/Software/pyfa/gui/updateDialog.py", line 63, in __init__
    self.browser = wx.html2.WebView.New(self)
NotImplementedError

### Expected behavior:

No error

### Actual behavior:

Gives messaage

### Detailed steps to reproduce:

Install pyfa and packages by pip

### Fits involved in EFT format (Edit > To Clipboard > EFT):

none - error appears n start

### Release or development git branch? Please note the release version or commit hash:

Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian 10 x64

**Comment by DarkFenX** [comment] 2020-04-06 08:49
Looks like some issue caused by incorrect wx version. Afaik it gets compiled on linux when you install via PIP, and quite likely it was missing some development headers to compile `webview` component.

You could try removing this compiled version of wx, and installing a system one (if it is 4.0.6+). It's in `python3-wxgtk4.0` and `python3-wxgtk-webview4.0` packages.

**Comment by DarkFenX** [comment] 2020-04-06 09:03
I will close this ticket now. If you have any data which hints that this issue is on pyfa, feel free to reopen.

**Closed by DarkFenX** 2020-04-06 09:03 UTC
Labels: invalid
