### ISSUE TITLE
Can't add character from SSO

### ISSUE THREAD

**Issue by rossos** [pyfa-org/Pyfa#1849] opened 2019-02-13 06:55 UTC
## Bug Report
I cannot add new characters via SSO, either with "Local Server" or "Manual" methods.

### Expected behavior:
After the localhost callback/redirect, or after copy/pasting the given text from a successful SSO login, the logged-in character should be in the list of available characters in the SSO Character Management window.

### Actual behavior:
The logged in character is not visible in the list of available characters, nor in the "Character" dropdown selection box in the main UI window (top right).

Using "Local Server" option (no error is thrown), I am redirected in my browser to the SSO session. After completing my login, I am redirected to a page at localhost:57055 which briefly says "Processing response from EVE Online", then just "pyfa". Returning to pyfa, my character has not been added.

Instead using "Manual" Login Authentication Method, I log in via SSO and am given text to copy. After copying, I see the error:

```
pyfa vv2.6.0
EVE Data Version: 1420430 (2018-11-13 21:35:30)

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 244, in ShowSsoLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 156, in handleLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\models.py", line 892, in json
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Detailed steps to reproduce:
Select the "EVE SSO" menu, select, "Manage Characters", then "Add Character". Log in using SSO.

### Release or development git branch? Please note the release version or commit hash:
v2.6.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7 64bit

**Comment by alexanderdarino** [comment] 2019-02-17 22:15
Having the exact same issue, same symptoms. Using latest stable version, Windows 10 64-bit up to date. Browser is Chrome (if that matters).

Oh, another thing: I had my character's already in Pyfa back when the update skills used to work, but then they stopped working. I removed them from Character Management before attempting to readd them to get the above issues. So the issue is both with adding characters and with updating existing characters.

**Comment by blitzmann** [comment] 2019-02-18 14:47
There was a similar issue on OS X that was resolved by re-downloading pyfa... I'm not sure why you guys are experiencing this tho. 

The error seems to suggest that the error is happening on the EVE side of things, however we're not handling the error properly. See: https://github.com/pyfa-org/Pyfa/blob/master/service/esi.py#L156

`res.json()` is the call that's breaking. This line happens if the verification of the token you receive  does not result in a `200 OK` response from CCP. However, if it doesn't result in a 200, then it's likely it's not actually returning any json body, hence the error `Expecting value`.

Can you guys post any `*.log` files here from `%userprofile%/.pyfa`? That may have a few more details, otherwise I can create a few more logging statements / handle the exception better.

For the record, I just tried myself, and can log in and link character fine.. :/

Another option is to get with you guys on slack or something and try to debug in realtime, but that would be pretty difficult for me due to extreme time constraints on my end recently

**Comment by blitzmann** [comment] 2019-02-18 14:48
Also @rossos please make sure you keep up with the latest version (currently 2.7.0) :)

**Comment by tfrahar** [comment] 2019-02-19 16:46
I've got the same problem, and cannot add my character through EVE SSO.

Windows 7 64-bit
pyfa v2.7.0

After install, and re-install, I try to add a character via SSO and go through the authentication portal just fine. By browser (Chrome) then loads a page entitled: pyfa Local Server which spins for a while, then stops and shows nothing but "pyfa" in bold on an empty white page.

Not sure if it's an ISP/firewall/proxy thing... but I can't get it to work.

This is the URL it stops on:

http://localhost:50473/?state=096f0828-0717-42b7-b438-b6ff2fb4fcda&SSOInfo=eyJhY2Nlc3NfdG9rZW4iOiAiMF9EMFg5S3JhZ3NmVjZOamxJWUxSRGk5aklHMjhabk1QQ3lKNVdkUnZfNDExcHdRS1QtYThzWTFZVFdqSFlKNjh0US0wekZlWXd4X1JnQXpnSEhWaGcyIiwgInRva2VuX3R5cGUiOiAiQmVhcmVyIiwgImV4cGlyZXNfaW4iOiAxMTk5LCAicmVmcmVzaF90b2tlbiI6ICJPbWRLWHA3TGtUakV3djFIMnl6QjRHRFpydEZMbjl2bEg5b0ktVllLTGdDN05ZU1BvUWIwRExUTWREYXl2Skp3MCJ9&step=2

**Comment by noobish** [comment] 2019-02-20 04:03
I am also seeing something similar to tfrahar's observations in chrome and FF with 2.7.0 on win10 amd64. But he seems to be able to make a connection back to pyfa, where as for me it seems that pyfa is not listening on the random port for connections following SSO sign-in process (url of the form `localhost:5xxxx?state=xxx&SSOInfo=xxx`). I wish I knew how to netstat this in windows to confirm. I get the same behavior on linux but it's an ancient version of pyfa. If I have time to run master and get you more info, I will.

*Strangest thing: I turned on `--debug` to get you a log, and it worked. Tried again without `-d`, worked again. Not sure...

**Comment by rossos** [comment] 2019-02-20 05:55
This resolved for me after updating to 2.7.0.

**Comment by blitzmann** [comment] 2019-02-20 15:43
This all seems to stem from the response coming back as a non-200 when trying to verify the data that EVE returns (and subsequently the fact that there's an error with the error handler... go figure). Will have to push a couple of changes that better reflect the error, hope to do that sometime this week.

As for the `This site can’t be reached localhost refused to connect.` issue, pyfa's local server spins up for only 120 seconds (I think). This is enough time to hopefully login, but if you dwaddle on the character selection screen for a bit, it's possible to miss this window. I've always wanted to find a better way to handle that, but meh

**Comment by noobish** [comment] 2019-02-21 16:32
For me, the 120 second server lifetime has to be it. Every time I SSO to EVE it requires 2-factor email code that I have to wait for. I suggest upping the lifetime to at least 5 mins.

**Comment by blitzmann** [comment] 2019-02-24 22:39
> For me, the 120 second server lifetime has to be it. Every time I SSO to EVE it requires 2-factor email code that I have to wait for. I suggest upping the lifetime to at least 5 mins.

This shouldn't be a problem. Additionally, we could probably set that as an option in the preferences, and we could probably be better about letting a user know that the server is only going to work for a limited time.

If that's the case though, `Manual` mode should work fine for you. Preferences > EVE SSO > Login Authentication method

**Comment by spdunn11** [comment] 2019-02-27 15:49
I'm also having this issue... SSO wouldn't update, so I deleted toon, and tried to add.  Won't add.  Tried Manual mode and got this error:

pyfa vv2.5.1
EVE Data Version: 1400958 (2018-10-15 21:11:58)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 244, in ShowSsoLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 156, in handleLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\models.py", line 892, in json
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by blitzmann** [comment] 2019-02-27 16:21
@spdunn11 

> pyfa vv2.5.1

This is an old version, please update and let me know if you still have the issue.

It's surprising that a lot of folks aren't updating their pyfa installs. Are you guys not getting the update notification? Check Preferences > Updates > Make sure there isn't a suppressed update.

I'm going to focus on getting this "error" "fixed" this weekend and putting out a dev build here for folks to try. It won't be a true fix, but it'll give us more information.

**Comment by spdunn11** [comment] 2019-02-27 16:27
no update available.  I'll have to do a reinstall.  I actually suspected this because it had been some time since I received an update notification.  Thank you for the insight.

**Comment by blitzmann** [comment] 2019-02-27 17:14
> Curious I wasn't getting any update notifications, and no option to update when checking manually.

yeah... oops. https://github.com/pyfa-org/Pyfa/issues/1860 it was an issue on our end. >_> Update check should be working now.

**Comment by blitzmann** [comment] 2019-02-27 23:57
Aha!

So, the reason we're having this error is because for versions before 2.7, the esi url was `esi.tech.ccp.is`. which is no longer active. The new url is `https://esi.evetech.net`. The reason a lot of folks were having this issue is because of #1860 which was recently fixed :)

Theres a few things that we can do to better reflect APIs errors, but for now, this will do.

**Closed** 2019-03-24 15:52 UTC
Labels: fixed, logged

**Comment by CaesiumPP** [comment] 2020-04-12 14:30
Hello.
I seem to have that EXACT problem now with 2.19.0. Can't add a new character for the same reason.
Reinstalls, restarts, deactivating firewall/antivirus program didn't help either.
