### ISSUE TITLE
Error on importing fit

### ISSUE THREAD

**Issue by natemarston** [pyfa-org/Pyfa#1775] opened 2018-10-15 15:24 UTC
## Bug Report
pyfa vv2.5.0
EVE Data Version: 1399820 (2018-10-09 23:27:02)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 86, in fitSelected
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 339, in fitSelected
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 353, in updateTab
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 76, in getImage
AttributeError: 'NoneType' object has no attribute 'ConvertToImage'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 86, in fitSelected
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 339, in fitSelected
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 353, in updateTab
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 76, in getImage
AttributeError: 'NoneType' object has no attribute 'ConvertToImage'

On importing the fit below to pyfa using CRTL+V I received the above error message. When I reloaded pyfa the fit showed up in the navigation menu, however when i clicked on the fit to view, it game the same error once again.

[Pacifier, DDLG]

Damage Control II

Magnetic Field Stabilizer II

Magnetic Field Stabilizer II

Nanofiber Internal Structure II

Coreli A-Type 1MN Afterburner

Dread Guristas Warp Scrambler

Pithum A-Type Medium Shield Booster

Small 'Siesta' Capacitor Booster,Navy Cap Booster 400

Covert Ops Cloaking Device II

Light Neutron Blaster II,Void S

Light Neutron Blaster II,Void S

Light Neutron Blaster II,Void S

Small Targeting Systems Stabilizer II

Small Targeting Systems Stabilizer II

Fit in question.

**Comment by blitzmann** [comment] 2018-10-15 19:28
Seems like a duplicate of #1767, which has been fixed. I will hopefully be able to release a point release tonight :)

**Closed** 2018-10-16 02:43 UTC
Labels: duplicate
