### ISSUE TITLE
Triage Module EWAR resists don't seem to be factored in.

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#916] opened 2016-12-21 03:52 UTC
Given this Keres:

```
[Keres, Keres]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Remote Sensor Dampener II, Scan Resolution Dampening Script
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
```

And this Apostle:

```
[Apostle, Apostle fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Triage Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

If you project the Keres on the Apostle, the scan resolution doesn't seem to account for the fact that the Triage Module I has a 60% Sensor Dampener Resistance Bonus.

The Keres has a dampening strength of 52.6% and the scan res ends up at `356mm (750mm - 52.6%)` on both the latest master (3396056dae74e51eb656539f7de8bc49c118701f) and in the latest stable (1.26.0)

A buddy logged into sisi and tested the situation and had their scan resolution go from 750mm to 598mm. So it seems like the math should be `750 × (1 - (.526 × (1 - .60))) = 592.2` (or something like that with stacking penalties)

**Comment by Ebag333** [comment] 2016-12-21 04:19
Yeah. We don't handle that at all, for anything with resists of that sort. So marauders, carriers, rorq, etc....

**Comment by blitzmann** [comment] 2016-12-21 13:52
I had a branch on my local repo that started ding things with this a few months back in case anyone wants to take a look. Never finished it and not sure if it's correct or the way we want to do it, but it might be a good stepping stone https://github.com/blitzmann/Pyfa/tree/ewar-resists

**Comment by blitzmann** [comment] 2017-01-04 05:00
Closing this as a duplicate of #809

**Closed by blitzmann** 2017-01-04 05:00 UTC
