### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by Elle-Auduin** [pyfa-org/Pyfa#2262] opened 2020-09-02 22:19 UTC
Attempting to add a character hasn't worked for a week or so, it redirects to the browser page but then it times out, every time.

https://www.pyfa.io/oauth/authorize?state=25f195c6-964c-4303-af47-d6a8abb5bd20&pyfa_version=v2.26.0&login_method=0&client_hash=224d28ef7d942b8491453ea0f760bbcc74a20174890b6860bffd5c8a711e40d1&redirect=http%3A%2F%2Flocalhost%3A49509

This site can’t be reachedwww.pyfa.io took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by blitzmann** [comment] 2020-09-03 01:34
I just check myself and it works fine. 

Just to clarify, when you try to add a character, it opens the browser to that page but that page never loads? You never get to the character selection screen?

Does going to `https://www.pyfa.io` redirect to this GitHub repo? Can you `ping pyfa.io`? What about `tracert pyfa.io` (this could help figure out where the connection is getting lost)

`ERR_CONNECTION_TIMED_OUT` usually happens when there's something preventing you from accessing the page. This wouldn't be a pyfa application issue, and the website is up and responsive, so I would say that there's somewhere between your computer and the authentication page where connection is breaking (firewalls are usually the cause, especially if you're attempting to connect from with a work network).

I've also heard that there are some regions where the government simply blocks certain IP addresses (pyfa.io / pythonanywhere.com uses AWS I believe, so the site could be blocked by regulatory bodies that indiscriminately block AWS IP blocks). So depending on where you live might also affect it if they have for some reason shut down access.

All that being said, if it's still causing issues, you can set up your own developer account with CCP by using the "Custom Application" setting:

![image](https://user-images.githubusercontent.com/3904767/92061252-cb811100-ed63-11ea-933c-86c3cf934b7c.png)

Information on how to set this up can be found here: https://github.com/pyfa-org/Pyfa/wiki/EVE-SSO

Please note that it's been a hot minute since I've reviewed those steps / scopes, but I don't think anything has changed. Also note that it will require you to agree to a developer license with CCP

**Comment by Elle-Auduin** [comment] 2020-09-03 11:19
Thanks for the reply ...

Yes I could ping pyfa,io that's what threw me off .. 0 losses, regular response.  even tracert pyfa.io worked.

But after your explanation, I tried a proxy and it worked, for whatever reason it does seem to have been blocked by my isp, will get in touch with them later on today to see what's going on.

Thanks again for all your help and prompt response 👍

**Comment by blitzmann** [comment] 2020-09-03 13:44
No problem, hope you get it resolved. I'm going to close this issue. If the you don't get anywhere with the ISP, as a last resort you can set up your own client details and bypass pyfa.io :)

**Closed by blitzmann** 2020-09-03 13:44 UTC
