### ISSUE TITLE
Pyfa crashes after using "search"

### ISSUE THREAD

**Issue by PLEX88** [pyfa-org/Pyfa#2171] opened 2020-04-16 20:13 UTC
Pyfa crashes after using search. It doesn’t matter what you wrote, any word and you got crash.
I tried to reinstall, but received no effect. Until the latest version, everything worked fine for me. Strange, but for my friends everything works.
Pyfa 2.20.1
Win 10

**Comment by DarkFenX** [comment] 2020-04-16 20:32
Duplicate of #2167. I will release fixed version shortly. See workaround in linked issue.

**Closed by DarkFenX** 2020-04-16 20:32 UTC
