### ISSUE TITLE
Drone stacks not correctly contributing to fittings price

### ISSUE THREAD

**Issue by bjjerry** [pyfa-org/Pyfa#1028] opened 2017-03-06 03:19 UTC
Other than the first drone of a stack, drones do not currently add to the cost of a fitting. To reproduce this bug, add two drones to any fit. The first drone is counted, but the second one isn't. Will poke around some and see what I can find.

**Comment by Ebag333** [comment] 2017-03-06 03:37
@blitzmann just made a change a month or so ago that stopped it from doing a price lookup for each drone. 

Might be related to that...

**Comment by blitzmann** [comment] 2017-03-06 04:18
That is almost certainly the cause. I'll investigate. Should be an easy way to fix this.

Thanks for the report!

**Comment by bjjerry** [comment] 2017-03-06 04:18
Same with cargo, first charge is counted, additional aren't.

**Comment by Ebag333** [comment] 2017-03-14 22:56
See #1038 for possible solution.

**Comment by blitzmann** [comment] 2017-04-11 01:14
Thanks to ebag for submitting a fix for this, as well as fixing a long-standing gripe with items not carrying their own price object. see #1115 :D

This will be released with v1.29.0

**Closed** 2017-05-10 03:38 UTC
Labels: bug, fixed
