### ISSUE TITLE
T2 comand skirmish bursts does not work at Sleipnir and Astarte

### ISSUE THREAD

**Issue by PavlikX** [pyfa-org/Pyfa#861] opened 2016-11-28 19:16 UTC
Well, here is a peoblemm. I had quick test to day. Armor and other bonuses works fine (at least at absolution, sleipnir, astarte). skirmish does not work at all.
PS I've activated second comand burst slot, as one of previous fixes recomended.

**Comment by blitzmann** [comment] 2016-11-28 21:21
Can't test right now but I believe this was fixed with a similar issue

**Comment by blitzmann** [comment] 2016-11-29 02:13
Confirmed that this is a duplicate of another issue that was fixed. Thanks!

**Closed by blitzmann** 2016-11-29 02:13 UTC
Labels: duplicate
