### ISSUE TITLE
Import fit failing from EFT file

### ISSUE THREAD

**Issue by radumalica** [pyfa-org/Pyfa#1459] opened 2018-03-02 17:03 UTC
Downloaded 2.0.0 beta 3 and tried to import a fit from CFG file in EFT format, saved by notepad in ANSI mode. The window in PYFA is hanged at importing fit, elapsed time 0:00:00 forever. Cancelling also doesn't work, pyfa needs to be killed via task manager.

Running Windows 10 latest updates.

**Comment by Neugeniko** [comment] 2018-03-03 03:54
Is the ship type in the file or in the file name. Just trying to clarify which type of eft "file".

**Comment by Neugeniko** [comment] 2018-03-03 03:54
Better yet post the file.

**Comment by blitzmann** [comment] 2018-03-03 04:11
Most likely a duplicate of #1410, which has been fixed and will be release this weekend.

I don't even have EFT installed anymore, and I can't find a mirror with the last release from way back in 2016, so I can't test myself with EFT's files. Would need some files to test with.

**Comment by Neugeniko** [comment] 2018-03-03 04:24
The pyfa code never gets to import normal EFT format via a file (with ship type in file) because of line 448 in port.py.

```
        if re.match("\[.*\]", firstLine) and path is not None:
            filename = os.path.split(path)[1]
            shipName = filename.rsplit('.')[0]
            return "EFT Config", cls.importEftCfg(shipName, string, iportuser)
```

Which tries to open the file as a eft config store file and fails.

Changing the first line to ignore the normal EFT header (with ship type) solves the problem.

`        if re.match("\[.*\]", firstLine) and path is not None and not re.match("\[.*,.*\]", firstLine):
`

**Comment by Neugeniko** [comment] 2018-03-03 04:35
I found eft over at eve files.
http://eve-files.com/search.dxd?search=eft

**Comment by Neugeniko** [comment] 2018-03-03 05:01
Ok confirmed, py3 is not able import *.cfg files from the setups directory of eft.

**Comment by Neugeniko** [comment] 2018-03-03 05:13
Just to confirm eft never generates *.cfg file  where it stores a fit in clipboard format at user request. So technically the above changes are not needed.

**Comment by blitzmann** [comment] 2018-03-03 05:51
Thanks for the link to EFT :)

Have a fix out on the py3 branch, was a simple encoding issue similar to #1410 but not the same

**Comment by Neugeniko** [comment] 2018-03-03 05:51
Heres a sample eftcfg file.

[Wolf.zip](https://github.com/pyfa-org/Pyfa/files/1777142/Wolf.zip)

**Comment by Neugeniko** [comment] 2018-03-03 06:03
Fix works for 'proper' cfg files. A 'malformed' cfg file ANSI file returns app to normal functioning. A 'malformed' UTF8,UTF16,UTF16BE file hangs the dialog. Attached.

[Various CFG files.zip](https://github.com/pyfa-org/Pyfa/files/1777149/Various.CFG.files.zip)

**Comment by radumalica** [comment] 2018-03-03 06:37
here is the one i tried with
[porpoise.zip](https://github.com/pyfa-org/Pyfa/files/1777186/porpoise.zip)

**Comment by blitzmann** [comment] 2018-03-03 08:11
> Fix works for 'proper' cfg files. A 'malformed' cfg file ANSI file returns app to normal functioning. A 'malformed' UTF8,UTF16,UTF16BE file hangs the dialog. Attached.

For the ANSI test, simply renaming the file to `Naga.cfg` allows the import to work. That's because the EFT cfg filenames determine the type of ship we're importing. Now, I'm not sure why this is the case, as we can easily get that information from the first line, eg `[SHIPNAME, FITNAME]`, but  that's the case as it stands currently. Possibly some legacy reason that we should probably re-evaluate.

For the other guys, I think the reason for this is that we are opening the file as utf-8 (which I believe was added for another fit in the py3 branch). Removing the encoding form the `open()` command allows the file to get through the file read process, but then we are left with a `firstline` that we aren't expecting with a bit of extra crap in front of it:

![image](https://user-images.githubusercontent.com/3904767/36931916-2a48e232-1e8e-11e8-8ae8-9c581ac9c458.png)

I'm assuming the encoding of the characters is screwing up how we identify which import path it goes down, hence it erroring out (handling errors of imports is already in another issue)

All that being said, I don't think we should spend any time trying to cover edge cases of malformed files. Whatever EFT exports, we should handle, and nothing more. There isn't one unified way of determining a files encoding, so there isn't any way we would be able to handle all files. We can only hope to handle proper, non-corrupted files and gracefully fail for everything else.

> here is the one i tried with

As explained above, the ship is determined by filename. It's also case-sensitive. Using `Porpoise.cfg` works for me with the latest commits.

**Comment by Neugeniko** [comment] 2018-03-03 08:30
.cfg files are specifically what eft uses in the background which has a different format to the clipboard export in eft. Those fits have the ship name in em. see eft setups folder.

**Comment by Neugeniko** [comment] 2018-03-03 09:32
We have two eft import functions to handle either case. 

if i open file in binary mode
detect any byte order mark to determin the encoding
substract those bytes of the byte order mark 
then decode the bytes using the detected encoding.
it all just works

just the start of the function definition
```
    def importFitFromFiles(paths, iportuser=None):
        """
        Imports fits from file(s). First processes all provided paths and stores
        assembled fits into a list. This allows us to call back to the GUI as
        fits are processed as well as when fits are being saved.
        returns
        """

        sFit = svcFit.getInstance()

        fit_list = []
        try:
            for path in paths:

                if iportuser:
                    msg = "Processing file:\n%s" % path
                    pyfalog.debug(msg)
                    PortProcessing.notify(iportuser, IPortUser.PROCESS_IMPORT | IPortUser.ID_UPDATE, msg)

                with open(path,"rb") as detectheader:
                    detectbom = detectheader.read()

                savebom = b''
                codec_found='utf-8'
                encoding_map = (
                    (b'\xef\xbb\xbf', 'utf-8'),
                    (b'\xff\xfe\0\0', 'utf-32'),
                    (b'\0\0\xfe\xff', 'UTF-32BE'),
                    (b'\xff\xfe', 'utf-16'),
                    (b'\xfe\xff', 'UTF-16BE'))

                for bom, encoding in encoding_map:
                    if detectbom.startswith(bom):
                        codec_found = encoding
                        savebom = bom

                srcString = detectbom[len(savebom):].decode(codec_found)
                if len(srcString) == 0:  # ignore blank files
                    pyfalog.debug("File is blank.")
                    continue


```

**Comment by Neugeniko** [comment] 2018-03-03 11:49
The reason the BOM detection etc was put in originally (see 1.35.1 code base) was because some platforms  just write xml in their preferred encoding and utf-16 support was needed.

**Comment by blitzmann** [comment] 2018-03-03 17:53
> .cfg files are specifically what eft uses in the background which has a different format to the clipboard export in eft.

Righto. I think I was going off the files you provided when making that statement, which have the ship name. So indeed, we need to be able to determine by the filename. >.<

As for the byte encoding... I removed that code from py3 branch to clean it up, thinking that we may not need it anymore with python 3. I don't specifically remember a case of an import failing due to it's BOM, but I guess it can happen. 

Fun side note, there's a package that allows us shove in a string, and out pops Unicode... this could be nice to automatically convert imported data to Unicode that we then can use as normal.

```
from bs4 import UnicodeDammit

dict = {
    'ansii': r"C:\Users\holme\Downloads\Various.CFG.files\Naga.cfg",
    'utf16': r"C:\Users\holme\Downloads\Various.CFG.files\Unicode.cfg",
    'utf16BE': r"C:\Users\holme\Downloads\Various.CFG.files\Unicodebe.cfg",
    'utf8': r"C:\Users\holme\Downloads\Various.CFG.files\utf8.cfg"
}

for k, v in dict.items():
    print(k)
    with open(v, "rb") as file_:
        srcString = file_.read()
        print(srcString)
        dammit = UnicodeDammit(srcString)
        print(dammit.original_encoding)
        print(dammit.tried_encodings)
        print(dammit.unicode_markup)
    print("-"*20)

```

Seems to work well, at least in this test script. I'm going to play around with it some more, but I think I'd want to use this. 

Thanks for researching into it 😄  👍

**Comment by blitzmann** [comment] 2018-03-03 19:23
124bb027abc7a9a1d975b5c6930d0825b64f6d20, please note this required the `beautifulsoup4` package, but I think it makes the code cleaner than the previous code, and can prove useful in other situations, while maintaining our ability to open files that might have a different encodings. Let me know if your tests pass with this :)

**Comment by Neugeniko** [comment] 2018-03-03 23:37
Passes these tests on win 10.
Able to import xml from eve client.
Able to import xml from self.
Able to import xml from eft.
Able to import xml from jeveassets.
Able to import cfg from eft setups directory.

Attempt to import 'clipboard eft' (ANSI) format from file fails and client return to normal function.
Attempt to import 'clipboard eft' (utf-8) format from file fails and client return to normal function.
Attempt to import 'clipboard eft' (utf-16) format from file fails and client return to normal function.
Attempt to import 'clipboard eft' (utf-16BE) format from file fails and client return to normal function.

Renaming above 4 files to a <Shipname> allows them to be imported. But like you said these are edge cases and we shouldnt worry about importing clipboard eft format via a file.

**Closed** 2018-03-04 22:13 UTC
Labels: 2.x, bug, fixed, logged
