### ISSUE TITLE
search implant "armor" made crash

### ISSUE THREAD

**Issue by limdoglim** [pyfa-org/Pyfa#2169] opened 2020-04-16 03:11 UTC
search implant "armor" made crash

![image](https://user-images.githubusercontent.com/1431962/79410444-63f83e00-7fdb-11ea-923d-1a62b653dff4.png)

**Comment by limdoglim** [comment] 2020-04-16 03:12
2.20.1

**Comment by DarkFenX** [comment] 2020-04-16 08:54
Seems to be duplicate of #2167. Try `damage` and see if it crashes the same way.

**Comment by DarkFenX** [comment] 2020-04-16 12:15
Closing as duplicate. Will make a release with the fix shortly.

**Closed by DarkFenX** 2020-04-16 12:15 UTC
