### ISSUE TITLE
New Pyfa 2.0 doesn't start

### ISSUE THREAD

**Issue by XanthorI** [pyfa-org/Pyfa#1559] opened 2018-05-10 09:13 UTC
This is the message I receive:
OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by Albador** [comment] 2018-05-10 13:26
OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

same problem for me

**Comment by BaxLi** [comment] 2018-05-10 20:28
The same 

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by seraphx2** [comment] 2018-05-10 21:39
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by Fundaris** [comment] 2018-05-11 17:54
look at #1553

**Comment by blitzmann** [comment] 2018-05-14 22:55
Indeed, looks like a duplicate of #1553. My bad for not explicitly stating in the release notes that you can't just jump the extracted zip file onto the old installation.

New installer is coming out with point release tonight hopefully :)

**Closed** 2018-05-14 22:55 UTC
Labels: duplicate
