### ISSUE TITLE
Initial Launch EVE SSO Manage Characters

### ISSUE THREAD

**Issue by devlake** [pyfa-org/Pyfa#1546] opened 2018-05-08 15:02 UTC
Created a fresh install of PYFA and first time I launched EVE SSO / Manage Characters it had the following error report:
```
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 636, in ssoHandler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 302, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 331, in popCharList
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 77, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 82, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 62, in initEsiApp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\esipy\app.py", line 70, in __getattr__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\esipy\app.py", line 45, in __get_or_create_app
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\core.py", line 364, in create
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\core.py", line 285, in load
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\core.py", line 166, in load_obj
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\resolve.py", line 62, in resolve
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\getter.py", line 32, in __next__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\getter.py", line 138, in load
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\pyswagger\getter.py", line 144, in _url_load
  File "C:\Python36\lib\urllib\request.py", line 223, in urlopen
  File "C:\Python36\lib\urllib\request.py", line 526, in open
  File "C:\Python36\lib\urllib\request.py", line 544, in _open
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
  File "C:\Python36\lib\urllib\request.py", line 1361, in https_open
  File "C:\Python36\lib\urllib\request.py", line 1321, in do_open
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
  File "C:\Python36\lib\http\client.py", line 297, in begin
  File "C:\Python36\lib\http\client.py", line 258, in _read_status
  File "C:\Python36\lib\socket.py", line 586, in readinto
  File "C:\Python36\lib\ssl.py", line 1002, in recv_into
  File "C:\Python36\lib\ssl.py", line 865, in read
  File "C:\Python36\lib\ssl.py", line 625, in read
socket.timeout: The read operation timed out
```
----------------------------

Not really any more information, just an fyi

**Comment by blitzmann** [comment] 2018-05-08 21:16
> socket.timeout: The read operation timed out

Yeah, this can happen sometimes when you first open the ESI stuff (per version, so pyfa 2.1 is going to have the same sort of delay). It has to download and cache the swagger information. A lot can go wrong in the meantime, such as a connection drop or timeout. Unfortunately, we don't currently have a mechanism in place to retry or anything, it just bombs.

I'll look into at the very least getting some sort of message like "Could not fetch ESI information. This can be caused by a slow network. Please try again"

**Comment by blitzmann** [comment] 2018-05-14 23:40
This should be addressed in the upcoming point release tonight, (hopefully)

**Comment by devlake** [comment] 2018-05-15 01:11
Oh it's not a problem, everything works fine.

I just posted the errors in case you needed them. Bugs sometimes cause other problems.

Thanks for all the hard work, pyfa is working better than it ever has.

**Comment by blitzmann** [comment] 2018-05-15 02:34
New update out that should resolve this issue. If it persists please open a new ticket :D

Thanks!

**Closed by blitzmann** 2018-05-15 02:34 UTC
