### ISSUE TITLE
Feature Request : HTTP Proxy Username/Password

### ISSUE THREAD

**Issue by kelyen** [pyfa-org/Pyfa#746] opened 2016-09-21 09:48 UTC
Hello,

Can we have the possibility to add a username and password in : 

Pyfa > Window > Preferences > Network > Manually Add Proxy

Thank you,

**Comment by blitzmann** [comment] 2016-09-23 14:47
Hey there,

This is a duplicate of #26, however I'm going to close that one and keep this one open simply because that one is buried in years of issues and this one might get some visibility. 

I personally don't have the knowledge to handle this feature. I've never used proxies, don't know how to set one up, and trying to get it to work just seems... It would take a bit of research on my part, and that's time I don't currently have :(

Maybe someone has the knowledge behind how proxy stuff works and wants to tackle this? If so, leave a comment!

**Comment by minlexx** [comment] 2016-09-23 20:41
I think this feature can be done. I always wanted to do some hacking with Pyfa, maybe I should start with something simple like this...

**Comment by blitzmann** [comment] 2016-09-23 22:43
@minlexx excellent! It would be a great help. This is where the proxy stuff resides:

https://github.com/pyfa-org/Pyfa/blob/master/service/network.py#L76

**Comment by webera** [comment] 2016-09-25 13:26
Shouldn't it be already possible to use the current implementation by specifiying the address like that:

http://proxyusername:proxypassword@proxyaddress

so like

http://squid:squid@127.0.0.1

?

**Comment by minlexx** [comment] 2016-09-25 17:11
@webera Yes, I just tested (took too much time for me to configure squid3 to require a username/password, but now I can reliably test with proxy). It works for me this way, but this is not obvious for users ;) We could still add explicit input fields for proxy username/password in GUI (somewhere below Port: input section), need @blitzmann opinion about this.

![screen](http://puu.sh/rnrG1/bddc686255.png)

P.S. I tested with EVE API: Character Editor ("Get Characters", "Fetch Skills" buttons). Without username:pass there was TCP_DENIED/407 error - "Proxy authorization required", with username:pass TCP_MISS indicates successful connect (cache miss) in squid proxy server log.

**Comment by blitzmann** [comment] 2016-09-25 19:13
> took too much time for me to configure squid3 to require a username/password

This is exactly why I gave up on it way back when I looked at it.

I am surprised it is as simple as that though. I agree, an explicit username and password field would be beneficial, and we can concatenate the information in the network service. :)

**Comment by kelyen** [comment] 2016-09-26 07:58
Thank you very much for the syntax. In fact, I didn't know it before. It's working like a charm.

**Closed** 2016-12-02 23:32 UTC
Labels: done, enhancement
