### ISSUE TITLE
Cerberus unable to fit 6 launchers

### ISSUE THREAD

**Issue by scuba-paul** [pyfa-org/Pyfa#2165] opened 2020-04-15 14:20 UTC
### Release or development git branch? Please note the release version or commit hash:

v2.20.0
Latest EVE version (15 Apr release)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by DarkFenX** [comment] 2020-04-15 14:39
Duplicate of #2162. Update to v2.21.1, it has that issue fixed.

**Closed by DarkFenX** 2020-04-15 14:39 UTC
