### ISSUE TITLE
AT ships not available

### ISSUE THREAD

**Issue by AkiraWhitlock** [pyfa-org/Pyfa#1323] opened 2017-10-26 21:53 UTC
### Expected behavior:
Find specific ship within search bar

### Actual behavior:
Error

### Detailed steps to reproduce:
In the search bar (Ctrl+f) search for the ship Victor

### Release or development git branch? Please note the release version or commit hash:
Most recent version

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.33.0 Stable - Lifeblood 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\DSU\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for -: 'int' and 'NoneType'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinStatsViews\resistancesViewFull.py", line 183, in refreshPanel
    resonance = (1 - fit.ship.getModifiedItemAttr(resonance)) * 100

Also why aren't the alliance tournament ships under Limited Issue Ships?

**Comment by blitzmann** [comment] 2017-10-28 23:06
Duplicate of #1310. Basically this error happens because the Victor (and Virtuoso) aren't completely set up in the game yet, according to the data. They are missing a lot of attributes, attributes that are assumed to be present on a ship.

See https://esi.tech.ccp.is/latest/universe/types/45531/?datasource=tranquility&language=en-us. Compare this with the rifter (https://esi.tech.ccp.is/latest/universe/types/587/?datasource=tranquility&language=en-us) and you can see that the Victor is missing things like dogma attributes and effects.

> Also why aren't the alliance tournament ships under Limited Issue Ships?

They usually are, but it's a manual addition that I have to remember to do. I don't usually keep up with AT prizes or when they drop, so I usually rely on somebody pinging me to get them set up properly.

As for the error, for now I will force these ships to be unpublished, which will cause them not to show up in the search results and hopefully avoid this confusion until they are completed and released by CCP (looks like they are nearly done on SISI)

**Comment by blitzmann** [comment] 2017-10-28 23:24
Labeling this as a v1.34.0 milestone so that I can remember to come back to these and unpublish them with the next release :)

**Comment by blitzmann** [comment] 2017-11-25 05:06
This is now in the development branch, so it should be available in the 1.34 release :)

**Closed** 2017-12-10 23:25 UTC
Labels: done
