### ISSUE TITLE
Agency boosters not present in 2.12.0 release

### ISSUE THREAD

**Issue by fonsui** [pyfa-org/Pyfa#2061] opened 2019-10-09 14:21 UTC
Agency boosters 'Pyrolancea', 'Hardshell', and 'Overclocker' of all grades (Dose I - IV) are not present in the market, by browse or by search.

**Comment by DarkFenX** [comment] 2019-10-09 15:08
Yes, it has been caused by change in data on CCP's side - those boosters now have metagroup 19 ("Limited"), and pyfa was not configured to show it.

It has been fixed in 0121a0064e15b34e273cf11d7d32274bf1acab70, i will try to make bugfix release by the end of the week.

**Closed by DarkFenX** 2019-10-09 15:08 UTC

**Comment by DarkFenX** [comment] 2019-10-09 16:40
I guess i will push release with the fix asap
