### ISSUE TITLE
Error when open ship fitting file

### ISSUE THREAD

**Issue by bilegole** [pyfa-org/Pyfa#2588] opened 2024-02-21 14:04 UTC
## Bug Report
When I try to import ship fiiting, pyfa shows me an error.

### Expected behavior:
Ship fitting should be open

### Actual behavior:
Ship fitting should did not open, an error window show

### Detailed steps to reproduce:
Fit -> Import fitting

### Fits involved in EFT format (Edit > To Clipboard > EFT):
['Marginis' Fortizar, 'Marginis' Fortizar fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]

### Release or development git branch? Please note the release version or commit hash:
v2.58.0、2.57.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
![image](https://github.com/pyfa-org/Pyfa/assets/13775952/9be291d9-a5f8-4a81-92ed-a1bcb76bb6bd)

pyfa v2.58.0
EVE Data Version: 2497879 (2024-02-20 20:05:56)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 855, in fileImportDialog
wx._core.wxAssertionError: C++ assertion ""IsRunning()"" failed at ..\..\src\common\evtloopcmn.cpp(92) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop

**Comment by DarkFenX** [comment] 2024-02-24 00:48
Duplicate of #2552

**Closed by DarkFenX** 2024-02-24 00:48 UTC
