### ISSUE TITLE
Pyfa not updating stats and not refreshing UI upon module change

### ISSUE THREAD

**Issue by GoldenCoins** [pyfa-org/Pyfa#1556] opened 2018-05-10 02:15 UTC
So im having an annoying bug whereby pyfa will not update the UI upon a module change.

I will be modifying my fits, and at somepoint, the math and stats will either stop updating, and occasionally I will click to another fitting tab and the stats from the previous fit will stay.

At this point, I can change the fit but the math and stats don't update.
Also, if I quit pyfa and reload, I usually find that the fits I was editing have missing slots. As if modules I removed stayed removed but none of the modules I added after replaced them.

I'm having to restart pyfa every couple minutes to fix this

**Comment by blitzmann** [comment] 2018-05-10 03:29
Can you please post the log files (specifically the log file for that session if you can)? They can be found under `%userprofile%/.pyfa`

**Comment by blitzmann** [comment] 2018-05-15 01:57
@GoldenCoins any update on those log files? Are you able to reproduce it with specific fits?

**Comment by blitzmann** [comment] 2018-05-15 02:48
Also, seems to be a duplicate of #1551. Please continue conversation there, thanks!

**Closed by blitzmann** 2018-05-15 02:48 UTC
