### ISSUE TITLE
2 annoying bugs

### ISSUE THREAD

**Issue by alexjamcclean** [pyfa-org/Pyfa#1054] opened 2017-03-17 13:55 UTC
In the most current Win exe. version:

* Have no functionality to remove modules! Restarting the programme resets the bug but it come sback after 1-2 mins.

*The market ceases to work after a couple of mins and can't select items to use in fits. Restarting the programme resets the bug but it comes back after 1-2 mins.

Using Windows 8

**Comment by Ebag333** [comment] 2017-03-17 16:00
>Have no functionality to remove modules! 

Do you mean the right click menu is missing remove? If so, there's already a fix for this. 
In the meantime, double click or delete key will remove items. 

>The market ceases to work after a couple of mins and can't select items to use in fits. 

Can you give more information on this? Also, check your user profile directory for the Pyfa log file and share it with us. You can find the path to the home directory in the preferences window under database. You can use gist to paste it to if you don't have anywhere else to upload it to.

**Comment by blitzmann** [comment] 2017-03-19 20:32
Yeah, the remove module/drone/etc option was accidentally removed. Gonna make a point release tomorrow hopefully with that fix.

> The market ceases to work after a couple of mins and can't select items to use in fits.

I have no idea about this - works fine for me. No one else has mentioned this. Perhaps wait for the point release to see if you're still experiencing issues. :)

**Comment by blitzmann** [comment] 2017-03-26 19:42
Closing this due to lack of data / not able to reproduce. Please reopen if you're still experiencing issues :)

**Closed by blitzmann** 2017-03-26 19:42 UTC
