### ISSUE TITLE
probe scan strength does not show correct value after changing launcher

### ISSUE THREAD

**Issue by 1knueller** [pyfa-org/Pyfa#2398] opened 2022-01-14 15:01 UTC
## Bug Report
Probe strength does not update when you change the probe launcher and hit refresh. (core probe launchers can result in different scan strenghts)

### Expected behavior:
scan probe strength should always consider the current fittings launcher

### Actual behavior:
scan probe strength does not respect the currently fitted launcher

### Detailed steps to reproduce:
create anathema fit
add sisters core probe launcher
add sisters core scanner probes
go to charge stats > attributes
see core probe strength in column "current value"
change core probe launcher variant to T1
hit refresh in charge stats window

and you can see the current scan strenght does not change in the window. 
but if you again open charge stats you get the correct value

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Anathema, Anathema fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Scan Rangefinding Array I
Scan Rangefinding Array I
[Empty Med slot]
[Empty Med slot]

Covert Ops Cloaking Device II
Core Probe Launcher I, Sisters Core Scanner Probe
[Empty High slot]

Small Gravity Capacitor Upgrade I
Small Gravity Capacitor Upgrade I

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.39.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win10

**Comment by DarkFenX** [comment] 2022-02-04 21:00
The issue is that info window opens for that specific launcher & its charge. What "change meta level" operation does, is replacing module and its charge with another one. So, when you are looking at charge stats window, this is for old launcher, and for that, it shows correct stats.

One of ways to fix it would be to store position of module/charge for stats window, instead of module itself. But this might have undesirable side-effects (like module swap - refresh - you get new module info there, but you'd expect to still get the same info).

Another fix is to launch UI event during replacement, with data about old and new modules, so that stats windows could be correctly updated.

**Comment by DarkFenX** [comment] 2022-02-04 22:26
Fixed in be73ffd929770fba38bb7d6c8ff3628fc857c4c2 and aa1ecd6beae74b3e2cf63de725c7b1e5949a977f for modules, boosters and implants. For fighters and drones fix seems to be super complex, so not doing that.

**Closed** 2022-02-09 20:49 UTC
Labels: bug, fixed
