### ISSUE TITLE
Crash on deleting fit

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#1055] opened 2017-03-17 18:08 UTC
Steps to reproduce:

1. Create new fit.
2. Rename.
3. Change character.
4. Open new tab
5. Copy first fit.
6. Change character.
7. Delete first fit

I could _only_ get this to work when running in non-debug mode.  Grrrr.

I did catch this error in the logs:
`[2017-03-17 17:58:37.261000] WARNING: gui.builtinViews.fittingView: Caught dead object`

I'm suspecting we might be trying to recalc the fit we just deleted.  Also, we have absolutely no logging on deleting objects, which is just garbage.

A similar bug (same basic steps):
>response : desired fit is deleted from the Fitting Browser pane alas the character selected on the fit I'm viewing changes to the same as in the first (leftmost) of the open fits on screen

Thanks to doc for reporting this on Pyfa Slack!

**Comment by Ebag333** [comment] 2017-03-17 22:22
First method _should_ fall back to the first page, then recalc.

Another way to crash it.

1. Launch pyfa
2. Clone existing fit.
3. Delete existing fit.

**Comment by Ebag333** [comment] 2017-03-17 22:58
From `fittingView.py`:

```
    def Destroy(self):
        self.parent.Unbind(EVT_NOTEBOOK_PAGE_CHANGED, handler=self.pageChanged)
        self.mainFrame.Unbind(GE.FIT_CHANGED, handler=self.fitChanged)
        self.mainFrame.Unbind(gui.shipBrowser.EVT_FIT_RENAMED, handler=self.fitRenamed)
        self.mainFrame.Unbind(gui.shipBrowser.EVT_FIT_REMOVED, handler=self.fitRemoved)
        self.mainFrame.Unbind(gui.marketBrowser.ITEM_SELECTED, handler=self.appendItem)

        d.Display.Destroy(self)
```

The culprit is `d.Display.Destroy(self)`.  It's literally destroying itself, which means that everything else we attach to self (like `self.getActiveFit()` and `self.mainFrame`) all no longer work.  This is an old bit of code (2010), so most likely we weren't attaching all this stuff to `self` back then.

Removing this line of code doesn't _seem_ to break anything, but @blitzmann can you run it through it's paces and see if you see any issues?

I'm going to submit a PR shortly with this change.  Since this is a fairly easily crash to run into, I'll push it against `master`.

**Comment by blitzmann** [comment] 2017-03-18 01:34
Crashing when deleting a fit has been a long time problem - usually causes a seg fault with no real output. Has to do with events firing in the wrong order (last time I delved into it, which was a couple of years ago). it's been notoriously hard to consistently reproduce. Dunno if this is the same thing, but possible

See #164 and all other things that branch from it.

Can't test right now as I'm not at my PC, but will look more into the comments and proposed fix soon.

**Comment by Ebag333** [comment] 2017-03-18 21:34
>Crashing when deleting a fit has been a long time problem - usually causes a seg fault with no real output. Has to do with events firing in the wrong order (last time I delved into it, which was a couple of years ago). it's been notoriously hard to consistently reproduce. Dunno if this is the same thing, but possible

It's not exactly the wrong order, but that's exactly what I thought too when I first looked into it.  The way the code is done, it's easy to fall down that rabbit hole, but it doesn't go anywhere.

The methods above are reproducible 100% of the time for me.

Regardless, we should _not_ be destroying `self`.  We attach everything to it, so that's a really bad thing to do.

#164 might be something else, but I believe that this is actually the root cause.

**Comment by blitzmann** [comment] 2017-03-19 03:04
I can't get it to consistently reproduce, at least with the methods listed above. 

I can, sporadically, get it to crash with having the fitting open when it's deleted, as noted in #164 and all things related to it.

Also, `d.Display.Destroy(self)` is definitely what we want to do. We override it here to clean up some bindings, but we still then need to actually destroy the page. `self` in this case is simply the fitting window being displayed, there's no special purpose here so I'm not sure why it's a really bad thing to remove it. A quick test with that shows that tabs aren't closed properly if this is removed.

The more interesting question is: do we need to clean up those bindings? methinks wx should handle the event binding cleanup when the window is destroyed. Haven't tested that yet.

**Comment by Ebag333** [comment] 2017-03-19 03:49
>I can't get it to consistently reproduce, at least with the methods listed above.

The first method listed is tricky, because I think if you do things slightly out of order then it won't work.

Also, keep in mind, I could _NOT_ get it to work when I was running in debug mode with full logging.

>Also, d.Display.Destroy(self) is definitely what we want to do. We override it here to clean up some bindings, but we still then need to actually destroy the page. self in this case is simply the fitting window being displayed, there's no special purpose here so I'm not sure why it's a really bad thing to remove it. A quick test with that shows that tabs aren't closed properly if this is removed.

Let me walk you through the logic.  In `chromeTabs.py` we have this function:
```
    def DeletePage(self, n, internal=False):
        """
        Deletes page.

        n -- index of page to be deleted
        internal -- True if we're deleting the page from the PFTabsContainer
        """
        page = self.pages[n]
        self.pages.remove(page)
        page.Destroy()

        if not internal:
            # If we're not deleting from the tab, delete the tab
            # (deleting from the tab automatically deletes itself)
            self.tabsContainer.DeleteTab(n, True)

        sel = self.tabsContainer.GetSelected()
        if sel is not None:
            self.activePage = self.pages[sel]
            self.ShowActive()
            wx.PostEvent(self, PageChanged(-1, sel))
        else:
            self.activePage = None
```

Now, `page.Destroy()` is where we dip into the function listed above in `fittingView.py` (it goes through another function, but that doesn't matter).

`page` is a `FittingView` object, remember that.

This is what it looks like right before we execute `page.Destroy()`:
https://puu.sh/uPqAV/c9a2ae7db3.png

And here's right after:
https://puu.sh/uPqIl/696e269693.png

The problem comes not from this, exactly, but a few lines later in the code.

What happens is that `sel = self.tabsContainer.GetSelected()` is returning what it believes to be is a valid object, so we drop down into the if statement.  I believe that this is caused by a race condition, which is why if you slow down the process (by enabling debugging, or even attaching the debugger to the process) _you won't ever get it_.

A few lines later we stacktrace on this line:
`self.ShowActive()`

The error?  Shows that the FittingView object has been deleted.  You can replicate this by running it yourself in debug mode (see here):
https://puu.sh/uPr54/82bc4f0443.png

>A quick test with that shows that tabs aren't closed properly if this is removed.

How are they not removed properly?  I just did a test of it (again) and the tab is removed.

Now _not_ deleting `self ` introduces other problems, but I don't think that those can't be worked around.

I have another idea for handling this, though.

**Comment by blitzmann** [comment] 2017-03-19 04:06
>How are they not removed properly? I just did a test of it (again) and the tab is removed.

Uhh... https://gyazo.com/5450b6d91561a8f211293425d8e85713

Note that the page isn't deleted, because we remove the command to delete it. :)

I am absolutely of the opinion that this is a race condition as you suggest - all signs point to it as noted in the other issues where I've delved into it. The problem is how to fix it. I've been meaning to take a long hard look at how the fit deletion / tab deletion flows into one another, never got around to it.

I also have a feeling that this would help, which I think I noted in the other issues; https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.DestroyLater

But that's not supported in wx2.8, which we still carry around for the mac build. v0v

Don't go too crazy with any potential fix. I have a feeling it should only be a few new conditionals or something.

**Comment by Ebag333** [comment] 2017-03-19 04:08
Weird.  That seriously doesn't happen for me.

If it's the only tab, or the tab on the far right, it deletes fine.  There does seem to be an issue when it's a tab in the middle of two other tabs though.

**Comment by blitzmann** [comment] 2017-03-19 04:09
Also note: this is an actual seg fault at the wxWidget layer (at least the reproductions that I can do). So, try/except generally won't work. :/

**Comment by blitzmann** [comment] 2017-03-19 04:11
> If it's the only tab, or the tab on the far right, it deletes fine. There does seem to be an issue when it's a tab in the middle of two other tabs though.

Nope, not for me. The object still exists, so it's floating around in the GUI (it's container is probably gone though). So for me, having multiple fits open after closing a tab is very glitchy and the fitting window spazes between the deleted view and the active view

**Comment by Ebag333** [comment] 2017-03-19 04:13
>Also note: this is an actual seg fault at the wxWidget layer (at least the reproductions that I can do). So, try/except generally won't work. :/

No, I'm tackling it from the `sel = self.tabsContainer.GetSelected()` side of things.

We _have_ a list of tabs in `self.pages`.  Why are we asking the GUI which page we're on when we should know?

Basically just bypass the race condition entirely.

>Nope, not for me. The object still exists, so it's floating around in the GUI (it's container is probably gone though). So for me, having multiple fits open after closing a tab is very glitchy and the fitting window spazes between the deleted view and the active view

Probably due to using slightly different versions of wx or something.  vOv

**Comment by Ebag333** [comment] 2017-03-19 04:48
Something I forgot to mention.

If you chase this back up the stack, you end up in `fitRemoved` in `fittingView.py`.

`self.parent.DeletePage(self.parent.GetPageIndex(self))` is where we nuke it.

If you check `self` after that line you get....a `wxPyDeadObject`.

Which means that later, when we do:
```
                sFit.refreshFit(self.getActiveFit())
                wx.PostEvent(self.mainFrame, GE.FitChanged(fitID=self.activeFitID))
```
 
Neither line will work.  `self.getActiveFit()` stacktraces because `self` is a wx dead object, which has no function `getActiveFit()`.  And `self.mainFrame` doesn't work, because `mainFrame` doesn't exist on the dead object that replaced the original `self`.

**Comment by Ebag333** [comment] 2017-03-19 04:58
Okay, so I can work around the race condition with `sel = self.tabsContainer.GetSelected()`.

The problem is, as mentioned above, when we get up to `fitRemoved` in `fittingView`, `self` is gone.

I can recreate `self.mainFrame` so that we can get past `fitRemoved` okay.
```
        try:
            # Sometimes there is no active page after deletion, hence the try block
            if isinstance(self, wx._core._wxPyDeadObject):
                # We've destroyed self.  Recreate the mainFrame.
                self.mainFrame = gui.mainFrame.MainFrame.getInstance()
                current_fitID = self.mainFrame.getActiveFit()
                wx.PostEvent(self.mainFrame, GE.FitChanged(fitID=current_fitID))
            else:
                sFit = Fit.getInstance()
                sFit.refreshFit(self.getActiveFit())
                wx.PostEvent(self.mainFrame, GE.FitChanged(fitID=self.activeFitID))
        except wx._core.PyDeadObjectError:
            pyfalog.warning("Caught dead object")
            pass
```

In this case, we we fall into the `if` and not the `else` (old code), so we get out without an exception here.  Problem is, we're just pushing the crash further up the stack (not sure where now).

I feel like this is the wrong way to do this  We're laying work around on top of work around, and will have to do this at each level up the stack.

I believe that the better solution is to tackle the one line identified, and then properly handle switching tabs.

**Comment by Ebag333** [comment] 2017-03-19 06:03
@blitzmann I believe I have a fix.  I'm not experiencing any GUI weirdness.

It's along the lines as before, _not_ destroying the object.  I'm aware that means that "deleted" objects will stay in memory and we're essentially orphaning them, but I don't see a better solution at the moment.

If you can take a look at my branch: https://github.com/Ebag333/Pyfa/tree/Suicide_is_NOT_painless

Changes from current:
1) Don't `page.Destroy()`.  We still remove from the pages list so it's no longer attached to the gui, and it becomes orphaned.  Destroying it is what destroys `self` higher up.  It will get garbage collected when Pyfa is restarted.
2) Use some basic maths instead of `sel = self.tabsContainer.GetSelected()` to avoid the race condition where the variable would return the wrong page.
3) At a higher level (`fittingView`) don't try and get the active fit from `self`.  This doesn't actually find the fit, it just returns `self.activeFitID` which isn't actually going to change.  Instead ask mainFrame what the current fit is, and use that to trigger a refresh.  This will properly grab the current fit, and not simply use a cached variable.

**Comment by blitzmann** [comment] 2017-03-19 20:59
>  It will get garbage collected when Pyfa is restarted.

Well yeah... because pyfa shuts down and releases everything from memory. Not exactly garbage collecting in the traditional sense.

That being said, I can confirm through the wxInspection tools that the pages still hang around, and I'm noticing a quick blip in the pages when changing while using your branch. The fact that the object itself isn't deleted worries me a bit (pyfa is already kinda high on memory usage, and we're keeping full fitting views around in memory). I don't know what that would be like for long-term use - probably negligible, but I feel, like you do, that this isn't the proper way.

So let me see if I understand this since it's been a while since I looked at the code surrounding this. When we delete a fit, we call `fittingView.fitRemoved()`, which then calls on it's parent (the notebook) to delete the page. This then goes through the process of destroying the `fittingView` object that ultimately called it in the first place, when we're still technically in the `fitRemoved() method...? We basically need to make it so that once we call `Destroy()` we can assume never to need that object again...

I want to have a crack at it first. You're solution seems to work for me (can't get it to crash), although I would prefer to actually delete the objects. Additionally, this may have further GUI funkiness on Linux / OS X / wx2.8. I'll take a look to see if there is a bit of reordering I can do; if not, I think it'll be fine to merge your changes in and just deal with it for now as long as this tests out correctly for the other OSs .

**Comment by blitzmann** [comment] 2017-03-19 21:01
Additionally, we could probably create a system that cleans up the pages if we go that route: simply register "deleted" pages with the container, which would periodically go through and `Destroy()` them via a Timer.

**Comment by Ebag333** [comment] 2017-03-19 21:08
>Additionally, we could probably create a system that cleans up the pages if we go that route: simply register "deleted" pages with the container, which would periodically go through and Destroy() them via a Timer. That is hacky as fuck, but it's an option and would probably work.

Hacky as fuck? You just reinvented garbage collection. :D

**Comment by blitzmann** [comment] 2017-03-19 21:09
> Hacky as fuck? You just reinvented garbage collection. :D

basically ya :P

**Comment by Ebag333** [comment] 2017-03-20 01:37
>So let me see if I understand this since it's been a while since I looked at the code surrounding this. When we delete a fit, we call fittingView.fitRemoved(), which then calls on it's parent (the notebook) to delete the page. This then goes through the process of destroying the fittingView object that ultimately called it in the first place, when we're still technically in the fitRemoved() method...? 

You roughly have the gist of it.  Because we're (ab)using `self`, it keeps getting passed down.  What _really_ trips me up is when we're in the method where we murder the page, the `self` there isn't the fittingView object (the page is), but then I remember that we can have parents that have a child that has a child that's it's own parent.

I believe it's basically `I am my own grandpa` in code.  So when we kill the grandkid, the grandparent dies.

>I want to have a crack at it first. You're solution seems to work for me (can't get it to crash), although I would prefer to actually delete the objects. Additionally, this may have further GUI funkiness on Linux / OS X / wx2.8. I'll take a look to see if there is a bit of reordering I can do; if not, I think it'll be fine to merge your changes in and just deal with it for now as long as this tests out correctly for the other OSs .

I don't see any reason why it'd break the GUI, we're dropping the page out from the list, so it's orphaned but shouldn't be anything that wx cares or knows about anymore.  You might be seeing a blip because we've switched to actually fetching the active selected tab rather than using a cached one.  Or it could be because we're forcing it to switch tabs based on the logic instead of just relying on the GUI to tell us which tab we should be using.

(Logic, for that btw, is open tab on right if there is one, open tab on left if there isn't, and do nothing if there are no more tabs.)

>We basically need to make it so that once we call Destroy() we can assume never to need that object again...
>The fact that the object itself isn't deleted worries me a bit (pyfa is already kinda high on memory usage, and we're keeping full fitting views around in memory).

Yeah, I actually did a search through the codebase to see how many times we're destroying objects.  This is actually one of the few.

How about a garbage service?  When we pop the page off the stack here, we register it with the garbage service which then cleans it up at a future time?

My worry is that with pages, at least, if we every destroy them, we will be destroying the instance that they were generated from, and that would cause the same breakage that we're seeing now.  But at least if we garbage collected them, they're no longer orphaned and we at least know about them.

Could be something to use for future use as well, and start cleaning up after ourselves.

For me, I don't really see Pyfa as being very high on memory usage.  Even launching it with the debugger hooked in, it's less than 100 megs.  For folks with gigs of RAM, that's pretty minimal.

**Comment by Rarilmar** [comment] 2017-05-12 13:22
I noticed with the latest version (1.29.1) that deleting a fit creates an error message, but pyfa continues to function after closing it.
![untitled](https://cloud.githubusercontent.com/assets/6603349/25999805/319ca5e2-372f-11e7-84f2-8a40bd2c347a.jpg)

**Comment by dyh135** [comment] 2017-06-03 03:52
If I have too many fitting tabs opened(10 or higher ), and deleting fit might get the error, after closing all the tab, and it never happen again. hope it may help to reproduce this issue.

**Comment by DarkFenX** [comment] 2019-10-02 12:05
I believe it was fixed when i reworked dialog windows and how they are handled. It was causing crash on Mac OS with 100% reproducibility, and after further fixes I didn't have a single crash for a long time.

Reason was in how we work with wx, it was race condition between dialog destruction and its parent destruction. If it still happens, please reopen.

**Closed by DarkFenX** 2019-10-02 12:05 UTC
