### ISSUE TITLE
Prospect and Covert Ops Cloaks

### ISSUE THREAD

**Issue by Xandulis** [pyfa-org/Pyfa#473] opened 2015-12-12 02:36 UTC
The coverts ops cloaks can not be fitted on the prospect.  Using version 1.17.1 windows.

**Comment by blitzmann** [comment] 2015-12-21 00:33
The problem is that they added `canFitShipType6` attribute to the cloak, but pyfa only checks up to `canFitShipType5`. CCP seems to have changed the attributes since the release and should be fixed with the 1.18 release.

**Comment by blitzmann** [comment] 2016-01-12 22:37
Hmm, seems this isn't really fixed. Opps. I will fix this in the source and will make fix available in point release

**Closed** 2016-02-10 20:05 UTC
Labels: fixed
