### ISSUE TITLE
wxPython 3.0 pyfa mac problems

### ISSUE THREAD

**Issue by JoshuaNotowitz** [pyfa-org/Pyfa#521] opened 2016-02-15 09:59 UTC
Its seems that the mouse tracks slowly when using the wxPython 3.0 pyfa.  Here is a [Video](https://youtu.be/mYoFabipVGE) of what I mean.  Its a little hard to tell in the video but pyfa only registers mouse clicks when where it think the mouse is catches up to where the mouse actually is.  There is also a problem where it will sometimes fail to load a group of fits and need to be restarted after that happens.  There are also long load times when loading a saved fit for the first time that session.

**Comment by blitzmann** [comment] 2016-02-16 02:07
OS X version, and are you using `-mac` or `-mac-deprecated`?

**Comment by JoshuaNotowitz** [comment] 2016-02-16 10:46
that's -mac version, -mac-deprecated doesn't have the slow down problem

**Comment by blitzmann** [comment] 2016-02-19 03:21
And your os x version?

**Comment by blitzmann** [comment] 2016-02-21 07:49
Of course it's 10.11. Nothing but problems there =(

**Comment by blitzmann** [comment] 2016-03-03 04:41
I have looked into this and can confirm that this happens on 10.11 (10.10 seems unaffected).

I am going to mark this as a duplicate of #438 - there seems to be differences in how OS X 10.11 renders content / interacts with wxWidgets compared to previous versions. I believe that this results in noticeable lag with our custom-drawn widgets when the visuals change in quick succession (such as the highlighting and the gauge animations).

Please go to that issue to follow discussion and progress. =)

**Closed by blitzmann** 2016-03-03 04:41 UTC
Labels: osx
