### ISSUE TITLE
Dual prop enabled at the same time on import

### ISSUE THREAD

**Issue by geoff-kruss** [pyfa-org/Pyfa#522] opened 2016-02-17 16:02 UTC
Importing a fitting that has both an afterburner and a microwarpdrive propulsion module causes both modules to be activated simultaneously, the usual check that happens when enabling a prop mod doesn't happen on import.

I have only tested this with EFT formatted fittings and only importing via the clipboard, though I would expect that the issue would exist even if importing via some other method. I can reproduce it easily, with varying ship and module combinations. 

In addition, the calculated velocity for the ship appears to take the base velocity, plus the percentage modifier of whichever prop mod is in the higher position, and then applies the next modifier on top of this new total creating really silly looking speeds.

pyfa 1.18.0 - this is where I initially spotted the issue
pyfa 1.19.1 - tested, bug still exists

Only able to test on Windows 10.

Thanks

EDIT: Perhaps a solution would be to pick whichever module is in the highest slot and enable that ? Or leave both disabled... 

EDIT: In issue #512 there is talk of working on validation during import, so this is more than likely related.

**Comment by blitzmann** [comment] 2016-02-17 18:43
You are correct with your edit, this seems to be a duplicate of #512. Hopefully I can get around to fixing this before the next release in March - it should be really simple.

**Closed by blitzmann** 2016-02-17 18:43 UTC
Labels: duplicate
