### ISSUE TITLE
Comparing DPS in graph mode 

### ISSUE THREAD

**Issue by Ashcoat** [pyfa-org/Pyfa#2042] opened 2019-09-10 20:44 UTC
I was comparing the DPS of 2 Drekavac fits with only their guns, one with the new Mimesis implants, and one without.

amid fumbling around trying to see if I could adjust the scale of the graph to get a better look at the first few ramp cycles over time. While clicking the drop down menu for the Y-axis I was hit with this error box, including the following contents. 

pyfa v2.11.0
EVE Data Version: 1564394 (2019-09-10 04:28:33)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.8
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 328, in OnYTypeUpdate
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 175, in _updateInputs
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 452, in _storeCurrentValues
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 370, in getValues
AttributeError: 'NoneType' object has no attribute 'handle'

**Comment by DarkFenX** [comment] 2019-09-10 20:52
Could you say which x and y selections you had before the switch, and to which selection did you switch?

**Comment by Ashcoat** [comment] 2019-09-10 20:58
I think I changed from y-axis drop down from "Damage inflicted" to "DPS", while the X-axis was on "Time, s". 
The Error happened on click, perhaps I might have clicked outside the drop down menu.

**Comment by Ashcoat** [comment] 2019-09-10 20:59
I can also see a small rectangular box, that looks like a "failed to load image icon" when I swap the menu, centered just above and to the left of the menu itself. It disappears just after the swap is complete.

**Comment by Ashcoat** [comment] 2019-09-10 21:01
I can't seem to duplicate, the error now though.

**Comment by Ashcoat** [comment] 2019-09-10 21:04
ah here we go so if you delete the fields to the right of the drop down the default is "0-80" and then try to change the drop down it spits out the error.

pyfa v2.11.0
EVE Data Version: 1564394 (2019-09-10 04:28:33)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.8
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 328, in OnYTypeUpdate
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 197, in _updateInputs
  File "C:\projects\pyfa\graphs\gui\ctrlPanel.py", line 232, in __addInputField
  File "C:\projects\pyfa\gui\utils\inputs.py", line 113, in __init__
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

**Comment by Ashcoat** [comment] 2019-09-10 21:10
Here are some photos
https://imgur.com/a/1sG93w8

**Comment by DarkFenX** [comment] 2019-09-11 05:37
2nd issue (`TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'`) fixed in 6e9fc1d1d9b536c4145ef6e17eab2d654ad71fad. First, however, seems to be consequence of another issue (possibly the one I've just fixed) and I am not willing to fix it directly, but rather seek for the root cause.

If you receive error message `AttributeError: 'NoneType' object has no attribute 'handle'` again, before receiving any other error message, please reopen this or create new issue.

**Closed by DarkFenX** 2019-09-11 05:37 UTC
Labels: bug
