### ISSUE TITLE
can't fill last turret/launcher hardpoint from "market" or cargo

### ISSUE THREAD

**Issue by PhilippeJara** [pyfa-org/Pyfa#2164] opened 2020-04-15 14:19 UTC
## Bug Report
can't fill last turret/launcher hardpoint in any fit from "market"

### Expected behavior:
I should be able to click or drag from "market" a rocket launcher II for example into a hookbill 3 times to the highs for its 3 highs

### Actual behavior:
it works as it should up until the last launcher hardpoint, at that point you cannot add any more, so in the case of a hookbill it has 2/3 missile hardpoints used. You are still able to fit all of them if you ctrl-click and drag one of the previously fitted rocket launchers to the empy high. This happens with both turrets and missiles and in all ships i tried with.

### Detailed steps to reproduce:
get a ship
fit it until it has all but one hardpoint used
try to fit the last one from either "market" or its cargo

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Caldari Navy Hookbill, Timecube's Caldari Navy Hookbill]

Ballistic Control System II
Damage Control II

1MN Y-S8 Compact Afterburner
Caldari Navy Medium Shield Extender
Fleeting Compact Stasis Webifier
Fleeting Compact Stasis Webifier
Initiated Compact Warp Scrambler

Rocket Launcher II, Scourge Rage Rocket
Rocket Launcher II
[Empty High slot]

Small Anti-EM Screen Reinforcer I
Small Anti-Thermal Screen Reinforcer I
Small Bay Loading Accelerator II

Agency 'Pyrolancea' DB5 Dose II

Scourge Rage Rocket x50
Rocket Launcher II x2

[Megathron, blaster]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
release v2.20.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

### Other relevant information:
fuck gate guns

**Comment by DarkFenX** [comment] 2020-04-15 14:40
Duplicate of #2162. Update to v2.21.1, it has that issue fixed.

ps Fuck security status loss!

**Closed by DarkFenX** 2020-04-15 14:40 UTC
