### ISSUE TITLE
[Feature Request] Fit Tagging

### ISSUE THREAD

**Issue by aaronmallen** [pyfa-org/Pyfa#1141] opened 2017-05-06 04:29 UTC
It would be amazing to see a fit tagging feature in pyfa similar to the one available on [Osmium](https://o.smium.org) so that if I create a fit or two and tag it "newbro" and later search "newbro" in my fits window it would show up in that search.

**Comment by blitzmann** [comment] 2017-05-06 16:10
Yep, this is an often requested feature (see #18). I do have plans to make this one of the next pushes of development after I release the next stable release.

I did some work on this in the past and got it mostly working, the problem was that we didn't really have a good way of displaying them. But now that we have the Notes section, I think we can actually utilize it as a "Meta" section and store the tags assigned to the fit there. Any other thoughts on how it might work?

**Comment by aaronmallen** [comment] 2017-05-06 19:39
Firstly I am sorry, I did a search and only found an issue related to module tagging... I guess my query wasn't thorough enough :( 

IMO the way I kinda see this working is to have a section on the right menu under the fit name. In the case where there are more tags than space display as many as you can and then display an ellipse. 

More importantly you could opt to not display them at all... The important part of the feature is that the fit shows up when the tag is queried.

**Comment by aaronmallen** [comment] 2017-05-06 19:48
Bonus points if typing a `#word` in the name automatically converts into a tag.

**Comment by blitzmann** [comment] 2017-05-06 19:53
> Firstly I am sorry, I did a search and only found an issue related to module tagging... I guess my query wasn't thorough enough :(

No worries, that other issue hasn't been updated in years, so it's not too much use. I should close that one and simply stick with this one

> Bonus points if typing a #word in the name automatically converts into a tag.**

That's an interesting idea :)

I'll take a look to see where it's at or if I even have that branch anymore and report back when I have something you can look at and test. Like I said though, it won't be with the next release (1.29), but hopefully the release after that. :)

**Comment by aaronmallen** [comment] 2017-05-06 20:53
Awesome I look forward to trying it out!

**Comment by blitzmann** [comment] 2018-05-28 23:35
So, this kind of got away form me, haven't really looked at fit tagging. It's still a planned feature, it's just a matter of squeezing it into development - unfortunately there are higher-priority tasks to be done, especially recently with the move to 2.x. >.<

Gonna close this as it's truly a duplicate of #18 (holy fuck that was a long time ago...). whenever I do get around to this, I'll be posting updates in that thread. 😄

**Closed by blitzmann** 2018-05-28 23:35 UTC
