### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by petsagouris** [pyfa-org/Pyfa#1213] opened 2017-06-03 09:21 UTC
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
While Pyfa didn't have focus, I right clicked on one of the two ancillary shield boosters. 

### Expected behavior:
No error dialog, just the contextual menu.

### Actual behavior:
It gave me the "Error!" dialog. Message attached.

### Detailed steps to reproduce:
Didn't care to reproduce. Sorry.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

> [Slasher, Arty test]
> 
> Power Diagnostic System I
> Counterbalanced Compact Gyrostabilizer
> 
> Initiated Compact Warp Disruptor
> 1MN Y-S8 Compact Afterburner
> Small Ancillary Shield Booster, Cap Booster 50
> Small Ancillary Shield Booster, Cap Booster 50
> 
> 200mm Light Prototype Automatic Cannon, EMP S
> 200mm Light Prototype Automatic Cannon, EMP S
> 200mm Light Prototype Automatic Cannon, EMP S
> Small Infectious Scoped Energy Neutralizer
> 
> Small Projectile Burst Aerator I
> Small Projectile Collision Accelerator I
> [Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
 Windows 10

### Other relevant information:

> OS version: 	Windows-8-6.2.9200
> Python: 	2.7.10
> wxPython: 	3.0.2.0
> SQLAlchemy: 	1.0.5
> Logbook: 	1.0.0
> pyfa version: 1.29.3 Stable - YC119.5 1.0
> pyfa root: C:\Program Files (x86)\pyfa
> save path: C:\Users\George\.pyfa
> fs encoding: mbcs
> 
> EXCEPTION: 'NoneType' object has no attribute 'name'
> 
>   File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
>   File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 577, in spawnMenu
>     menu = ContextMenu.getMenu(selection, *contexts)
>   File "C:\Program Files (x86)\pyfa\library.zip\gui\contextMenu.py", line 85, in getMenu
>     sub = m.getSubMenu(srcContext, selection, rootMenu, it, rootItem)
>   File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinContextMenus\changeAffectingSkills.py", line 88, in getSubMenu
>     bitmap = BitmapLoader.getBitmap("lvl%s" % skill.level, "gui")
>   File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\character.py", line 337, in level
>     if self.character.name == "All 5":
> 
>

**Comment by blitzmann** [comment] 2017-06-03 16:38
Did you update your API information for that character by chance? This is an error we have been getting and I'm not sure of the cause of it (and I haven't been able to reproduce), see #1182. Is it easy for you to reproduce?

The error is simple to understand - it's getting the level for a skill, however the skill apparently doesn't have a character associated with it. But a skill should always have a character. Would you mind sending me your `%userprofile%/.pyfa` directory zipped up to sable.blitzmann@gmail.com? It will contain your user database and log files, which might give a hint as to what's going on.

**Comment by petsagouris** [comment] 2017-06-03 17:33
hm ye I update the API of that characters many times with the use of that convenient button ;).

i've send the .pyfa folder.

**Comment by blitzmann** [comment] 2017-09-22 06:13
Duplicate #1234 (actually that is duplicate of this, but gonna keep discussion in that one :))

**Closed by blitzmann** 2017-09-22 06:13 UTC
