### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by traugdor** [pyfa-org/Pyfa#1265] opened 2017-08-04 18:28 UTC
Software just completely fails to startup on a forwarded X11 session over SSH

OS version: Ubuntu Server 16.04.3 LTS
Python: 2.7.12
wxPython: 3.0.2.0
SQLAlchemy:  1.2.0b2
Logbook: 1.1.0
pyfa version: YC119.7 - v1.30.0

```
[2017-08-04 18:01:35.704901] CRITICAL: __main__: Exception in main thread: 'PFTabsContainer' object has no attribute 'efxBmp'
[2017-08-04 18:01:35.705103] CRITICAL: __main__:   File "/home/user/Desktop/pyfa/gui/chromeTabs.py", line 1173, in OnPaint
[2017-08-04 18:01:35.705276] CRITICAL: __main__:     mdc.DrawBitmap(self.efxBmp, posx, posy, True)
```

Issue is able to be reproduced consistently on my system as outlined above. Downgrading any dependencies did not help that I could see.

**Comment by pahakalle** [comment] 2017-08-28 00:41
why are you running it on a forwarded X11 session?

**Comment by tommyapeldk** [comment] 2017-08-29 19:24
Same here with local python 2.7.13

**Comment by blitzmann** [comment] 2017-09-19 03:44
@tommyapeldk can you please post the error that you get as well?

As for this issue... forwarded X11 session. I'm sorry, but I have absolutely no experience in this. @traugdor Approx how long would it take to get a test bed set up using ubuntu server with a ubuntu / debian client? Would you be willing to get with me sometime to walk me through it? Please let me know, and sorry for the late reply!

**Comment by tommyapeldk** [comment] 2017-09-19 07:37
Can't copy the text so you'll have to do with a screenshot, sorry.
https://imgur.com/a/J8qG3

**Comment by traugdor** [comment] 2017-09-19 14:34
You can install Ubuntu Server onto any old machine you have laying around. It's very lightweight and doesn't require any special configuration outside of the normal configuration for a fresh headless Linux installation.

**Comment by blitzmann** [comment] 2017-09-19 23:22
@traugdor are you by chance getting the same error when running locally instead of via X11 forwarding?

I am familiar with linux, but extremely unfamiliar with running X11 in a client/server setting, and I've never tunneled it through ssh before. So it would be great if you can supply a quick how to. However, since @tommyapeldk is getting the same error on his local machine, methinks it's not about the X11 forwarding. Will take a look after downloading Ubuntu server and installing on VM, hopefully I can reproduce :)

**Comment by tommyapeldk** [comment] 2017-09-19 23:25
No worries, if you need help just give a shout

**Comment by blitzmann** [comment] 2017-09-24 00:48
I can't reproduce unfortunately, so I'm gonna need some help from you guys. Can you replace the UpdateTabFX() function found on line 1188 in `gui/chromeTabs` with:

```
   def UpdateTabFX(self):
        self.tabShadow.SetSize((self.tabMinWidth, self.height + 1))
        fxBmp = self.tabShadow.Render()

        simg = fxBmp.ConvertToImage()
        if not simg.HasAlpha():
            simg.InitAlpha()
        simg = simg.Blur(2)
        simg = simg.AdjustChannels(0.3, 0.3, 0.3, 0.35)

        self.efxBmp = wx.BitmapFromImage(simg)
```

The error is complaining about self.efxBmp being missing, and UpdateTabFX is where it's created. However there originally is a conditional there that may be blocking it from running (presumably so we don't have to re-draw it if we don't have to - this is old code from years ago, so I'm not 100% sure of the specifics of each line).

If that works for you guys, that's a new clue as to what may be happening, and hopefully I can get a fix ut for it.) Additionally, if either of you have any development experience, feel free to load up pyCharm and use the debugger to try to figure out the cause of it breaking.

**Comment by tommyapeldk** [comment] 2017-09-24 01:38
bing, that worked for me, everything renders now.

**Comment by blitzmann** [comment] 2017-09-24 02:13
k, well that gives us a hint, but it's not really a fix. That function now runs all the time, instead of when needed (pretty inefficient).

Can you try this:

```
    def UpdateTabFX(self):
        w, h = self.tabShadow.GetSize()
        if self.efxBmp is None or w != self.tabMinWidth:
            self.tabShadow.SetSize((self.tabMinWidth, self.height + 1))
            fxBmp = self.tabShadow.Render()

            simg = fxBmp.ConvertToImage()
            if not simg.HasAlpha():
                simg.InitAlpha()
            simg = simg.Blur(2)
            simg = simg.AdjustChannels(0.3, 0.3, 0.3, 0.35)

            self.efxBmp = wx.BitmapFromImage(simg)
```

That should check if `efxBmp` exists and, if not, create it regardless of if that other check happens.

**Comment by tommyapeldk** [comment] 2017-09-24 11:05
OS version: 	Linux-4.12.5-gentoo-x86_64-Intel-R-_Core-TM-_i5-4670K_CPU_@_3.40GHz-with-gentoo-2.4.1
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.11
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: /home/tommy/pyfa
save path: /home/tommy/.pyfa
fs encoding: UTF-8

EXCEPTION: 'PFTabsContainer' object has no attribute 'efxBmp'

  File "./pyfa.py", line 384, in <module>
    MainFrame(options.title)
  File "/home/tommy/pyfa/gui/mainFrame.py", line 178, in __init__
    self.additionsPane = AdditionsPane(self.fitting_additions_split)
  File "/home/tommy/pyfa/gui/additionsPane.py", line 62, in __init__
    self.notebook.AddPage(self.drone, "Drones", tabImage=droneImg, showClose=False)
  File "/home/tommy/pyfa/gui/chromeTabs.py", line 229, in AddPage
    self.tabsContainer.AddTab(tabTitle, tabImage, showClose)
  File "/home/tommy/pyfa/gui/chromeTabs.py", line 1208, in AddTab
    self.AdjustTabsSize()
  File "/home/tommy/pyfa/gui/chromeTabs.py", line 1269, in AdjustTabsSize
    self.UpdateTabFX()
  File "/home/tommy/pyfa/gui/chromeTabs.py", line 1189, in UpdateTabFX
    if self.efxBmp is None or w != self.tabMinWidth:

**Comment by blitzmann** [comment] 2017-09-24 16:34
Use the file that I linked - I realized there were a few other changes that you needed to do before this would work (initializing `eftBmp` in `__init__`)

**Comment by tommyapeldk** [comment] 2017-09-24 16:45
sorry didn't see that link, I applied the patch and it still works.

**Comment by blitzmann** [comment] 2017-09-24 17:14
Sweet, that should do it then. New release will be out tonight :) Thanks for taking the time to help troubleshoot!

**Comment by tommyapeldk** [comment] 2017-09-24 17:25
sure no problem, have you comitted to bug/1265 branch yet?

**Comment by blitzmann** [comment] 2017-09-24 17:30
yep, just merged into master :)

**Comment by tommyapeldk** [comment] 2017-09-24 17:35
sweet, I'll switch back to master then

**Comment by tommyapeldk** [comment] 2017-09-24 17:40
ok, back on master and everything works again as expected, thanks for the effort.

**Closed** 2017-09-24 22:38 UTC
Labels: bug, fixed
